fimc-is-module-objs := fimc-is-module-6b2.o \
		fimc-is-device-8b1.o \
		fimc-is-module-6d1.o \
		fimc-is-module-5e3.o \
		fimc-is-module-imx135.o \
		fimc-is-module-imx135.o \
		fimc-is-module-3l2.o \
		fimc-is-module-2p2.o \
		fimc-is-module-2p2_12m.o \
		fimc-is-module-2p8.o \
		fimc-is-module-2t2.o \
		fimc-is-module-2p3.o \
		fimc-is-module-2l1.o \
		fimc-is-module-3h5.o \
		fimc-is-module-3h7.o \
		fimc-is-module-3h7_sunny.o \
		fimc-is-module-4e5.o \
		fimc-is-module-6a3.o \
		fimc-is-module-imx175.o \
		fimc-is-module-imx240.o \
		fimc-is-module-imx219.o \
		fimc-is-module-imx260.o \
		fimc-is-module-4h5.o \
		fimc-is-module-4e6-c2.o \
		fimc-is-module-4e6.o \
		fimc-is-module-3m2.o \
		fimc-is-module-5e2.o \
		fimc-is-module-virtual-zebu.o \
		fimc-is-module-dsim.o \
		fimc-is-module-virtual.o \
		fimc-is-module-3p3.o \
		fimc-is-module-5e6.o

obj-$(CONFIG_MODULE_ALL_INCLUDE) += fimc-is-module.o

obj-$(CONFIG_CAMERA_SENSOR_6B2_OBJ) += fimc-is-module-6b2.o
obj-$(CONFIG_CAMERA_SENSOR_8B1_OBJ) += fimc-is-device-8b1.o
obj-$(CONFIG_CAMERA_SENSOR_6D1_OBJ) += fimc-is-module-6d1.o
obj-$(CONFIG_CAMERA_SENSOR_5E3_OBJ) += fimc-is-module-5e3.o
obj-$(CONFIG_CAMERA_SENSOR_IMX134_OBJ) += fimc-is-module-imx134.o
obj-$(CONFIG_CAMERA_SENSOR_IMX135_OBJ) += fimc-is-module-imx135.o
obj-$(CONFIG_CAMERA_SENSOR_3L2_OBJ) += fimc-is-module-3l2.o
obj-$(CONFIG_CAMERA_SENSOR_2P2_OBJ) += fimc-is-module-2p2.o
obj-$(CONFIG_CAMERA_SENSOR_2P2_12M_OBJ) += fimc-is-module-2p2_12m.o
obj-$(CONFIG_CAMERA_SENSOR_2P8_OBJ) += fimc-is-module-2p8.o
obj-$(CONFIG_CAMERA_SENSOR_2T2_OBJ) += fimc-is-module-2t2.o
obj-$(CONFIG_CAMERA_SENSOR_2P3_OBJ) += fimc-is-module-2p3.o
obj-$(CONFIG_CAMERA_SENSOR_2L1_OBJ) += fimc-is-module-2l1.o
obj-$(CONFIG_CAMERA_SENSOR_3H5_OBJ) += fimc-is-module-3h5.o
obj-$(CONFIG_CAMERA_SENSOR_3H7_OBJ) += fimc-is-module-3h7.o
obj-$(CONFIG_CAMERA_SENSOR_3H7_SUNNY_OBJ) += fimc-is-module-3h7_sunny.o
obj-$(CONFIG_CAMERA_SENSOR_4E5_OBJ) += fimc-is-module-4e5.o
obj-$(CONFIG_CAMERA_SENSOR_6A3_OBJ) += fimc-is-module-6a3.o
obj-$(CONFIG_CAMERA_SENSOR_IMX175_OBJ) += fimc-is-module-imx175.o
obj-$(CONFIG_CAMERA_SENSOR_IMX240_OBJ) += fimc-is-module-imx240.o
obj-$(CONFIG_CAMERA_SENSOR_IMX219_OBJ) += fimc-is-module-imx219.o
obj-$(CONFIG_CAMERA_SENSOR_IMX260_OBJ) += fimc-is-module-imx260.o
obj-$(CONFIG_CAMERA_SENSOR_4H5_OBJ) += fimc-is-module-4h5.o
obj-$(CONFIG_CAMERA_SENSOR_4E6_OBJ) += fimc-is-module-4e6.o
obj-$(CONFIG_CAMERA_SENSOR_4E6_C2_OBJ) += fimc-is-module-4e6-c2.o
obj-$(CONFIG_CAMERA_SENSOR_3M2_OBJ) += fimc-is-module-3m2.o
obj-$(CONFIG_CAMERA_SENSOR_5E2_OBJ) += fimc-is-module-5e2.o
obj-$(CONFIG_CAMERA_SENSOR_VIRTUAL_ZEBU_OBJ) += fimc-is-module-virtual-zebu.o
obj-$(CONFIG_CAMERA_SENSOR_DSIM_OBJ) += fimc-is-module-dsim.o
obj-$(CONFIG_CAMERA_SENSOR_VIRTUAL_OBJ) += fimc-is-module-virtual.o
obj-$(CONFIG_CAMERA_SENSOR_3P3_OBJ) += fimc-is-module-3p3.o
obj-$(CONFIG_CAMERA_SENSOR_5E6_OBJ) += fimc-is-module-5e6.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/vendor
