# SPDX-License-Identifier: GPL-2.0
# Samsung pin control drivers

ccflags-y := $(KBUILD_FP_SENSOR_CFLAGS)

obj-$(CONFIG_PINCTRL_SAMSUNG)	+= pinctrl-samsung.o
obj-$(CONFIG_PINCTRL_EXYNOS)	+= pinctrl-exynos.o
obj-$(CONFIG_PINCTRL_EXYNOS_ARM)	+= pinctrl-exynos-arm.o
obj-$(CONFIG_PINCTRL_EXYNOS_ARM64)	+= pinctrl-exynos-arm64.o
obj-$(CONFIG_PINCTRL_EXYNOS5440)	+= pinctrl-exynos5440.o
obj-$(CONFIG_PINCTRL_S3C24XX)	+= pinctrl-s3c24xx.o
obj-$(CONFIG_PINCTRL_S3C64XX)	+= pinctrl-s3c64xx.o
obj-$(CONFIG_SEC_GPIO_DVS)	+= secgpio_dvs.o
