obj-$(CONFIG_SND_SOC_SAMSUNG_ABOX) += abox_util.o abox_dbg.o abox_dump.o abox_log.o abox_gic.o abox.o abox_soc.o abox_core.o abox_rdma.o abox_wdma.o abox_if.o abox_effect.o abox_vss.o abox_failsafe.o abox_vdma.o abox_msg.o abox_ipc.o abox_qos.o abox_mmapfd.o
obj-$(CONFIG_SND_SOC_SAMSUNG_ABOX_V1) += abox_cmpnt_v10.o
obj-$(CONFIG_SND_SOC_SAMSUNG_ABOX_V2) += abox_cmpnt_v20.o
obj-$(CONFIG_SEC_SND_ADAPTATION) += abox_adaptation.o
