#
# Copyright (c) 2013 Samsung Electronics Co., Ltd.
#		http://www.samsung.com
#
# Licensed under GPLv2
#

obj-$(CONFIG_EXYNOS_MIPI_DSIM) += timenval.o panel.o panel_bl.o dimming.o panel_drv.o panel_irc.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3HF3) += s6e3hf3/s6e3hf3.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3HF4) += s6e3hf4/s6e3hf4.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3HA6) += s6e3ha6/s6e3ha6.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3HA8) += s6e3ha8/s6e3ha8.o s6e3ha8/s6e3ha8_aod.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3HA9) += s6e3ha9/s6e3ha9.o s6e3ha9/s6e3ha9_aod.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3FA7) += s6e3fa7/s6e3fa7.o s6e3fa7/s6e3fa7_aod.o
obj-$(CONFIG_EXYNOS_DECON_MDNIE_LITE) += mdnie.o
obj-$(CONFIG_EXYNOS_DECON_LCD_SYSFS) += sysfs.o
obj-$(CONFIG_EXYNOS_DECON_LCD_SPI) += spi.o
obj-$(CONFIG_EXYNOS_DECON_LCD_COPR) += copr.o
obj-$(CONFIG_ACTIVE_CLOCK) += active_clock.o
obj-$(CONFIG_DISPLAY_USE_INFO) += dpui.o
obj-$(CONFIG_PANEL_NOTIFY) += panel_notify.o
obj-$(CONFIG_SUPPORT_DDI_FLASH) += panel_poc.o
obj-$(CONFIG_EXTEND_LIVE_CLOCK) += aod/aod_drv.o
obj-$(CONFIG_SUPPORT_POC_SPI) += panel_spi.o
obj-$(CONFIG_DYNAMIC_FREQ) += dynamic_freq.o
obj-$(CONFIG_SUPPORT_DISPLAY_PROFILER) += display_profiler/display_profiler.o s6e3ha9/s6e3ha9_profiler.o