obj-$(CONFIG_CSIS_V3_2) += fimc-is-hw-csi-v3_2.o
obj-$(CONFIG_CSIS_V3_4) += fimc-is-hw-csi-v3_4.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/include
