# Cirrus Logic pinctrl drivers
obj-$(CONFIG_PINCTRL_MADERA)	+= pinctrl-madera.o
ifeq ($(CONFIG_PINCTRL_CS47L15),y)
obj-$(CONFIG_PINCTRL_MADERA)	+= pinctrl-cs47l15.o
endif
ifeq ($(CONFIG_PINCTRL_CS47L35),y)
obj-$(CONFIG_PINCTRL_MADERA)	+= pinctrl-cs47l35.o
endif
ifeq ($(CONFIG_PINCTRL_CS47L85),y)
obj-$(CONFIG_PINCTRL_MADERA)	+= pinctrl-cs47l85.o
endif
ifeq ($(CONFIG_PINCTRL_CS47L90),y)
obj-$(CONFIG_PINCTRL_MADERA)	+= pinctrl-cs47l90.o
endif
ifeq ($(CONFIG_PINCTRL_CS47L92),y)
obj-$(CONFIG_PINCTRL_MADERA)	+= pinctrl-cs47l92.o
endif

