#
# Copyright (c) 2016 Samsung Electronics Co., Ltd.
#              http://www.samsung.com
#
# Licensed under GPLv2
#

repeater-objs := repeater_dev.o repeater_buf.o
obj-$(CONFIG_VIDEO_EXYNOS_REPEATER)       += repeater.o
