#
# Exynos HDCP drivers
#

# HDCP
obj-$(CONFIG_EXYNOS_HDCP2)	+= exynos-hdcp2-session.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= exynos-hdcp2-teeif.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= exynos-hdcp2.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= exynos-hdcp2-misc.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= exynos-hdcp2-encrypt.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= exynos-hdcp2-crypto.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= exynos-hdcp2-protocol-msg.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= iia_link/exynos-hdcp2-iia-auth.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= iia_link/exynos-hdcp2-iia.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= iia_link/exynos-hdcp2-iia-selftest.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= dp_link/exynos-hdcp2-dplink-inter.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= dp_link/exynos-hdcp2-dplink.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= dp_link/exynos-hdcp2-dplink-if.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= dp_link/exynos-hdcp2-dplink-auth.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= dp_link/exynos-hdcp2-dplink-protocol-msg.o
obj-$(CONFIG_EXYNOS_HDCP2)	+= dp_link/exynos-hdcp2-dplink-selftest.o
