obj-$(CONFIG_BCM_GPS_TTY_DRIVER) += bcm_gps_tty.o
obj-$(CONFIG_BCM_GPS_I2C_DRIVER) += bcm_gps_i2c.o
obj-$(CONFIG_BCM_GPS_SPI_DRIVER) += bcm_gps_spi.o
obj-$(CONFIG_BCM_GPS_SPI_DRIVER) += bcm_gps_regs.o
obj-$(CONFIG_BCM_GPS_SPI_DRIVER) += bcm_gps_mem.o
obj-$(CONFIG_BCM_GPS_HOSTWAKE_DRIVER) += bcm_gps_hostwake.o
obj-$(CONFIG_SENSORS_SSP_BBD) += bbd_rpc_lh.o bbd.o
