obj-$(CONFIG_FIMC_BNS_V2_0) += fimc-is-hw-flite-v2_0.o
obj-$(CONFIG_FIMC_BNS_V4_0) += fimc-is-hw-flite-v4_0.o
obj-$(CONFIG_FIMC_BNS_V4_10_0) += fimc-is-hw-flite-v4_10_0.o
obj-$(CONFIG_FIMC_BNS_V4_20_0) += fimc-is-hw-flite-v4_20_0.o
obj-$(CONFIG_FIMC_BSC_V1_20_0) += fimc-is-hw-bsc-v1_20_0.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/include
