obj-$(CONFIG_EXYNOS_FIMC_IS) += setup-fimc-is-module.o

obj-$(CONFIG_EXYNOS_FIMC_IS) += fimc-is-v5_2_0/
obj-$(CONFIG_EXYNOS_FIMC_IS) += fimc-is-v4_3_0/
obj-$(CONFIG_EXYNOS_FIMC_IS) += fimc-is-v4_0_0/
obj-$(CONFIG_EXYNOS_FIMC_IS) += fimc-is-v3_1_1/
obj-$(CONFIG_EXYNOS_FIMC_IS) += fimc-is-v3_11_0/
obj-$(CONFIG_EXYNOS_FIMC_IS) += fimc-is-v3_20_0/
obj-$(CONFIG_EXYNOS_FIMC_IS) += fimc-is-v5_10_0/
obj-$(CONFIG_EXYNOS_FIMC_IS) += fimc-is-v5_15_0/
obj-$(CONFIG_EXYNOS_FIMC_IS) += fimc-is-v6_0_0/
obj-$(CONFIG_EXYNOS_FIMC_IS) += fimc-is-v6_10_0/
obj-$(CONFIG_EXYNOS_FIMC_IS) += fimc-is-v7_0_0/

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/include
