obj-$(CONFIG_CAMERA_OIS_SELECT) += fimc-is-helper-ois-i2c.o \
				fimc-is-ois.o

obj-$(CONFIG_CAMERA_OIS_IDG2030_OBJ) += fimc-is-ois-idg2030.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/sensor/module_framework
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/sensor
