obj-$(CONFIG_REISER4_FS) += plugins.o

plugins-objs :=			\
	plugin.o		\
	plugin_set.o		\
	object.o		\
	inode_ops.o		\
	inode_ops_rename.o	\
	file_ops.o		\
	file_ops_readdir.o	\
	file_plugin_common.o	\
	dir_plugin_common.o	\
	digest.o		\
	hash.o			\
	fibration.o		\
	tail_policy.o		\
	regular.o

obj-$(CONFIG_REISER4_FS) += item/
obj-$(CONFIG_REISER4_FS) += file/
obj-$(CONFIG_REISER4_FS) += dir/
obj-$(CONFIG_REISER4_FS) += node/
obj-$(CONFIG_REISER4_FS) += compress/
obj-$(CONFIG_REISER4_FS) += space/
obj-$(CONFIG_REISER4_FS) += disk_format/
obj-$(CONFIG_REISER4_FS) += security/
