#
# Copyright (c) 2018 Samsung Electronics Co., Ltd.
#		http://www.samsung.com
#
# Licensed under GPLv2
#

obj-$(CONFIG_CAMERA_PP_STR_V1_0_0_OBJ)	+= camerapp-str-sfr-api-v100.o

ccflags-y += -Idrivers/media/platform/exynos/camera-pp
