#
# Makefile for the vibrator driver ICs with vibrator driver
#

obj-$(CONFIG_ANDROID_TIMED_OUTPUT)	+= timed_output.o
obj-$(CONFIG_MOTOR_CS40L2X)		+= cs40l2x.o cs40l2x-tables.o
obj-$(CONFIG_MOTOR_DRV_MAX77705)	+= max77705_haptic.o
obj-$(CONFIG_SEC_HAPTIC)	+= sec_haptic.o
obj-$(CONFIG_VIB_NOTIFIER)	+= vib_notifier.o