obj-y				+= npu-interface.o
obj-y				+= npu-mailbox-mgr-mock.o
obj-y				+= npu-mailbox.o

EXTRA_CFLAGS += -Idrivers/vision/include -Idrivers/vision/npu/include -Idrivers/vision/npu -Idrivers/vision/npu/interface/loopback
