obj-$(CONFIG_REISER4_FS) += item_plugins.o

item_plugins-objs :=		\
	item.o			\
	static_stat.o		\
	sde.o			\
	cde.o			\
	blackbox.o		\
	internal.o		\
	tail.o			\
	ctail.o			\
	extent.o		\
	extent_item_ops.o	\
	extent_file_ops.o	\
	extent_flush_ops.o



