#
# Makefile for DEK and DLP modules
#

obj-$(CONFIG_SDP) += dek.o dek_aes.o sdp_mm.o pub_crypto_emul.o dek_sysfs.o cache_cleanup.o kek_pack.o fs_handler.o 
obj-$(CONFIG_DLP) += sdp_dlp.o
obj-$(CONFIG_DDAR) += dd_core.o dd_xattr.o dd_kernel_crypto.o
