ifeq ($(CONFIG_SAMSUNG_PRODUCT_SHIP), y)
obj-$(CONFIG_KEYBOARD_STM_FSR)   += stm_fsr_sidekey.o stm_fsr_fwu.o stm_fsr_functions.o
else
obj-$(CONFIG_KEYBOARD_STM_FSR)   += stm_fsr_sidekey.o stm_fsr_fwu.o stm_fsr_functions.o stm_fsr_vendor_functions.o
endif

