#
# (C) COPYRIGHT 2012 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained
# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA.
#
#

MALI_CUSTOMER_RELEASE = 1
DEFINES +=-DMALI_SEC_PROBE_TEST=0

# MALI_SEC_SECURE_RENDERING
ifeq ($(CONFIG_MALI_EXYNOS_SECURE_RENDERING),y)
DEFINES +=-DMALI_SEC_SECURE_RENDERING=1
else
DEFINES +=-DMALI_SEC_SECURE_RENDERING=0
endif

# EXYNOS THERMAL
THERMAL_PATH = $(srctree)/drivers/thermal/samsung/

ccflags-y += $(DEFINES) -I$(THERMAL_PATH)
subdir-ccflags-y += $(DEFINES) -I$(THERMAL_PATH)

soc_name := $(shell echo $(CONFIG_EXYNOS_SOC_NAME))

obj-y += gpu_integration_callbacks.o
obj-y += mali_kbase_platform.o
obj-y += gpu_notifier.o
obj-y += gpu_control.o
obj-y += gpu_pmqos.o
obj-y += gpu_utilization.o
obj-y += gpu_dvfs_handler.o
obj-y += gpu_dvfs_api.o
obj-y += gpu_dvfs_governor.o
obj-y += gpu_job_fence_debug.o
obj-$(CONFIG_MALI_DEBUG_SYS) += gpu_custom_interface.o
obj-$(CONFIG_CPU_THERMAL_IPA) += gpu_ipa.o
