obj-$(CONFIG_USE_DIRECT_IS_CONTROL) += fimc-is-interface-ischain.o \
		fimc-is-interface-library.o \
		fimc-is-interface-vra.o \
		fimc-is-interface-ddk.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/hardware
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/hardware/api
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/vendor
