obj-y += core.o pcf.o global_boost.o ontime.o energy.o init_util.o band.o multi_load.o load_balance.o
obj-y += service.o

obj-$(CONFIG_SCHED_TUNE) += st_addon.o
obj-$(CONFIG_FREQVAR_TUNE) += freqvar_tune.o
