obj-y += bbm.o
obj-y += dmbdrv_wrap_fc8080.o
obj-y += fc8080_bb.o
obj-y += fc8080_isr.o
obj-$(CONFIG_TDMB_SPI) += fc8080_spi.o
obj-$(CONFIG_TDMB_EBI) += fc8080_ppi.o
obj-$(CONFIG_TDMB_I2C) += fc8080_i2c.o
obj-$(CONFIG_TDMB_TSIF_QC) += fc8080_demux.o
obj-$(CONFIG_TDMB_TSIF_SLSI) += fc8080_demux.o
obj-y += fc8080_tun.o
obj-y += fci_hal.o
obj-y += fci_hpi.o
obj-y += fci_oal.o
obj-y += fci_tun.o
obj-y += fic.o
obj-y += ficdecoder.o

ccflags-y += -Idrivers/media/tdmb
