#
# Exynos CPU Performance Profiling
#

# Exynos CPU Performance
obj-$(CONFIG_EXYNOS_CPU_PERF)	+= exynos_perf_ncmemcpy.o
obj-$(CONFIG_EXYNOS_CPU_PERF)	+= exynos_perf_cpuidle.o
obj-$(CONFIG_EXYNOS_CPU_PERF)	+= exynos_perf_cpu.o
obj-$(CONFIG_EXYNOS_CPU_PERF)	+= exynos_perf_cpufreq.o
