obj-$(CONFIG_CSIS_V4_0) += fimc-is-hw-csi-v4_0.o
obj-$(CONFIG_CSIS_V4_1) += fimc-is-hw-csi-v4_0.o
obj-$(CONFIG_CSIS_V5_0) += fimc-is-hw-csi-v5_0.o
obj-$(CONFIG_CSIS_V5_1) += fimc-is-hw-csi-v5_1.o
obj-$(CONFIG_CSIS_V5_2) += fimc-is-hw-csi-v5_2.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/include
