obj-$(CONFIG_VIDEO_EXYNOS_MFC) := exynos_mfc.o
exynos_mfc-y += mfc.o mfc_isr.o mfc_dec_v4l2.o mfc_dec_vb2.o mfc_enc_v4l2.o mfc_enc_vb2.o
exynos_mfc-y += mfc_hwlock.o mfc_nal_q.o mfc_watchdog.o mfc_run.o mfc_sync.o
exynos_mfc-y += mfc_pm.o mfc_cmd.o mfc_hw_reg_api.o mfc_reg_api.o mfc_perf_measure.o
exynos_mfc-y += mfc_dec_ctrl.o mfc_enc_ctrl.o mfc_enc_param.o
exynos_mfc-y += mfc_queue.o mfc_buf.o mfc_utils.o mfc_qos.o mfc_mem.o
exynos_mfc-y += mfc_debugfs.o mfc_otf.o
exynos_mfc-y += mfc_mmcache.o
