camerapp-objs := camerapp-sfr-api-common.o
obj-$(CONFIG_VIDEO_EXYNOS_CAMERA_POSTPROCESS)	+= camerapp.o
obj-$(CONFIG_VIDEO_EXYNOS_CAMERA_POSTPROCESS_GDC)	+= gdc/
obj-$(CONFIG_VIDEO_EXYNOS_CAMERA_POSTPROCESS_STR)	+= str/
