#
# Makefile for the optics drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSORS_HRMSENSOR)		+= hrmsensor.o
obj-$(CONFIG_SENSORS_HRM_MAX86915)	+= hrm_max86915.o
obj-$(CONFIG_SENSORS_MAX86915)		+= max86915.o
obj-$(CONFIG_SENSORS_TCS3407)		+= tcs3407.o
obj-$(CONFIG_SENSORS_VD6281)		+= vd6281.o