#
# Makefile for ccic devices
#

obj-$(CONFIG_USBPD_CORE)		+= usbpd-core.o usbpd-manager.o usbpd-dual-role.o
obj-$(CONFIG_CCIC_NOTIFIER)		+= ccic_notifier.o ccic_sysfs.o ccic_core.o ccic_misc.o
obj-$(CONFIG_CCIC_ALTERNATE_MODE)	+= ccic_alternate.o
obj-$(CONFIG_CCIC_S2MM003)		+= s2mm003.o
obj-$(CONFIG_CCIC_S2MM005)		+= s2mm005_fw.o s2mm005_cc.o s2mm005_pd.o sec_pd.o s2mm005.o
obj-$(CONFIG_CCIC_MAX77705)		+= max77705_cc.o max77705_pd.o sec_pd.o max77705_usbc.o max77705_alternate.o
obj-$(CONFIG_CCIC_MAX77705_DEBUG)	+= max77705_debug.o
obj-$(CONFIG_USBPD_S2MM005)		+= s2mm005_usbpd_fw.o s2mm005_usbpd_phy.o s2mm005_usbpd.o s2mm005_usbpd_i2c.o s2mm005_usbpd_interface.o usbpd_sysfs.o
