obj-$(CONFIG_VISION_CORE)	+= vision-dev.o
obj-$(CONFIG_VISION_CORE)	+= vision-compat-ioctl32.o
obj-$(CONFIG_VISION_CORE)	+= vision-ioctl.o
obj-$(CONFIG_VISION_CORE)	+= vision-buffer.o

EXTRA_CFLAGS += -Idrivers/vision/include -Idrivers/vision/npu/include
