/*
 * Copyright (C) 2016 Samsung Electronics Co.Ltd
 *
 * This program is free software; you can redistribute	it and/or modify it
 * under  the terms of	the GNU General  Public License as published by the
 * Free Software Foundation;  either version 2 of the  License, or (at your
 * option) any later version.
 */
#ifndef _VDE_REGS_H_
#define _VDE_REGS_H_

/* base addresses of vde register sections */
#define VDE_GBL_BASE_ADDR	(0x00000)
#define VDE_CH_BASE_DIST	(0x00200)
#define VDE_CH_BASE_ADDR(ch)	(ch * VDE_CH_BASE_DIST + 0x200)
#define VDE_CH0_BASE_ADDR	(VDE_CH_BASE_ADDR(0))
#define VDE_CH1_BASE_ADDR	(VDE_CH_BASE_ADDR(1))
#define VDE_CH2_BASE_ADDR	(VDE_CH_BASE_ADDR(2))
#define VDE_CH3_BASE_ADDR	(VDE_CH_BASE_ADDR(3))
#define VDE_DBG_BASE_ADDR	(0x0FF00)

/* addresses for global registers */
#define VDE_STATUS_REG_AXI_ADDR		(0x00004)
#define VDE_IRQ_EN_ADDR			(0x00010)
#define VDE_IRQ_RAW_STATUS_ADDR		(0x00014)
#define VDE_IRQ_SOFT_ADDR		(0x00018)
#define VDE_IRQ_STATUS_ADDR		(0x0001C)
#define VDE_AXI_QOS_ADDR		(0x00040)

/*
 * make common macros for applying all channels.
 *	describes those as offset from channel base address.
 */
#define VDE_CH_START_REG_ADDR		(0x00000)
#define VDE_CH_STATUS_REG_0_ADDR	(0x00004)
#define VDE_CH_STATUS_REG_BCI_ADDR	(0x00008)
/* nr : 0 ~ 8 */
#define VDE_CH_CFG_REG_ADDR(nr)		(0x00010 + nr * 0x4)
#define VDE_CH_CFG_REG_0_ADDR		(0x00010)
#define VDE_CH_CFG_REG_1_ADDR		(0x00014)
#define VDE_CH_CFG_REG_2_ADDR		(0x00018)
#define VDE_CH_CFG_REG_3_ADDR		(0x0001C)
#define VDE_CH_CFG_REG_4_ADDR		(0x00020)
#define VDE_CH_CFG_REG_5_ADDR		(0x00024)
#define VDE_CH_CFG_REG_6_ADDR		(0x00028)
#define VDE_CH_CFG_REG_7_ADDR		(0x0002C)
#define VDE_CH_CFG_REG_8_ADDR		(0x00030)

#define VDE_CH_CFG_REG_BCI_ADDR		(0x00034)
#define VDE_CH_CFG_REG_YUV_ADDR		(0x00038)

/* nr : 0 ~ 5 */
#define VDE_CH_CBWCFG_BASE		(0x00040)
#define VDE_CH_CBWCFG_ADDR(nr)		(VDE_CH_CBWCFG_BASE + nr * 0x4)
/* NOTICE: common for CH_CBWCFG and CH_P_CBWCFG registers*/
#define VDE_CH_CBWCFG0_ADDR_OFFSET	(0x0)
#define VDE_CH_CBWCFG1_ADDR_OFFSET	(0x4)
#define VDE_CH_CBWCFG2_ADDR_OFFSET	(0x8)
#define VDE_CH_CBWCFG3_ADDR_OFFSET	(0xC)
#define VDE_CH_CBWCFG4_ADDR_OFFSET	(0x10)
#define VDE_CH_CBWCFG5_ADDR_OFFSET	(0x14)

/* nr : 0 ~ 5 */
#define VDE_CH_CBRCFG_BASE		(0x00060)
#define VDE_CH_CBRCFG_ADDR(nr)		(VDE_CH_CBRCFG_BASE + nr * 0x4)
/* NOTICE: common for CH_CBRCFG and CH_P_CBRCFG registers*/
#define VDE_CH_CBRCFG0_ADDR_OFFSET	(0x0)
#define VDE_CH_CBRCFG1_ADDR_OFFSET	(0x4)
#define VDE_CH_CBRCFG2_ADDR_OFFSET	(0x8)
#define VDE_CH_CBRCFG3_ADDR_OFFSET	(0xC)
#define VDE_CH_CBRCFG4_ADDR_OFFSET	(0x10)
#define VDE_CH_CBRCFG5_ADDR_OFFSET	(0x14)

/* bci control */
#define VDE_CH_BCI_BUF_SRC_SIZE_ADDR		(0x00080)
#define VDE_CH_BCI_BUF_SRC_START_OFFSET_ADDR	(0x00084)
#define VDE_CH_BCI_BUF_SRC_OFFSET_ADDR		(0x00088)
#define VDE_CH_BCI_BUF_DST_SIZE_ADDR		(0x0008C)
#define VDE_CH_BCI_BUF_DST_START_OFFSET_ADDR	(0x00090)
#define VDE_CH_BCI_BUF_DST_OFFSET_ADDR		(0x00094)

/* p(plane) : 0 ~ 2, nr : 0 ~ 5 */
#define VDE_PLANAR_OFFSET		(0x50)
#define VDE_CH_P_BUF_SRC_ADDR_ADDR(p)	(0x00100 + p * VDE_PLANAR_OFFSET)
#define VDE_CH_P_BUF_SRC_SIZE_ADDR(p)	(0x00104 + p * VDE_PLANAR_OFFSET)
#define VDE_CH_P_BUF_SRC_STRIDE_ADDR(p)	(0x00108 + p * VDE_PLANAR_OFFSET)
#define VDE_CH_P_BUF_DST_ADDR_ADDR(p)	(0x0010C + p * VDE_PLANAR_OFFSET)
#define VDE_CH_P_BUF_DST_SIZE_ADDR(p)	(0x00110 + p * VDE_PLANAR_OFFSET)
#define VDE_CH_P_BUF_DST_STRIDE_ADDR(p)	(0x00114 + p * VDE_PLANAR_OFFSET)

#define VDE_CH_P_CBWCFG_ADDR(p, nr)	(0x00118 + p * VDE_PLANAR_OFFSET + nr * 0x4)
#define VDE_CH_P_CBRCFG_ADDR(p, nr)	(0x00134 + p * VDE_PLANAR_OFFSET + nr * 0x4)

/* bit masks and shifts */
#define VDE_CH_START_REG_TR_START_S	(0)
#define VDE_CH_START_REG_TR_START_M	(0x1)

#define VDE_CH_STATUS_CH_WSTATE_S	(8)
#define VDE_CH_STATUS_CH_WSTATE_M	(0x1F)
#define VDE_CH_STATUS_CH_RSTATE_S	(4)
#define VDE_CH_STATUS_CH_RSTATE_M	(0xF)
#define VDE_CH_STATUS_CH_READY_S	(1)
#define VDE_CH_STATUS_CH_READY_M	(0x1)
#define VDE_CH_STATUS_0_CH_BUSY_S	(0)
#define VDE_CH_STATUS_0_CH_BUSY_M	(0x1)

#define VDE_CH_CFG_REG_4_5_LOCAL_ADDR_M		(0x7FFFF)
#define VDE_CH_CFG_REG_4_LOCAL_SRC_ADDR_S	(0)
#define VDE_CH_CFG_REG_4_LOCAL_SRC_ADDR_M	(VDE_CH_CFG_REG_4_5_LOCAL_ADDR_M)
#define VDE_CH_CFG_REG_5_LOCAL_DST_ADDR_S	(0)
#define VDE_CH_CFG_REG_5_LOCAL_DST_ADDR_M	(VDE_CH_CFG_REG_4_5_LOCAL_ADDR_M)

#define VDE_CH_CFG_REG_6_IMG_HEIGHT_S		(16)
#define VDE_CH_CFG_REG_6_IMG_HEIGHT_M		(0x1FFF)
#define VDE_CH_CFG_REG_6_IMG_WIDTH_S		(0)
#define VDE_CH_CFG_REG_6_IMG_WIDTH_M		(0x1FFF)

#define VDE_CH_CFG_REG_7_DST_STRIDE_S		(16)
#define VDE_CH_CFG_REG_7_DST_STRIDE_M		(0x1FFF)
#define VDE_CH_CFG_REG_7_SRC_STRIDE_S		(0)
#define VDE_CH_CFG_REG_7_SRC_STRIDE_M		(0x1FFF)

#define VDE_CH_CFG_REG_8_ADDR_MODE_S		(30)
#define VDE_CH_CFG_REG_8_ADDR_MODE_M		(0x3)
#define VDE_CH_CFG_REG_8_TTYPE_S		(28)
#define VDE_CH_CFG_REG_8_TTYPE_M		(0x3)
#define VDE_CH_CFG_REG_8_BPP_S			(24)
#define VDE_CH_CFG_REG_8_BPP_M			(0x7)
#define VDE_CH_CFG_REG_8_TSIZE_S		(0)
#define VDE_CH_CFG_REG_8_TSIZE_M		(0x7FFFF)

#define VDE_CH_CFG_REG_BCI_BCI_BUF_DST_YNUM_S	(16)
#define VDE_CH_CFG_REG_BCI_BCI_BUF_DST_YNUM_M	(0xF)
#define VDE_CH_CFG_REG_BCI_BCI_BUF_DST_XNUM_S	(12)
#define VDE_CH_CFG_REG_BCI_BCI_BUF_DST_XNUM_M	(0xF)
#define VDE_CH_CFG_REG_BCI_BCI_BUF_SRC_YNUM_S	(8)
#define VDE_CH_CFG_REG_BCI_BCI_BUF_SRC_YNUM_M	(0xF)
#define VDE_CH_CFG_REG_BCI_BCI_BUF_SRC_XNUM_S	(4)
#define VDE_CH_CFG_REG_BCI_BCI_BUF_SRC_XNUM_M	(0xF)
#define VDE_CH_CFG_REG_BCI_BCI_DST_MODE_EN_S	(1)
#define VDE_CH_CFG_REG_BCI_BCI_DST_MODE_EN_M	(0x1)
#define VDE_CH_CFG_REG_BCI_BCI_DST_MODE_EN	\
			(VDE_CH_CFG_REG_BCI_BCI_DST_MODE_EN_M <<\
				VDE_CH_CFG_REG_BCI_BCI_DST_MODE_EN_S)
#define VDE_CH_CFG_REG_BCI_BCI_SRC_MODE_EN_S	(0)
#define VDE_CH_CFG_REG_BCI_BCI_SRC_MODE_EN_M	(0x1)
#define VDE_CH_CFG_REG_BCI_BCI_SRC_MODE_EN	\
			(VDE_CH_CFG_REG_BCI_BCI_SRC_MODE_EN_M <<\
				VDE_CH_CFG_REG_BCI_BCI_SRC_MODE_EN_S)

#define VDE_CH_CFG_REG_YUV_DST_YUV_MODE_S	(12)
#define VDE_CH_CFG_REG_YUV_DST_YUV_MODE_M	(0x7)
#define VDE_CH_CFG_REG_YUV_DST_PLANAR_MODE_S	(8)
#define VDE_CH_CFG_REG_YUV_DST_PLANAR_MODE_M	(0x3)
#define VDE_CH_CFG_REG_YUV_SRC_YUV_MODE_S	(4)
#define VDE_CH_CFG_REG_YUV_SRC_YUV_MODE_M	(0x7)
#define VDE_CH_CFG_REG_YUV_SRC_PLANAR_MODE_S	(0)
#define VDE_CH_CFG_REG_YUV_SRC_PLANAR_MODE_M	(0x3)

/* NOTICE: common for CH_CBWCFG and CH_P_CBWCFG registers*/
#define VDE_CH_CBWCFG0_WR_BCAST_START_OF_ROW_S	(2)
#define VDE_CH_CBWCFG0_WR_BCAST_START_OF_ROW_M	(0x1)
#define VDE_CH_CBWCFG0_WR_FLOWCTRL_EN_S		(1)
#define VDE_CH_CBWCFG0_WR_FLOWCTRL_EN_M		(0x1)
#define VDE_CH_CBWCFG0_WR_BCAST_EN_S		(0)
#define VDE_CH_CBWCFG0_WR_BCAST_EN_M		(0x1)

#define VDE_CH_CBWCFG1_WR_BCAST_PERIOD_S	(16)
#define VDE_CH_CBWCFG1_WR_BCAST_PERIOD_M	(0xFFFF)
#define VDE_CH_CBWCFG1_WR_BCAST_UNIT_S		(4)
#define VDE_CH_CBWCFG1_WR_BCAST_UNIT_M		(0xFFF)

#define VDE_CH0_CBWCFG2_WCBUF_PTR_S		(4)
#define VDE_CH0_CBWCFG2_WCBUF_PTR_M		(0x7FFF)
#define VDE_CH0_CBWCFG3_WCBUF_SIZE_S		(4)
#define VDE_CH0_CBWCFG3_WCBUF_SIZE_M		(0x7FFF)

#define VDE_CH_CBWCFG4_RID_EN_S		(8)
#define VDE_CH_CBWCFG4_RID_EN_M		(0x3)
#define VDE_CH_CBWCFG4_BCAST_WID_S	(0)
#define VDE_CH_CBWCFG4_BCAST_WID_M	(0xFF)

#define VDE_CH_CBWCFG5_RID3_S		(24)
#define VDE_CH_CBWCFG5_RID2_S		(16)
#define VDE_CH_CBWCFG5_RID1_S		(8)
#define VDE_CH_CBWCFG5_RID0_S		(0)
#define VDE_CH_CBWCFG5_RID_M		(0xFF)

/* NOTICE: common for CH_CBRCFG and CH_P_CBRCFG registers*/
#define VDE_CH_CBRCFG0_RD_BCAST_START_OF_ROW_S	(2)
#define VDE_CH_CBRCFG0_RD_BCAST_START_OF_ROW_M	(0x1)
#define VDE_CH_CBRCFG0_RD_FLOWCTRL_EN_S		(1)
#define VDE_CH_CBRCFG0_RD_FLOWCTRL_EN_M		(0x1)
#define VDE_CH_CBRCFG0_RD_BCAST_EN_S		(0)
#define VDE_CH_CBRCFG0_RD_BCAST_EN_M		(0x1)

#define VDE_CH_CBRCFG1_RD_BCAST_PERIOD_S	(16)
#define VDE_CH_CBRCFG1_RD_BCAST_PERIOD_M	(0xFFFF)
#define VDE_CH_CBRCFG1_RD_BCAST_UNIT_S		(4)
#define VDE_CH_CBRCFG1_RD_BCAST_UNIT_M		(0xFFF)

#define VDE_CH_CBRCFG2_RCBUF_PTR_S	(4)
#define VDE_CH_CBRCFG2_RCBUF_PTR_M	(0x7FFF)

#define VDE_CH_CBRCFG3_RCBUF_SIZE_S	(4)
#define VDE_CH_CBRCFG3_RCBUF_SIZE_M	(0x7FFF)

#define VDE_CH_CBRCFG4_WID_S		(0)
#define VDE_CH_CBRCFG4_WID_M		(0xFF)

#define VDE_CH_CBRCFG5_BCAST_RID_S	(0)
#define VDE_CH_CBRCFG5_BCAST_RID_M	(0xFF)

#define VDE_CH_BCI_BUF_SRC_SIZE_BCI_BUF_SRC_HEIGHT_S	(16)
#define VDE_CH_BCI_BUF_SRC_SIZE_BCI_BUF_SRC_HEIGHT_M	(0x1FFF)
#define VDE_CH_BCI_BUF_SRC_SIZE_BCI_BUF_SRC_WIDTH_S	(0)
#define VDE_CH_BCI_BUF_SRC_SIZE_BCI_BUF_SRC_WIDTH_M	(0x1FFF)

#define VDE_CH_BCI_BUF_SRC_START_OFFSET_BCI_BUF_SRC_START_OFFSET_Y_S	(16)
#define VDE_CH_BCI_BUF_SRC_START_OFFSET_BCI_BUF_SRC_START_OFFSET_Y_M	(0x1FFF)
#define VDE_CH_BCI_BUF_SRC_START_OFFSET_BCI_BUF_SRC_START_OFFSET_X_S	(0)
#define VDE_CH_BCI_BUF_SRC_START_OFFSET_BCI_BUF_SRC_START_OFFSET_X_M	(0x1FFF)

#define VDE_CH_BCI_BUF_SRC_OFFSET_BCI_BUF_SRC_OFFSET_Y_S	(16)
#define VDE_CH_BCI_BUF_SRC_OFFSET_BCI_BUF_SRC_OFFSET_Y_M	(0x1FFF)
#define VDE_CH_BCI_BUF_SRC_OFFSET_BCI_BUF_SRC_OFFSET_X_S	(0)
#define VDE_CH_BCI_BUF_SRC_OFFSET_BCI_BUF_SRC_OFFSET_X_M	(0x1FFF)

#define VDE_CH_BCI_BUF_DST_SIZE_BCI_BUF_DST_HEIGHT_S	(16)
#define VDE_CH_BCI_BUF_DST_SIZE_BCI_BUF_DST_HEIGHT_M	(0x1FFF)
#define VDE_CH_BCI_BUF_DST_SIZE_BCI_BUF_DST_WIDTH_S	(0)
#define VDE_CH_BCI_BUF_DST_SIZE_BCI_BUF_DST_WIDTH_M	(0x1FFF)

#define VDE_CH_P_BUF_SRC_ADDR_P0_BUF_SRC_ADDR_S		(0)
#define VDE_CH_P_BUF_SRC_ADDR_P0_BUF_SRC_ADDR_M		(0x7FFFF)

#define VDE_CH_P_BUF_SRC_SIZE_P_BUF_SRC_HEIGHT_S	(16)
#define VDE_CH_P_BUF_SRC_SIZE_P_BUF_SRC_HEIGHT_M	(0x1FFF)
#define VDE_CH_P_BUF_SRC_SIZE_P_BUF_SRC_WIDTH_S		(0)
#define VDE_CH_P_BUF_SRC_SIZE_P_BUF_SRC_WIDTH_M		(0x1FFF)

#define VDE_CH_P_BUF_DST_SIZE_P_BUF_DST_HEIGHT_S	(16)
#define VDE_CH_P_BUF_DST_SIZE_P_BUF_DST_HEIGHT_M	(0x1FFF)
#define VDE_CH_P_BUF_DST_SIZE_P_BUF_DST_WIDTH_S		(0)
#define VDE_CH_P_BUF_DST_SIZE_P_BUF_DST_WIDTH_MASK	(0x1FFF)

#define VDE_CH_P_BUF_DST_STRIDE_P_BUF_DST_STRIDE_S	(0)
#define VDE_CH_P_BUF_DST_STRIDE_P_BUF_DST_STRIDE_M	(0x1FFF)

#define VDE_CH_P_BUF_DST_STRIDE_P_BUF_DST_STRIDE_S	(0)
#define VDE_CH_P_BUF_DST_STRIDE_P_BUF_DST_STRIDE_M	(0x1FFF)

#define VDE_CH_P_CBWCFG0_WR_BCAST_START_OF_ROW_S	(2)
#define VDE_CH_P_CBWCFG0_WR_BCAST_START_OF_ROW_M	(0x1)
#define VDE_CH_P_CBWCFG0_WR_FLOWCTRL_EN_S		(1)
#define VDE_CH_P_CBWCFG0_WR_FLOWCTRL_EN_M		(0x1)
#define VDE_CH_P_CBWCFG0_WR_BCAST_EN_S			(0)
#define VDE_CH_P_CBWCFG0_WR_BCAST_EN_M			(0x1)

#define VDE_CH_P_CBWCFG1_WR_BCAST_PERIOD_S		(16)
#define VDE_CH_P_CBWCFG1_WR_BCAST_PERIOD_M		(0xFFFF)
#define VDE_CH_P_CBWCFG1_WR_BCAST_UNIT_S		(4)
#define VDE_CH_P_CBWCFG1_WR_BCAST_UNIT_M		(0xFFF)

#define VDE_CH_P_CBWCFG2_WCBUF_PTR_S			(4)
#define VDE_CH_P_CBWCFG2_WCBUF_PTR_M			(0x7FFF)

#define VDE_CH_P_CBWCFG3_WCBUF_SIZE_S			(4)
#define VDE_CH_P_CBWCFG3_WCBUF_SIZE_M			(0x7FFF)

#define VDE_CH_P_CBWCFG4_RID_EN_S			(8)
#define VDE_CH_P_CBWCFG4_RID_EN_M			(0x3)
#define VDE_CH_P_CBWCFG4_BCAST_WID_S			(0)
#define VDE_CH_P_CBWCFG4_BCAST_WID_M			(0xFF)

#define VDE_CH_P_CBWCFG5_RID3_S				(24)
#define VDE_CH_P_CBWCFG5_RID2_S				(16)
#define VDE_CH_P_CBWCFG5_RID1_S				(8)
#define VDE_CH_P_CBWCFG5_RID0_S				(0)
#define VDE_CH_P_CBWCFG5_RID_M				(0xFF)

#define VDE_CH_P_CBRCFG0_RD_BCAST_START_OF_ROW_S	(2)
#define VDE_CH_P_CBRCFG0_RD_BCAST_START_OF_ROW_M	(0x1)
#define VDE_CH_P_CBRCFG0_RD_FLOWCTRL_EN_S		(1)
#define VDE_CH_P_CBRCFG0_RD_FLOWCTRL_EN_M		(0x1)
#define VDE_CH_P_CBRCFG0_RD_BCAST_EN_S			(0)
#define VDE_CH_P_CBRCFG0_RD_BCAST_EN_M			(0x1)

#define VDE_CH_P_CBRCFG1_RD_BCAST_PERIOD_S		(16)
#define VDE_CH_P_CBRCFG1_RD_BCAST_PERIOD_M		(0xFFFF)
#define VDE_CH_P_CBRCFG1_RD_BCAST_UNIT_S		(4)
#define VDE_CH_P_CBRCFG1_RD_BCAST_UNIT_M		(0xFFF)

#define VDE_CH_P_CBRCFG2_RCBUF_PTR_S			(4)
#define VDE_CH_P_CBRCFG2_RCBUF_PTR_M			(0x7FFF)

#define VDE_CH_P_CBRCFG3_RCBUF_SIZE_S			(4)
#define VDE_CH_P_CBRCFG3_RCBUF_SIZE_M			(0x7FFF)

#define VDE_CH_P_CBRCFG4_WID_S				(0)
#define VDE_CH_P_CBRCFG4_WID_M				(0xFF)

#define VDE_CH_P_CBRCFG5_BCAST_RID_S			(0)
#define VDE_CH_P_CBRCFG5_BCAST_RID_M			(0xFF)
#endif /* _VDE_REGS_H_ */
