#ifndef _MCU_CTRL_REGS_H_
#define _MCU_CTRL_REGS_H_

/* mcu_ctrl */
#define IVA_MCU_CTRL_BOOTHOOLD_ADDR		(0x00000)
#define IVA_MCU_CTRL_CM7_CTRL_ADDR		(0x00004)
#define IVA_MCU_CTRL_INITTCM_ADDR		(0x00008)
#define IVA_MCU_CTRL_INITVTOR_ADDR		(0x0000C)

#define IVA_MCU_CTRL_MCU_NMI_CTRL_ADDR		(0x00100)
#define IVA_MCU_CTRL_MCU_NMI_STATUS_ADDR	(0x00104)
#define IVA_MCU_CTRL_MCU_NMI_ID_ADDR		(0x00108)
#define IVA_MCU_CTRL_MCU_HARD_ABORT_ADDR	(0x0010C)
#define IVA_MCU_CTRL_EDIL_CTRL_ADDR		(0x00200)

#endif /* _MCU_CTRL_REGS_H_ */
