#define CPU_INFORM_C1			(0)
#define CPU_INFORM_C2			(1)
#define CPU_INFORM_CPD			(2)
#define CPU_INFORM_SICD			(3)
#define CPU_INFORM_SLEEP			(4)
#define CPU_INFORM_SLEEP_USBL2			(5)
#define CPU_INFORM_STOP			(6)
#define CPU_INFORM_POWERMODE_NUM			(7)
