#
# Copyright (c) 2013 Samsung Electronics Co., Ltd.
#		http://www.samsung.com
#
# Licensed under GPLv2
#

obj-$(CONFIG_SEC_DISPLAYPORT_LOGGER) += dp_logger.o
obj-$(CONFIG_SEC_DISPLAYPORT_BIGDATA) += displayport_bigdata.o
