#
# Makefile for BTS.
#

obj-$(CONFIG_EXYNOS8890_BTS)    += cal_bts8890.o bts-exynos8890.o
obj-$(CONFIG_EXYNOS8895_BTS)    += cal_bts8895.o bts-exynos8895.o
obj-$(CONFIG_EXYNOS9810_BTS)    += cal_bts9810.o bts-exynos9810.o
obj-$(CONFIG_EXYNOS9820_BTS)    += cal_bts9820.o bts-exynos9820.o
