# SPDX-License-Identifier: GPL-2.0

ifdef CONFIG_MODEL_G970F
include arch/arm64/boot/dts/G970F.mk
endif

ifdef CONFIG_MODEL_G970N
include arch/arm64/boot/dts/G970N.mk
endif

ifdef CONFIG_MODEL_G973F
include arch/arm64/boot/dts/G973F.mk
endif

ifdef CONFIG_MODEL_G975F
include arch/arm64/boot/dts/G975F.mk
endif

ifdef CONFIG_MODEL_G977B
include arch/arm64/boot/dts/G977B.mk
endif

ifdef CONFIG_MODEL_N970F
include arch/arm64/boot/dts/N970F.mk
endif

ifdef CONFIG_MODEL_N971N
include arch/arm64/boot/dts/N971N.mk
endif

ifdef CONFIG_MODEL_N975F
include arch/arm64/boot/dts/N975F.mk
endif

ifdef CONFIG_MODEL_N976B
include arch/arm64/boot/dts/N976B.mk
endif

ifdef CONFIG_MODEL_N976N
include arch/arm64/boot/dts/N976N.mk
endif
