obj-$(CONFIG_USE_DIRECT_IS_CONTROL) += fimc-is-hw-api-common.o \
		fimc-is-hw-api-vra.o

obj-$(CONFIG_CAMERA_FIMC_SCALER_USE) += fimc-is-hw-api-scp.o
obj-$(CONFIG_MC_SCALER_V1_20) += fimc-is-hw-api-mcscaler-v120.o
obj-$(CONFIG_MC_SCALER_V1_22_V1_23) += fimc-is-hw-api-mcscaler-v122_123.o
obj-$(CONFIG_MC_SCALER_V2_10) += fimc-is-hw-api-mcscaler-v210.o
obj-$(CONFIG_MC_SCALER_V2_0) += fimc-is-hw-api-mcscaler-v2_0.o
obj-$(CONFIG_MC_SCALER_V3_0) += fimc-is-hw-api-mcscaler-v3_0.o
obj-$(CONFIG_MC_SCALER_V3_20) += fimc-is-hw-api-mcscaler-v320.o
obj-$(CONFIG_MC_SCALER_V4_0) += fimc-is-hw-api-mcscaler-v4_0.o
obj-$(CONFIG_MC_SCALER_V4_10) += fimc-is-hw-api-mcscaler-v410.o
obj-$(CONFIG_MC_SCALER_V5_0) += fimc-is-hw-api-mcscaler-v5_0.o

obj-$(CONFIG_USE_HW_API_COMMON) += fimc-is-hw-api-common.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/hardware
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/hardware/api
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/vendor
