/*
 * Samsung Exynos SoC series FIMC-IS2 driver
 *
 * Copyright (c) 2017 Samsung Electronics Co., Ltd
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef FIMC_IS_HW_PAFSTAT_V1_0_H
#define FIMC_IS_HW_PAFSTAT_V1_0_H

#include "fimc-is-hw-api-common.h"

#define PAFSTAT_FLOATING_MAXWIDTH	9
#define PAFSTAT_FLOATING_MAXHEIGHT	1
#define PAFSTAT_FLOATING_ELEMENT_SIZE	448

#define PAFSTAT_STATIC_MAXWIDTH		19
#define PAFSTAT_STATIC_MAXHEIGHT	15
#define PAFSTAT_STATIC_ELEMENT_SIZE	448

enum pafstat_rdma_format {
	/*
	 * RDAM data format.
	 * 0 : 8bit
	 * 1 : 10bit
	 * 2 : 12bit {00, 10bit}
	 * 3 : 12bit {10bit, 00}
	 * 4 : 16bit {000000, 10bit}
	 * 5 : Android10
	 */
	PAFSTAT_RDMA_FORMAT_8BIT_PACK = 0,
	PAFSTAT_RDMA_FORMAT_10BIT_PACK,
	PAFSTAT_RDMA_FORMAT_12BIT_PACK_LSB_ALIGN,
	PAFSTAT_RDMA_FORMAT_12BIT_PACK_MSB_ALIGN,
	PAFSTAT_RDMA_FORMAT_16BIT_PACK_LSB_ALIGN,
	PAFSTAT_RDMA_FORMAT_ANDROID10,
};

/* the total count of PAFSTAT v1.0's regs */
enum fimc_is_hw_pafstat_reg_name {
	/* common between context0 and context1 */
	PAFSTAT_R_COM_QACTIVE_SET,
	PAFSTAT_R_COM_RESET_REQ,
	PAFSTAT_R_COM_RESET_REQ_BUSY,
	PAFSTAT_R_COM_DMA_FLUSH_REQ,
	PAFSTAT_R_COM_DMA_FLUSH_REQ_BUSY,
	PAFSTAT_R_COM_3AA_STALL_ENABLE,
	PAFSTAT_R_COM_LIC_MODE,
	PAFSTAT_R_COM_LIC_BYPASS,
	PAFSTAT_R_COM_LIC_SEL_SINGLE_INPUT,
	PAFSTAT_R_COM_SUB_STALL,
	PAFSTAT_R_COM_SUB_BUSY,
	PAFSTAT_R_COM_SUB_DVALID,
	PAFSTAT_R_COM_HBLANK_CYCLE,
	PAFSTAT_R_COM_DISABLE_OUTPUTMASK,
	PAFSTAT_R_COM_FRAME_NUM,
	PAFSTAT_R_COM_FRAME_NUM_STAT,	/* common between setA, setB */
	PAFSTAT_R_COM_FRAME_NUM_MED_INT,/* common between setA, setB */
	PAFSTAT_R_COM_FRAME_CNT,	/* common between setA, setB */
	PAFSTAT_R_COM_FRAME_STATUS,
	PAFSTAT_R_COM_VERSION,
	/* common between setA, setB */
	PAFSTAT_R_CTX_GLOBAL_ENABLE,
	PAFSTAT_R_CTX_ONESHOT,
	PAFSTAT_R_CTX_SEL_OTF,
	PAFSTAT_R_CTX_INTERRUPT_SRC,
	PAFSTAT_R_CTX_INTERRUPT_MASK,
	PAFSTAT_R_CTX_TIMEOUT_CNT_INIT,
	PAFSTAT_R_CTX_TIMEOUT_CNT_MAX,
	PAFSTAT_R_CTX_SENSOR_MODE,
	PAFSTAT_R_CTX_CURRENT_USE_A,
	PAFSTAT_R_CTX_LINE_NUM_MED_INT,
	PAFSTAT_R_CTX_INPUT_WIDTH,
	PAFSTAT_R_CTX_INPUT_HEIGHT,
	PAFSTAT_R_CTX_PD_PXL_WIDTH,
	PAFSTAT_R_CTX_PD_PXL_HEIGHT,
	PAFSTAT_R_CTX_CLK_CTRL,
	PAFSTAT_R_CTX_LIC_IS_DMA,
	PAFSTAT_R_CTX_SFR_READY,
	PAFSTAT_R_CTX_LIC_4PPC,
	PAFSTAT_R_PAFSTAT_YEXTR_HDRMODE,
	PAFSTAT_R_PAFSTAT_YEXTR_MAXNOSKIPPXG,
	PAFSTAT_R_PAFSTAT_YEXTR_SKIPLEVELTH,
	PAFSTAT_R_PAFSTAT_YEXTR_SATVALUEG,
	PAFSTAT_R_PAFSTAT_YEXTR_SATVALUER,
	PAFSTAT_R_PAFSTAT_YEXTR_SATVALUEB,
	PAFSTAT_R_PAFSTAT_YEXTR_NUMOFSATG,
	PAFSTAT_R_PAFSTAT_YEXTR_NUMOFSATR,
	PAFSTAT_R_PAFSTAT_YEXTR_NUMOFSATB,
	PAFSTAT_R_PAFSTAT_YEXTR_SATVALSUMOFG,
	PAFSTAT_R_PAFSTAT_YEXTR_SATVALSUMOFR,
	PAFSTAT_R_PAFSTAT_YEXTR_SATVALSUMOFB,
	PAFSTAT_R_PAFSTAT_YEXTR_CLIPVALLEFT,
	PAFSTAT_R_PAFSTAT_YEXTR_CLIPVALRIGHT,
	PAFSTAT_R_PAFSTAT_YEXTR_COEFG,
	PAFSTAT_R_PAFSTAT_YEXTR_COEFR,
	PAFSTAT_R_PAFSTAT_YEXTR_COEFB,
	PAFSTAT_R_PAFSTAT_YEXTR_YSHIFT,
	PAFSTAT_R_PAFSTAT_YEXTR_COEFG_SHORT,
	PAFSTAT_R_PAFSTAT_YEXTR_COEFR_SHORT,
	PAFSTAT_R_PAFSTAT_YEXTR_COEFB_SHORT,
	PAFSTAT_R_PAFSTAT_YEXTR_CRC,
	PAFSTAT_R_PAFSTAT_BIN_BYPASS,
	PAFSTAT_R_PAFSTAT_BIN_CONFIG,
	PAFSTAT_R_PAFSTAT_BIN_IMAGE_SIZE,
	PAFSTAT_R_PAFSTAT_BIN_COEF_0,
	PAFSTAT_R_PAFSTAT_BIN_COEF_1,
	PAFSTAT_R_PAFSTAT_BIN_CRC_SEED,
	PAFSTAT_R_PAFSTAT_BIN_CRC_RESULT,
	PAFSTAT_R_PAFSTAT_REORDER_BYPASS,
	PAFSTAT_R_PAFSTAT_REORDER_ACTIVE_STA_X,
	PAFSTAT_R_PAFSTAT_REORDER_ACTIVE_STA_Y,
	PAFSTAT_R_PAFSTAT_REORDER_ACTIVE_SIZE_X,
	PAFSTAT_R_PAFSTAT_REORDER_ACTIVE_SIZE_Y,
	PAFSTAT_R_PAFSTAT_REORDER_UNIT_SIZE_X,
	PAFSTAT_R_PAFSTAT_REORDER_UNIT_SIZE_Y,
	PAFSTAT_R_PAFSTAT_REORDER_NUM_OF_UNIT_X,
	PAFSTAT_R_PAFSTAT_REORDER_NUM_OF_UNIT_Y,
	PAFSTAT_R_PAFSTAT_REORDER_LR_INDC_FLAG_MODE,
	PAFSTAT_R_PAFSTAT_REORDER_LR_POS_ENABLE,
	PAFSTAT_R_PAFSTAT_REORDER_LR_NUM_OF_UNIT_X_IN_BLK,
	PAFSTAT_R_PAFSTAT_REORDER_LR_NUM_OF_UNIT_Y_IN_BLK,
	PAFSTAT_R_PAFSTAT_REORDER_LR_POS_TABLE_0,
	PAFSTAT_R_PAFSTAT_REORDER_LR_POS_TABLE_1,
	PAFSTAT_R_PAFSTAT_REORDER_LR_POS_TABLE_2,
	PAFSTAT_R_PAFSTAT_REORDER_LR_POS_TABLE_3,
	PAFSTAT_R_PAFSTAT_REORDER_LR_POS_TABLE_4,
	PAFSTAT_R_PAFSTAT_REORDER_LR_POS_TABLE_5,
	PAFSTAT_R_PAFSTAT_REORDER_LR_POS_TABLE_6,
	PAFSTAT_R_PAFSTAT_REORDER_LR_POS_TABLE_7,
	PAFSTAT_R_PAFSTAT_REORDER_LR_POS_TABLE_8,
	PAFSTAT_R_PAFSTAT_REORDER_LR_POS_TABLE_9,
	PAFSTAT_R_PAFSTAT_REORDER_LR_POS_TABLE_10,
	PAFSTAT_R_PAFSTAT_REORDER_LR_POS_TABLE_11,
	PAFSTAT_R_PAFSTAT_REORDER_LR_POS_TABLE_12,
	PAFSTAT_R_PAFSTAT_REORDER_LR_POS_TABLE_13,
	PAFSTAT_R_PAFSTAT_REORDER_LR_POS_TABLE_14,
	PAFSTAT_R_PAFSTAT_REORDER_LR_POS_TABLE_15,
	PAFSTAT_R_PAFSTAT_REORDER_LR_NUM_OF_BLK_IN_LINE,
	PAFSTAT_R_PAFSTAT_REORDER_LR_NUM_OF_PXL_IN_LINE,
	PAFSTAT_R_PAFSTAT_REORDER_CRC_SEED,
	PAFSTAT_R_PAFSTAT_REORDER_CRC_RESULT,
	PAFSTAT_R_PAFSTAT_LSC_BYPASS,
	PAFSTAT_R_PAFSTAT_LSC_HDR_MODE,
	PAFSTAT_R_PAFSTAT_LSC_MIRROR_MODE,
	PAFSTAT_R_PAFSTAT_LSC_PEDESTAL_EN,
	PAFSTAT_R_PAFSTAT_LSC_PEDESTAL_CUT,
	PAFSTAT_R_PAFSTAT_LSC_PEDESTAL_IN,
	PAFSTAT_R_PAFSTAT_LSC_PEDESTAL_OUT,
	PAFSTAT_R_PAFSTAT_LSC_START_X,
	PAFSTAT_R_PAFSTAT_LSC_START_Y,
	PAFSTAT_R_PAFSTAT_LSC_STEP_X,
	PAFSTAT_R_PAFSTAT_LSC_STEP_Y,
	PAFSTAT_R_PAFSTAT_LSC_GAIN_WEIGHT_INF,
	PAFSTAT_R_PAFSTAT_LSC_GAIN_WEIGHT_MAC,
	PAFSTAT_R_PAFSTAT_LSC_GAIN_SHIFT,
	PAFSTAT_R_PAFSTAT_LSC_GAIN_ADDR_0,
	PAFSTAT_R_PAFSTAT_LSC_GAIN_DATA_0,
	PAFSTAT_R_PAFSTAT_LSC_GAIN_ADDR_1,
	PAFSTAT_R_PAFSTAT_LSC_GAIN_DATA_1,
	PAFSTAT_R_PAFSTAT_LSC_CRC_SEED,
	PAFSTAT_R_PAFSTAT_LSC_CRC_RESULT,
	PAFSTAT_R_PAFSTAT_BPC_BYPASS,
	PAFSTAT_R_PAFSTAT_BPC_POS_NUM,
	PAFSTAT_R_PAFSTAT_BPC_STATIC_POS_ADDR,
	PAFSTAT_R_PAFSTAT_BPC_STATIC_POS_DATA,
	PAFSTAT_R_PAFSTAT_BPC_CRC_SEED,
	PAFSTAT_R_PAFSTAT_BPC_CRC_RESULT,
	PAFSTAT_R_PAFSTAT_GAMMA_BYPASS,
	PAFSTAT_R_PAFSTAT_GAMMA_PEDESTAL_EN,
	PAFSTAT_R_PAFSTAT_GAMMA_PEDESTAL,
	PAFSTAT_R_PAFSTAT_GAMMA_HDR_MODE,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_00,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_01,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_02,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_03,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_04,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_05,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_06,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_07,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_08,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_09,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_10,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_11,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_12,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_13,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_14,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_15,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_16,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_17,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_18,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_19,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_20,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_21,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_22,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_23,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_24,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_25,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_26,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_27,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_28,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_29,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_30,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_31,
	PAFSTAT_R_PAFSTAT_GAMMA_CRC_SEED,
	PAFSTAT_R_PAFSTAT_GAMMA_CRC_RESULT,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_00,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_01,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_02,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_03,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_04,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_05,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_06,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_07,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_08,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_09,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_10,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_11,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_12,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_13,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_14,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_15,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_16,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_17,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_18,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_19,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_20,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_21,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_22,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_23,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_24,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_25,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_26,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_27,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_28,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_29,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_30,
	PAFSTAT_R_PAFSTAT_GAMMA_LUT_SHORT_31,
	PAFSTAT_R_PAFSTAT_STAT_BYPASS,
	PAFSTAT_R_PAFSTAT_STAT_HDR_MODE,
	PAFSTAT_R_PAFSTAT_STAT_PAD_EXPAND,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_BYPASS,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_RATIO,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_0_0,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_0_1,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_0_2,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_0_3,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_0_4,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_0_5,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_0_6,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_0_7,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_1_0,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_1_1,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_1_2,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_1_3,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_1_4,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_1_5,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_1_6,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_1_7,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_2_0,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_2_1,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_2_2,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_2_3,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_2_4,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_2_5,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_2_6,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_2_7,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_3_0,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_3_1,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_3_2,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_3_3,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_3_4,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_3_5,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_3_6,
	PAFSTAT_R_PAFSTAT_STAT_UPSAMPLE_COEF_3_7,
	PAFSTAT_R_PAFSTAT_STAT_LPF_BYPASS,
	PAFSTAT_R_PAFSTAT_STAT_GRAD_BYPASS,
	PAFSTAT_R_PAFSTAT_STAT_GRAD_LEVEL,
	PAFSTAT_R_PAFSTAT_STAT_CORR_MATCH_METHOD,
	PAFSTAT_R_PAFSTAT_STAT_CORR_MAX_DISPARITY,
	PAFSTAT_R_PAFSTAT_STAT_CORR_LR_ORDER,
	PAFSTAT_R_PAFSTAT_STAT_CORR_SAT_LEVEL,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_0_ENABLE,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_1_ENABLE,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_2_ENABLE,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_3_ENABLE,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_4_ENABLE,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_5_ENABLE,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_0_POS_STA_X,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_0_POS_STA_Y,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_0_POS_END_X,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_0_POS_END_Y,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_1_POS_STA_X,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_1_POS_STA_Y,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_1_POS_END_X,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_1_POS_END_Y,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_2_POS_STA_X,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_2_POS_STA_Y,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_2_POS_END_X,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_2_POS_END_Y,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_3_POS_STA_X,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_3_POS_STA_Y,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_3_POS_END_X,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_3_POS_END_Y,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_4_POS_STA_X,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_4_POS_STA_Y,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_4_POS_END_X,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_4_POS_END_Y,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_5_POS_STA_X,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_5_POS_STA_Y,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_5_POS_END_X,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_5_POS_END_Y,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_ENABLE,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_BLK_NUM_X,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_BLK_NUM_Y,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_BLK_SIZE_X,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_BLK_SIZE_Y,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_POS_STA_X,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_POS_STA_Y,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_0_INTEGRAL_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_1_INTEGRAL_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_2_INTEGRAL_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_3_INTEGRAL_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_4_INTEGRAL_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_5_INTEGRAL_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_0_LPF_COEF0,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_0_LPF_COEF1,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_0_LPF_COEF2,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_0_LPF_COEF3,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_1_LPF_COEF0,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_1_LPF_COEF1,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_1_LPF_COEF2,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_1_LPF_COEF3,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_2_LPF_COEF0,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_2_LPF_COEF1,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_2_LPF_COEF2,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_2_LPF_COEF3,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_3_LPF_COEF0,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_3_LPF_COEF1,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_3_LPF_COEF2,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_3_LPF_COEF3,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_4_LPF_COEF0,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_4_LPF_COEF1,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_4_LPF_COEF2,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_4_LPF_COEF3,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_5_LPF_COEF0,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_5_LPF_COEF1,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_5_LPF_COEF2,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_5_LPF_COEF3,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_0_LPF_COEF_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_1_LPF_COEF_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_2_LPF_COEF_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_3_LPF_COEF_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_4_LPF_COEF_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_5_LPF_COEF_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_0_GRAD_COEF0,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_0_GRAD_COEF1,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_0_GRAD_COEF2,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_0_GRAD_COEF3,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_1_GRAD_COEF0,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_1_GRAD_COEF1,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_1_GRAD_COEF2,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_1_GRAD_COEF3,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_2_GRAD_COEF0,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_2_GRAD_COEF1,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_2_GRAD_COEF2,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_2_GRAD_COEF3,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_3_GRAD_COEF0,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_3_GRAD_COEF1,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_3_GRAD_COEF2,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_3_GRAD_COEF3,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_4_GRAD_COEF0,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_4_GRAD_COEF1,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_4_GRAD_COEF2,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_4_GRAD_COEF3,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_5_GRAD_COEF0,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_5_GRAD_COEF1,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_5_GRAD_COEF2,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_5_GRAD_COEF3,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_0_GRAD_COEF_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_1_GRAD_COEF_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_2_GRAD_COEF_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_3_GRAD_COEF_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_4_GRAD_COEF_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_5_GRAD_COEF_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_INTEGRAL_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_LPF_COEF0,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_LPF_COEF1,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_LPF_COEF2,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_LPF_COEF3,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_LPF_COEF_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_GRAD_COEF0,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_GRAD_COEF1,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_GRAD_COEF2,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_GRAD_COEF3,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_GRAD_COEF_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_0_CORR_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_1_CORR_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_2_CORR_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_3_CORR_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_4_CORR_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_5_CORR_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_CORR_SHIFT,
	PAFSTAT_R_PAFSTAT_STAT_RESULT_OUT_FW0_START_ADDR,
	PAFSTAT_R_PAFSTAT_STAT_RESULT_OUT_FW0_ACCESS,
	PAFSTAT_R_PAFSTAT_STAT_RESULT_OUT_FW1_START_ADDR,
	PAFSTAT_R_PAFSTAT_STAT_RESULT_OUT_FW1_ACCESS,
	PAFSTAT_R_PAFSTAT_STAT_RESULT_OUT_FW2_START_ADDR,
	PAFSTAT_R_PAFSTAT_STAT_RESULT_OUT_FW2_ACCESS,
	PAFSTAT_R_PAFSTAT_STAT_RESULT_OUT_FW3_START_ADDR,
	PAFSTAT_R_PAFSTAT_STAT_RESULT_OUT_FW3_ACCESS,
	PAFSTAT_R_PAFSTAT_STAT_RESULT_OUT_FW4_START_ADDR,
	PAFSTAT_R_PAFSTAT_STAT_RESULT_OUT_FW4_ACCESS,
	PAFSTAT_R_PAFSTAT_STAT_RESULT_OUT_FW5_START_ADDR,
	PAFSTAT_R_PAFSTAT_STAT_RESULT_OUT_FW5_ACCESS,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_INTEGRAL_CRC_SEED,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_INTEGRAL_CRC_RESULT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_UPSAMPLE_CRC_SEED,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_UPSAMPLE_CRC_RESULT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_LPF_CRC_SEED,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_LPF_CRC_RESULT,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_GRAD_CRC_SEED,
	PAFSTAT_R_PAFSTAT_STAT_FWIN_GRAD_CRC_RESULT,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_INTEGRAL_CRC_SEED,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_INTEGRAL_CRC_RESULT,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_UPSAMPLE_CRC_SEED,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_UPSAMPLE_CRC_RESULT,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_LPF_CRC_SEED,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_LPF_CRC_RESULT,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_GRAD_CRC_SEED,
	PAFSTAT_R_PAFSTAT_STAT_SWIN_GRAD_CRC_RESULT,
	PAFSTAT_R_PAFSTAT_AFIDENT_BYPASS,
	PAFSTAT_R_PAFSTAT_AFIDENT_START_ACTIVE_X,
	PAFSTAT_R_PAFSTAT_AFIDENT_START_ACTIVE_Y,
	PAFSTAT_R_PAFSTAT_AFIDENT_ACTIVE_WIDTH,
	PAFSTAT_R_PAFSTAT_AFIDENT_ACTIVE_HEIGHT,
	PAFSTAT_R_PAFSTAT_AFIDENT_UNIT_OFFSET_X,
	PAFSTAT_R_PAFSTAT_AFIDENT_UNIT_OFFSET_Y,
	PAFSTAT_R_PAFSTAT_AFIDENT_RELATIVE_OFFSET_X,
	PAFSTAT_R_PAFSTAT_AFIDENT_RELATIVE_OFFSET_Y,
	PAFSTAT_R_PAFSTAT_AFIDENT_OUTPUT_TYPE0,
	PAFSTAT_R_PAFSTAT_AFIDENT_BLOCKS_PER_ACTIVE_X,
	PAFSTAT_R_PAFSTAT_AFIDENT_BLOCKS_PER_ACTIVE_Y,
	PAFSTAT_R_PAFSTAT_AFIDENT_DATA_IN_TAIL,
	PAFSTAT_R_PAFSTAT_AFIDENT_TAIL_START,
	PAFSTAT_R_PAFSTAT_AFIDENT_TAIL_SPLIT,
	PAFSTAT_R_PAFSTAT_AFIDENT_BLOCKS_FIRST_SPLIT_TAIL,
	PAFSTAT_R_PAFSTAT_AFIDENT_BLOCKS_SECOND_SPLIT_TAIL,
	PAFSTAT_R_PAFSTAT_AFIDENT_UNIT_SIZE_X,
	PAFSTAT_R_PAFSTAT_AFIDENT_UNIT_SIZE_Y,
	PAFSTAT_R_PAFSTAT_AFIDENT_PTRN_X_0,
	PAFSTAT_R_PAFSTAT_AFIDENT_PTRN_X_1,
	PAFSTAT_R_PAFSTAT_AFIDENT_PTRN_X_2,
	PAFSTAT_R_PAFSTAT_AFIDENT_PTRN_X_3,
	PAFSTAT_R_PAFSTAT_AFIDENT_PTRN_X_4,
	PAFSTAT_R_PAFSTAT_AFIDENT_PTRN_X_5,
	PAFSTAT_R_PAFSTAT_AFIDENT_PTRN_X_6,
	PAFSTAT_R_PAFSTAT_AFIDENT_PTRN_X_7,
	PAFSTAT_R_PAFSTAT_AFIDENT_PTRN_Y_0,
	PAFSTAT_R_PAFSTAT_AFIDENT_PTRN_Y_1,
	PAFSTAT_R_PAFSTAT_AFIDENT_PTRN_Y_2,
	PAFSTAT_R_PAFSTAT_AFIDENT_PTRN_Y_3,
	PAFSTAT_R_PAFSTAT_AFIDENT_PTRN_Y_4,
	PAFSTAT_R_PAFSTAT_AFIDENT_PTRN_Y_5,
	PAFSTAT_R_PAFSTAT_AFIDENT_PTRN_Y_6,
	PAFSTAT_R_PAFSTAT_AFIDENT_PTRN_Y_7,
	PAFSTAT_R_PAFSTAT_AFIDENT_UNITS_PER_BLOCK_X,
	PAFSTAT_R_PAFSTAT_AFIDENT_UNIS_PER_BLOCK_Y,
	PAFSTAT_R_PAFSTAT_AFIDENT_PTRN_0,
	PAFSTAT_R_PAFSTAT_AFIDENT_PTRN_1,
	PAFSTAT_R_PAFSTAT_AFIDENT_PTRN_2,
	PAFSTAT_R_PAFSTAT_AFIDENT_PTRN_3,
	PAFSTAT_R_PAFSTAT_AFIDENT_SWITCHED_PTRN,
	PAFSTAT_R_PAFSTAT_AFIDENT_RATE_CNTRL_EN,
	PAFSTAT_R_PAFSTAT_AFIDENT_PIXELS_GAP,
	PAFSTAT_R_PAFSTAT_AFIDENT_REG_INTERFACE_VER,
	PAFSTAT_R_PAFSTAT_AFIDENT_BLOCK_ID_CODE,
	PAFSTAT_R_PAFSTAT_AFIDENT_VERSION_ID_CODE,
	PAFSTAT_R_PAFSTAT_AFIDENT_STREAM_CRC,
	PAFSTAT_R_PAFSTAT_LBCTRL_BYPASS,
	PAFSTAT_R_PAFSTAT_LBCTRL_IMAGE_SIZE,
	PAFSTAT_R_PAFSTAT_LBCTRL_BPC_MODE,
	PAFSTAT_REG_CNT
};

static struct fimc_is_reg pafstat_regs[PAFSTAT_REG_CNT] = {
	{0x0000, "COM_QACTIVE_SET"},
	{0x0004, "COM_RESET_REQ"},
	{0x0008, "COM_RESET_REQ_BUSY"},
	{0x000C, "COM_DMA_FLUSH_REQ"},
	{0x0010, "COM_DMA_FLUSH_REQ_BUSY"},
	{0x0014, "COM_3AA_STALL_ENABLE"},
	{0x0018, "COM_LIC_MODE"},
	{0x001C, "COM_LIC_BYPASS"},
	{0x0020, "COM_LIC_SEL_SINGLE_INPUT"},
	{0x0024, "COM_SUB_STALL"},
	{0x0028, "COM_SUB_BUSY"},
	{0x002C, "COM_SUB_DVALID"},
	{0x0030, "COM_HBLANK_CYCLE"},
	{0x0034, "COM_DISABLE_OUTPUTMASK"},
	{0x0060, "COM_FRAME_NUM"},
	{0x0064, "COM_FRAME_NUM_STAT"},
	{0x0068, "COM_FRAME_NUM_MED_INT"},
	{0x006C, "COM_FRAME_CNT"},
	{0x0070, "COM_FRAME_STATUS"},
	{0x00FC, "COM_VERSION"},
	{0x0080, "CTX_GLOBAL_ENABLE"},
	{0x0084, "CTX_ONESHOT"},
	{0x0088, "CTX_SEL_OTF"},
	{0x008C, "CTX_INTERRUPT_SRC"},
	{0x0090, "CTX_INTERRUPT_MASK"},
	{0x0094, "CTX_TIMEOUT_CNT_INIT"},
	{0x0098, "CTX_TIMEOUT_CNT_MAX"},
	{0x009C, "CTX_SENSOR_MODE"},
	{0x00A0, "CTX_CURRENT_USE_A"},
	{0x00A4, "CTX_LINE_NUM_MED_INT"},
	{0x00C0, "CTX_INPUT_WIDTH"},
	{0x00C4, "CTX_INPUT_HEIGHT"},
	{0x00C8, "CTX_PD_PXL_WIDTH"},
	{0x00CC, "CTX_PD_PXL_HEIGHT"},
	{0x00D0, "CTX_CLK_CTRL"},
	{0x00D4, "CTX_LIC_IS_DMA"},
	{0x00D8, "CTX_SFR_READY"},
	{0x00DC, "CTX_LIC_4PPC"},
	{0x0100, "PAFSTAT_YEXTR_HDRMODE"},
	{0x0104, "PAFSTAT_YEXTR_MAXNOSKIPPXG"},
	{0x0108, "PAFSTAT_YEXTR_SKIPLEVELTH"},
	{0x010C, "PAFSTAT_YEXTR_SATVALUEG"},
	{0x0110, "PAFSTAT_YEXTR_SATVALUER"},
	{0x0114, "PAFSTAT_YEXTR_SATVALUEB"},
	{0x0118, "PAFSTAT_YEXTR_NUMOFSATG"},
	{0x011C, "PAFSTAT_YEXTR_NUMOFSATR"},
	{0x0120, "PAFSTAT_YEXTR_NUMOFSATB"},
	{0x0124, "PAFSTAT_YEXTR_SATVALSUMOFG"},
	{0x0128, "PAFSTAT_YEXTR_SATVALSUMOFR"},
	{0x012C, "PAFSTAT_YEXTR_SATVALSUMOFB"},
	{0x0130, "PAFSTAT_YEXTR_CLIPVALLEFT"},
	{0x0134, "PAFSTAT_YEXTR_CLIPVALRIGHT"},
	{0x0138, "PAFSTAT_YEXTR_COEFG"},
	{0x013C, "PAFSTAT_YEXTR_COEFR"},
	{0x0140, "PAFSTAT_YEXTR_COEFB"},
	{0x0144, "PAFSTAT_YEXTR_YSHIFT"},
	{0x0148, "PAFSTAT_YEXTR_COEFG_SHORT"},
	{0x014C, "PAFSTAT_YEXTR_COEFR_SHORT"},
	{0x0150, "PAFSTAT_YEXTR_COEFB_SHORT"},
	{0x0160, "PAFSTAT_YEXTR_CRC"},
	{0x0200, "PAFSTAT_BIN_BYPASS"},
	{0x0204, "PAFSTAT_BIN_CONFIG"},
	{0x0208, "PAFSTAT_BIN_IMAGE_SIZE"},
	{0x0210, "PAFSTAT_BIN_COEF_0"},
	{0x0214, "PAFSTAT_BIN_COEF_1"},
	{0x0218, "PAFSTAT_BIN_CRC_SEED"},
	{0x021C, "PAFSTAT_BIN_CRC_RESULT"},
	{0x0300, "PAFSTAT_REORDER_BYPASS"},
	{0x0304, "PAFSTAT_REORDER_ACTIVE_STA_X"},
	{0x0308, "PAFSTAT_REORDER_ACTIVE_STA_Y"},
	{0x0310, "PAFSTAT_REORDER_ACTIVE_SIZE_X"},
	{0x0314, "PAFSTAT_REORDER_ACTIVE_SIZE_Y"},
	{0x0318, "PAFSTAT_REORDER_UNIT_SIZE_X"},
	{0x031C, "PAFSTAT_REORDER_UNIT_SIZE_Y"},
	{0x0320, "PAFSTAT_REORDER_NUM_OF_UNIT_X"},
	{0x0324, "PAFSTAT_REORDER_NUM_OF_UNIT_Y"},
	{0x0330, "PAFSTAT_REORDER_LR_INDC_FLAG_MODE"},
	{0x0334, "PAFSTAT_REORDER_LR_POS_ENABLE"},
	{0x0338, "PAFSTAT_REORDER_LR_NUM_OF_UNIT_X_IN_BLK"},
	{0x033C, "PAFSTAT_REORDER_LR_NUM_OF_UNIT_Y_IN_BLK"},
	{0x0340, "PAFSTAT_REORDER_LR_POS_TABLE_0"},
	{0x0344, "PAFSTAT_REORDER_LR_POS_TABLE_1"},
	{0x0348, "PAFSTAT_REORDER_LR_POS_TABLE_2"},
	{0x034C, "PAFSTAT_REORDER_LR_POS_TABLE_3"},
	{0x0350, "PAFSTAT_REORDER_LR_POS_TABLE_4"},
	{0x0354, "PAFSTAT_REORDER_LR_POS_TABLE_5"},
	{0x0358, "PAFSTAT_REORDER_LR_POS_TABLE_6"},
	{0x035C, "PAFSTAT_REORDER_LR_POS_TABLE_7"},
	{0x0360, "PAFSTAT_REORDER_LR_POS_TABLE_8"},
	{0x0364, "PAFSTAT_REORDER_LR_POS_TABLE_9"},
	{0x0368, "PAFSTAT_REORDER_LR_POS_TABLE_10"},
	{0x036C, "PAFSTAT_REORDER_LR_POS_TABLE_11"},
	{0x0370, "PAFSTAT_REORDER_LR_POS_TABLE_12"},
	{0x0374, "PAFSTAT_REORDER_LR_POS_TABLE_13"},
	{0x0378, "PAFSTAT_REORDER_LR_POS_TABLE_14"},
	{0x037C, "PAFSTAT_REORDER_LR_POS_TABLE_15"},
	{0x0380, "PAFSTAT_REORDER_LR_NUM_OF_BLK_IN_LINE"},
	{0x0384, "PAFSTAT_REORDER_LR_NUM_OF_PXL_IN_LINE"},
	{0x0388, "PAFSTAT_REORDER_CRC_SEED"},
	{0x038C, "PAFSTAT_REORDER_CRC_RESULT"},
	{0x0400, "PAFSTAT_LSC_BYPASS"},
	{0x0404, "PAFSTAT_LSC_HDR_MODE"},
	{0x0410, "PAFSTAT_LSC_MIRROR_MODE"},
	{0x0414, "PAFSTAT_LSC_PEDESTAL_EN"},
	{0x0418, "PAFSTAT_LSC_PEDESTAL_CUT"},
	{0x041C, "PAFSTAT_LSC_PEDESTAL_IN"},
	{0x0420, "PAFSTAT_LSC_PEDESTAL_OUT"},
	{0x0424, "PAFSTAT_LSC_START_X"},
	{0x0428, "PAFSTAT_LSC_START_Y"},
	{0x042C, "PAFSTAT_LSC_STEP_X"},
	{0x0430, "PAFSTAT_LSC_STEP_Y"},
	{0x0434, "PAFSTAT_LSC_GAIN_WEIGHT_INF"},
	{0x0438, "PAFSTAT_LSC_GAIN_WEIGHT_MAC"},
	{0x043C, "PAFSTAT_LSC_GAIN_SHIFT"},
	{0x0444, "PAFSTAT_LSC_GAIN_ADDR_0"},
	{0x0448, "PAFSTAT_LSC_GAIN_DATA_0"},
	{0x044C, "PAFSTAT_LSC_GAIN_ADDR_1"},
	{0x0450, "PAFSTAT_LSC_GAIN_DATA_1"},
	{0x0454, "PAFSTAT_LSC_CRC_SEED"},
	{0x0458, "PAFSTAT_LSC_CRC_RESULT"},
	{0x0504, "PAFSTAT_BPC_BYPASS"},
	{0x0508, "PAFSTAT_BPC_POS_NUM"},
	{0x0510, "PAFSTAT_BPC_STATIC_POS_ADDR"},
	{0x0514, "PAFSTAT_BPC_STATIC_POS_DATA"},
	{0x0518, "PAFSTAT_BPC_CRC_SEED"},
	{0x051C, "PAFSTAT_BPC_CRC_RESULT"},
	{0x0600, "PAFSTAT_GAMMA_BYPASS"},
	{0x0608, "PAFSTAT_GAMMA_PEDESTAL_EN"},
	{0x0610, "PAFSTAT_GAMMA_PEDESTAL"},
	{0x0614, "PAFSTAT_GAMMA_HDR_MODE"},
	{0x0618, "PAFSTAT_GAMMA_LUT_00"},
	{0x061C, "PAFSTAT_GAMMA_LUT_01"},
	{0x0620, "PAFSTAT_GAMMA_LUT_02"},
	{0x0624, "PAFSTAT_GAMMA_LUT_03"},
	{0x0628, "PAFSTAT_GAMMA_LUT_04"},
	{0x062C, "PAFSTAT_GAMMA_LUT_05"},
	{0x0630, "PAFSTAT_GAMMA_LUT_06"},
	{0x0634, "PAFSTAT_GAMMA_LUT_07"},
	{0x0638, "PAFSTAT_GAMMA_LUT_08"},
	{0x063C, "PAFSTAT_GAMMA_LUT_09"},
	{0x0640, "PAFSTAT_GAMMA_LUT_10"},
	{0x0644, "PAFSTAT_GAMMA_LUT_11"},
	{0x0648, "PAFSTAT_GAMMA_LUT_12"},
	{0x064C, "PAFSTAT_GAMMA_LUT_13"},
	{0x0650, "PAFSTAT_GAMMA_LUT_14"},
	{0x0654, "PAFSTAT_GAMMA_LUT_15"},
	{0x0658, "PAFSTAT_GAMMA_LUT_16"},
	{0x065C, "PAFSTAT_GAMMA_LUT_17"},
	{0x0660, "PAFSTAT_GAMMA_LUT_18"},
	{0x0664, "PAFSTAT_GAMMA_LUT_19"},
	{0x0668, "PAFSTAT_GAMMA_LUT_20"},
	{0x066C, "PAFSTAT_GAMMA_LUT_21"},
	{0x0670, "PAFSTAT_GAMMA_LUT_22"},
	{0x0674, "PAFSTAT_GAMMA_LUT_23"},
	{0x0678, "PAFSTAT_GAMMA_LUT_24"},
	{0x067C, "PAFSTAT_GAMMA_LUT_25"},
	{0x0680, "PAFSTAT_GAMMA_LUT_26"},
	{0x0684, "PAFSTAT_GAMMA_LUT_27"},
	{0x0688, "PAFSTAT_GAMMA_LUT_28"},
	{0x068C, "PAFSTAT_GAMMA_LUT_29"},
	{0x0690, "PAFSTAT_GAMMA_LUT_30"},
	{0x0694, "PAFSTAT_GAMMA_LUT_31"},
	{0x0698, "PAFSTAT_GAMMA_CRC_SEED"},
	{0x069C, "PAFSTAT_GAMMA_CRC_RESULT"},
	{0x0718, "PAFSTAT_GAMMA_LUT_SHORT_00"},
	{0x071C, "PAFSTAT_GAMMA_LUT_SHORT_01"},
	{0x0720, "PAFSTAT_GAMMA_LUT_SHORT_02"},
	{0x0724, "PAFSTAT_GAMMA_LUT_SHORT_03"},
	{0x0728, "PAFSTAT_GAMMA_LUT_SHORT_04"},
	{0x072C, "PAFSTAT_GAMMA_LUT_SHORT_05"},
	{0x0730, "PAFSTAT_GAMMA_LUT_SHORT_06"},
	{0x0734, "PAFSTAT_GAMMA_LUT_SHORT_07"},
	{0x0738, "PAFSTAT_GAMMA_LUT_SHORT_08"},
	{0x073C, "PAFSTAT_GAMMA_LUT_SHORT_09"},
	{0x0740, "PAFSTAT_GAMMA_LUT_SHORT_10"},
	{0x0744, "PAFSTAT_GAMMA_LUT_SHORT_11"},
	{0x0748, "PAFSTAT_GAMMA_LUT_SHORT_12"},
	{0x074C, "PAFSTAT_GAMMA_LUT_SHORT_13"},
	{0x0750, "PAFSTAT_GAMMA_LUT_SHORT_14"},
	{0x0754, "PAFSTAT_GAMMA_LUT_SHORT_15"},
	{0x0758, "PAFSTAT_GAMMA_LUT_SHORT_16"},
	{0x075C, "PAFSTAT_GAMMA_LUT_SHORT_17"},
	{0x0760, "PAFSTAT_GAMMA_LUT_SHORT_18"},
	{0x0764, "PAFSTAT_GAMMA_LUT_SHORT_19"},
	{0x0768, "PAFSTAT_GAMMA_LUT_SHORT_20"},
	{0x076C, "PAFSTAT_GAMMA_LUT_SHORT_21"},
	{0x0770, "PAFSTAT_GAMMA_LUT_SHORT_22"},
	{0x0774, "PAFSTAT_GAMMA_LUT_SHORT_23"},
	{0x0778, "PAFSTAT_GAMMA_LUT_SHORT_24"},
	{0x077C, "PAFSTAT_GAMMA_LUT_SHORT_25"},
	{0x0780, "PAFSTAT_GAMMA_LUT_SHORT_26"},
	{0x0784, "PAFSTAT_GAMMA_LUT_SHORT_27"},
	{0x0788, "PAFSTAT_GAMMA_LUT_SHORT_28"},
	{0x078C, "PAFSTAT_GAMMA_LUT_SHORT_29"},
	{0x0790, "PAFSTAT_GAMMA_LUT_SHORT_30"},
	{0x0794, "PAFSTAT_GAMMA_LUT_SHORT_31"},
	{0x0800, "PAFSTAT_STAT_BYPASS"},
	{0x0804, "PAFSTAT_STAT_HDR_MODE"},
	{0x0808, "PAFSTAT_STAT_PAD_EXPAND"},
	{0x080C, "PAFSTAT_STAT_UPSAMPLE_BYPASS"},
	{0x0810, "PAFSTAT_STAT_UPSAMPLE_RATIO"},
	{0x0814, "PAFSTAT_STAT_UPSAMPLE_COEF_0_0"},
	{0x0818, "PAFSTAT_STAT_UPSAMPLE_COEF_0_1"},
	{0x081C, "PAFSTAT_STAT_UPSAMPLE_COEF_0_2"},
	{0x0820, "PAFSTAT_STAT_UPSAMPLE_COEF_0_3"},
	{0x0824, "PAFSTAT_STAT_UPSAMPLE_COEF_0_4"},
	{0x0828, "PAFSTAT_STAT_UPSAMPLE_COEF_0_5"},
	{0x082C, "PAFSTAT_STAT_UPSAMPLE_COEF_0_6"},
	{0x0830, "PAFSTAT_STAT_UPSAMPLE_COEF_0_7"},
	{0x0834, "PAFSTAT_STAT_UPSAMPLE_COEF_1_0"},
	{0x0838, "PAFSTAT_STAT_UPSAMPLE_COEF_1_1"},
	{0x083C, "PAFSTAT_STAT_UPSAMPLE_COEF_1_2"},
	{0x0840, "PAFSTAT_STAT_UPSAMPLE_COEF_1_3"},
	{0x0844, "PAFSTAT_STAT_UPSAMPLE_COEF_1_4"},
	{0x0848, "PAFSTAT_STAT_UPSAMPLE_COEF_1_5"},
	{0x084C, "PAFSTAT_STAT_UPSAMPLE_COEF_1_6"},
	{0x0850, "PAFSTAT_STAT_UPSAMPLE_COEF_1_7"},
	{0x0854, "PAFSTAT_STAT_UPSAMPLE_COEF_2_0"},
	{0x0858, "PAFSTAT_STAT_UPSAMPLE_COEF_2_1"},
	{0x085C, "PAFSTAT_STAT_UPSAMPLE_COEF_2_2"},
	{0x0860, "PAFSTAT_STAT_UPSAMPLE_COEF_2_3"},
	{0x0864, "PAFSTAT_STAT_UPSAMPLE_COEF_2_4"},
	{0x0868, "PAFSTAT_STAT_UPSAMPLE_COEF_2_5"},
	{0x086C, "PAFSTAT_STAT_UPSAMPLE_COEF_2_6"},
	{0x0870, "PAFSTAT_STAT_UPSAMPLE_COEF_2_7"},
	{0x0874, "PAFSTAT_STAT_UPSAMPLE_COEF_3_0"},
	{0x0878, "PAFSTAT_STAT_UPSAMPLE_COEF_3_1"},
	{0x087C, "PAFSTAT_STAT_UPSAMPLE_COEF_3_2"},
	{0x0880, "PAFSTAT_STAT_UPSAMPLE_COEF_3_3"},
	{0x0884, "PAFSTAT_STAT_UPSAMPLE_COEF_3_4"},
	{0x0888, "PAFSTAT_STAT_UPSAMPLE_COEF_3_5"},
	{0x088C, "PAFSTAT_STAT_UPSAMPLE_COEF_3_6"},
	{0x0890, "PAFSTAT_STAT_UPSAMPLE_COEF_3_7"},
	{0x089C, "PAFSTAT_STAT_LPF_BYPASS"},
	{0x08A8, "PAFSTAT_STAT_GRAD_BYPASS"},
	{0x08AC, "PAFSTAT_STAT_GRAD_LEVEL"},
	{0x08B8, "PAFSTAT_STAT_CORR_MATCH_METHOD"},
	{0x08BC, "PAFSTAT_STAT_CORR_MAX_DISPARITY"},
	{0x08C0, "PAFSTAT_STAT_CORR_LR_ORDER"},
	{0x08C4, "PAFSTAT_STAT_CORR_SAT_LEVEL"},
	{0x0900, "PAFSTAT_STAT_FWIN_0_ENABLE"},
	{0x0904, "PAFSTAT_STAT_FWIN_1_ENABLE"},
	{0x0908, "PAFSTAT_STAT_FWIN_2_ENABLE"},
	{0x090C, "PAFSTAT_STAT_FWIN_3_ENABLE"},
	{0x0910, "PAFSTAT_STAT_FWIN_4_ENABLE"},
	{0x0914, "PAFSTAT_STAT_FWIN_5_ENABLE"},
	{0x0918, "PAFSTAT_STAT_FWIN_0_POS_STA_X"},
	{0x091C, "PAFSTAT_STAT_FWIN_0_POS_STA_Y"},
	{0x0920, "PAFSTAT_STAT_FWIN_0_POS_END_X"},
	{0x0924, "PAFSTAT_STAT_FWIN_0_POS_END_Y"},
	{0x0928, "PAFSTAT_STAT_FWIN_1_POS_STA_X"},
	{0x092C, "PAFSTAT_STAT_FWIN_1_POS_STA_Y"},
	{0x0930, "PAFSTAT_STAT_FWIN_1_POS_END_X"},
	{0x0934, "PAFSTAT_STAT_FWIN_1_POS_END_Y"},
	{0x0938, "PAFSTAT_STAT_FWIN_2_POS_STA_X"},
	{0x093C, "PAFSTAT_STAT_FWIN_2_POS_STA_Y"},
	{0x0940, "PAFSTAT_STAT_FWIN_2_POS_END_X"},
	{0x0944, "PAFSTAT_STAT_FWIN_2_POS_END_Y"},
	{0x0948, "PAFSTAT_STAT_FWIN_3_POS_STA_X"},
	{0x094C, "PAFSTAT_STAT_FWIN_3_POS_STA_Y"},
	{0x0950, "PAFSTAT_STAT_FWIN_3_POS_END_X"},
	{0x0954, "PAFSTAT_STAT_FWIN_3_POS_END_Y"},
	{0x0958, "PAFSTAT_STAT_FWIN_4_POS_STA_X"},
	{0x095C, "PAFSTAT_STAT_FWIN_4_POS_STA_Y"},
	{0x0960, "PAFSTAT_STAT_FWIN_4_POS_END_X"},
	{0x0964, "PAFSTAT_STAT_FWIN_4_POS_END_Y"},
	{0x0968, "PAFSTAT_STAT_FWIN_5_POS_STA_X"},
	{0x096C, "PAFSTAT_STAT_FWIN_5_POS_STA_Y"},
	{0x0970, "PAFSTAT_STAT_FWIN_5_POS_END_X"},
	{0x0974, "PAFSTAT_STAT_FWIN_5_POS_END_Y"},
	{0x0978, "PAFSTAT_STAT_SWIN_ENABLE"},
	{0x097C, "PAFSTAT_STAT_SWIN_BLK_NUM_X"},
	{0x0980, "PAFSTAT_STAT_SWIN_BLK_NUM_Y"},
	{0x0984, "PAFSTAT_STAT_SWIN_BLK_SIZE_X"},
	{0x0988, "PAFSTAT_STAT_SWIN_BLK_SIZE_Y"},
	{0x098C, "PAFSTAT_STAT_SWIN_POS_STA_X"},
	{0x0990, "PAFSTAT_STAT_SWIN_POS_STA_Y"},
	{0x0994, "PAFSTAT_STAT_FWIN_0_INTEGRAL_SHIFT"},
	{0x0998, "PAFSTAT_STAT_FWIN_1_INTEGRAL_SHIFT"},
	{0x099C, "PAFSTAT_STAT_FWIN_2_INTEGRAL_SHIFT"},
	{0x09A0, "PAFSTAT_STAT_FWIN_3_INTEGRAL_SHIFT"},
	{0x09A4, "PAFSTAT_STAT_FWIN_4_INTEGRAL_SHIFT"},
	{0x09A8, "PAFSTAT_STAT_FWIN_5_INTEGRAL_SHIFT"},
	{0x09AC, "PAFSTAT_STAT_FWIN_0_LPF_COEF0"},
	{0x09B0, "PAFSTAT_STAT_FWIN_0_LPF_COEF1"},
	{0x09B4, "PAFSTAT_STAT_FWIN_0_LPF_COEF2"},
	{0x09B8, "PAFSTAT_STAT_FWIN_0_LPF_COEF3"},
	{0x09BC, "PAFSTAT_STAT_FWIN_1_LPF_COEF0"},
	{0x09C0, "PAFSTAT_STAT_FWIN_1_LPF_COEF1"},
	{0x09C4, "PAFSTAT_STAT_FWIN_1_LPF_COEF2"},
	{0x09C8, "PAFSTAT_STAT_FWIN_1_LPF_COEF3"},
	{0x09CC, "PAFSTAT_STAT_FWIN_2_LPF_COEF0"},
	{0x09D0, "PAFSTAT_STAT_FWIN_2_LPF_COEF1"},
	{0x09D4, "PAFSTAT_STAT_FWIN_2_LPF_COEF2"},
	{0x09D8, "PAFSTAT_STAT_FWIN_2_LPF_COEF3"},
	{0x09DC, "PAFSTAT_STAT_FWIN_3_LPF_COEF0"},
	{0x09E0, "PAFSTAT_STAT_FWIN_3_LPF_COEF1"},
	{0x09E4, "PAFSTAT_STAT_FWIN_3_LPF_COEF2"},
	{0x09E8, "PAFSTAT_STAT_FWIN_3_LPF_COEF3"},
	{0x09EC, "PAFSTAT_STAT_FWIN_4_LPF_COEF0"},
	{0x09F0, "PAFSTAT_STAT_FWIN_4_LPF_COEF1"},
	{0x09F4, "PAFSTAT_STAT_FWIN_4_LPF_COEF2"},
	{0x09F8, "PAFSTAT_STAT_FWIN_4_LPF_COEF3"},
	{0x09FC, "PAFSTAT_STAT_FWIN_5_LPF_COEF0"},
	{0x0A00, "PAFSTAT_STAT_FWIN_5_LPF_COEF1"},
	{0x0A04, "PAFSTAT_STAT_FWIN_5_LPF_COEF2"},
	{0x0A08, "PAFSTAT_STAT_FWIN_5_LPF_COEF3"},
	{0x0A0C, "PAFSTAT_STAT_FWIN_0_LPF_COEF_SHIFT"},
	{0x0A10, "PAFSTAT_STAT_FWIN_1_LPF_COEF_SHIFT"},
	{0x0A14, "PAFSTAT_STAT_FWIN_2_LPF_COEF_SHIFT"},
	{0x0A18, "PAFSTAT_STAT_FWIN_3_LPF_COEF_SHIFT"},
	{0x0A1C, "PAFSTAT_STAT_FWIN_4_LPF_COEF_SHIFT"},
	{0x0A20, "PAFSTAT_STAT_FWIN_5_LPF_COEF_SHIFT"},
	{0x0A24, "PAFSTAT_STAT_FWIN_0_GRAD_COEF0"},
	{0x0A28, "PAFSTAT_STAT_FWIN_0_GRAD_COEF1"},
	{0x0A2C, "PAFSTAT_STAT_FWIN_0_GRAD_COEF2"},
	{0x0A30, "PAFSTAT_STAT_FWIN_0_GRAD_COEF3"},
	{0x0A34, "PAFSTAT_STAT_FWIN_1_GRAD_COEF0"},
	{0x0A38, "PAFSTAT_STAT_FWIN_1_GRAD_COEF1"},
	{0x0A3C, "PAFSTAT_STAT_FWIN_1_GRAD_COEF2"},
	{0x0A40, "PAFSTAT_STAT_FWIN_1_GRAD_COEF3"},
	{0x0A44, "PAFSTAT_STAT_FWIN_2_GRAD_COEF0"},
	{0x0A48, "PAFSTAT_STAT_FWIN_2_GRAD_COEF1"},
	{0x0A4C, "PAFSTAT_STAT_FWIN_2_GRAD_COEF2"},
	{0x0A50, "PAFSTAT_STAT_FWIN_2_GRAD_COEF3"},
	{0x0A54, "PAFSTAT_STAT_FWIN_3_GRAD_COEF0"},
	{0x0A58, "PAFSTAT_STAT_FWIN_3_GRAD_COEF1"},
	{0x0A5C, "PAFSTAT_STAT_FWIN_3_GRAD_COEF2"},
	{0x0A60, "PAFSTAT_STAT_FWIN_3_GRAD_COEF3"},
	{0x0A64, "PAFSTAT_STAT_FWIN_4_GRAD_COEF0"},
	{0x0A68, "PAFSTAT_STAT_FWIN_4_GRAD_COEF1"},
	{0x0A6C, "PAFSTAT_STAT_FWIN_4_GRAD_COEF2"},
	{0x0A70, "PAFSTAT_STAT_FWIN_4_GRAD_COEF3"},
	{0x0A74, "PAFSTAT_STAT_FWIN_5_GRAD_COEF0"},
	{0x0A78, "PAFSTAT_STAT_FWIN_5_GRAD_COEF1"},
	{0x0A7C, "PAFSTAT_STAT_FWIN_5_GRAD_COEF2"},
	{0x0A80, "PAFSTAT_STAT_FWIN_5_GRAD_COEF3"},
	{0x0A84, "PAFSTAT_STAT_FWIN_0_GRAD_COEF_SHIFT"},
	{0x0A88, "PAFSTAT_STAT_FWIN_1_GRAD_COEF_SHIFT"},
	{0x0A8C, "PAFSTAT_STAT_FWIN_2_GRAD_COEF_SHIFT"},
	{0x0A90, "PAFSTAT_STAT_FWIN_3_GRAD_COEF_SHIFT"},
	{0x0A94, "PAFSTAT_STAT_FWIN_4_GRAD_COEF_SHIFT"},
	{0x0A98, "PAFSTAT_STAT_FWIN_5_GRAD_COEF_SHIFT"},
	{0x0A9C, "PAFSTAT_STAT_SWIN_INTEGRAL_SHIFT"},
	{0x0AA0, "PAFSTAT_STAT_SWIN_LPF_COEF0"},
	{0x0AA4, "PAFSTAT_STAT_SWIN_LPF_COEF1"},
	{0x0AA8, "PAFSTAT_STAT_SWIN_LPF_COEF2"},
	{0x0AAC, "PAFSTAT_STAT_SWIN_LPF_COEF3"},
	{0x0AB0, "PAFSTAT_STAT_SWIN_LPF_COEF_SHIFT"},
	{0x0AB4, "PAFSTAT_STAT_SWIN_GRAD_COEF0"},
	{0x0AB8, "PAFSTAT_STAT_SWIN_GRAD_COEF1"},
	{0x0ABC, "PAFSTAT_STAT_SWIN_GRAD_COEF2"},
	{0x0AC0, "PAFSTAT_STAT_SWIN_GRAD_COEF3"},
	{0x0AC4, "PAFSTAT_STAT_SWIN_GRAD_COEF_SHIFT"},
	{0x0AC8, "PAFSTAT_STAT_FWIN_0_CORR_SHIFT"},
	{0x0ACC, "PAFSTAT_STAT_FWIN_1_CORR_SHIFT"},
	{0x0AD0, "PAFSTAT_STAT_FWIN_2_CORR_SHIFT"},
	{0x0AD4, "PAFSTAT_STAT_FWIN_3_CORR_SHIFT"},
	{0x0AD8, "PAFSTAT_STAT_FWIN_4_CORR_SHIFT"},
	{0x0ADC, "PAFSTAT_STAT_FWIN_5_CORR_SHIFT"},
	{0x0AE0, "PAFSTAT_STAT_SWIN_CORR_SHIFT"},
	{0x0B00, "PAFSTAT_STAT_RESULT_OUT_FW0_START_ADDR"},
	{0x0B04, "PAFSTAT_STAT_RESULT_OUT_FW0_ACCESS"},
	{0x0B08, "PAFSTAT_STAT_RESULT_OUT_FW1_START_ADDR"},
	{0x0B0C, "PAFSTAT_STAT_RESULT_OUT_FW1_ACCESS"},
	{0x0B10, "PAFSTAT_STAT_RESULT_OUT_FW2_START_ADDR"},
	{0x0B14, "PAFSTAT_STAT_RESULT_OUT_FW2_ACCESS"},
	{0x0B18, "PAFSTAT_STAT_RESULT_OUT_FW3_START_ADDR"},
	{0x0B1C, "PAFSTAT_STAT_RESULT_OUT_FW3_ACCESS"},
	{0x0B20, "PAFSTAT_STAT_RESULT_OUT_FW4_START_ADDR"},
	{0x0B24, "PAFSTAT_STAT_RESULT_OUT_FW4_ACCESS"},
	{0x0B28, "PAFSTAT_STAT_RESULT_OUT_FW5_START_ADDR"},
	{0x0B2C, "PAFSTAT_STAT_RESULT_OUT_FW5_ACCESS"},
	{0x0B30, "PAFSTAT_STAT_FWIN_INTEGRAL_CRC_SEED"},
	{0x0B34, "PAFSTAT_STAT_FWIN_INTEGRAL_CRC_RESULT"},
	{0x0B38, "PAFSTAT_STAT_FWIN_UPSAMPLE_CRC_SEED"},
	{0x0B3C, "PAFSTAT_STAT_FWIN_UPSAMPLE_CRC_RESULT"},
	{0x0B40, "PAFSTAT_STAT_FWIN_LPF_CRC_SEED"},
	{0x0B44, "PAFSTAT_STAT_FWIN_LPF_CRC_RESULT"},
	{0x0B48, "PAFSTAT_STAT_FWIN_GRAD_CRC_SEED"},
	{0x0B4C, "PAFSTAT_STAT_FWIN_GRAD_CRC_RESULT"},
	{0x0B50, "PAFSTAT_STAT_SWIN_INTEGRAL_CRC_SEED"},
	{0x0B54, "PAFSTAT_STAT_SWIN_INTEGRAL_CRC_RESULT"},
	{0x0B58, "PAFSTAT_STAT_SWIN_UPSAMPLE_CRC_SEED"},
	{0x0B5C, "PAFSTAT_STAT_SWIN_UPSAMPLE_CRC_RESULT"},
	{0x0B60, "PAFSTAT_STAT_SWIN_LPF_CRC_SEED"},
	{0x0B64, "PAFSTAT_STAT_SWIN_LPF_CRC_RESULT"},
	{0x0B68, "PAFSTAT_STAT_SWIN_GRAD_CRC_SEED"},
	{0x0B6C, "PAFSTAT_STAT_SWIN_GRAD_CRC_RESULT"},
	{0x0D00, "PAFSTAT_AFIDENT_BYPASS"},
	{0x0D04, "PAFSTAT_AFIDENT_START_ACTIVE_X"},
	{0x0D08, "PAFSTAT_AFIDENT_START_ACTIVE_Y"},
	{0x0D0C, "PAFSTAT_AFIDENT_ACTIVE_WIDTH"},
	{0x0D10, "PAFSTAT_AFIDENT_ACTIVE_HEIGHT"},
	{0x0D14, "PAFSTAT_AFIDENT_UNIT_OFFSET_X"},
	{0x0D18, "PAFSTAT_AFIDENT_UNIT_OFFSET_Y"},
	{0x0D1C, "PAFSTAT_AFIDENT_RELATIVE_OFFSET_X"},
	{0x0D20, "PAFSTAT_AFIDENT_RELATIVE_OFFSET_Y"},
	{0x0D24, "PAFSTAT_AFIDENT_OUTPUT_TYPE0"},
	{0x0D28, "PAFSTAT_AFIDENT_BLOCKS_PER_ACTIVE_X"},
	{0x0D2C, "PAFSTAT_AFIDENT_BLOCKS_PER_ACTIVE_Y"},
	{0x0D30, "PAFSTAT_AFIDENT_DATA_IN_TAIL"},
	{0x0D34, "PAFSTAT_AFIDENT_TAIL_START"},
	{0x0D38, "PAFSTAT_AFIDENT_TAIL_SPLIT"},
	{0x0D3C, "PAFSTAT_AFIDENT_BLOCKS_FIRST_SPLIT_TAIL"},
	{0x0D40, "PAFSTAT_AFIDENT_BLOCKS_SECOND_SPLIT_TAIL"},
	{0x0D44, "PAFSTAT_AFIDENT_UNIT_SIZE_X"},
	{0x0D48, "PAFSTAT_AFIDENT_UNIT_SIZE_Y"},
	{0x0D4C, "PAFSTAT_AFIDENT_PTRN_X_0"},
	{0x0D50, "PAFSTAT_AFIDENT_PTRN_X_1"},
	{0x0D54, "PAFSTAT_AFIDENT_PTRN_X_2"},
	{0x0D58, "PAFSTAT_AFIDENT_PTRN_X_3"},
	{0x0D5C, "PAFSTAT_AFIDENT_PTRN_X_4"},
	{0x0D60, "PAFSTAT_AFIDENT_PTRN_X_5"},
	{0x0D64, "PAFSTAT_AFIDENT_PTRN_X_6"},
	{0x0D68, "PAFSTAT_AFIDENT_PTRN_X_7"},
	{0x0D6C, "PAFSTAT_AFIDENT_PTRN_Y_0"},
	{0x0D70, "PAFSTAT_AFIDENT_PTRN_Y_1"},
	{0x0D74, "PAFSTAT_AFIDENT_PTRN_Y_2"},
	{0x0D78, "PAFSTAT_AFIDENT_PTRN_Y_3"},
	{0x0D7C, "PAFSTAT_AFIDENT_PTRN_Y_4"},
	{0x0D80, "PAFSTAT_AFIDENT_PTRN_Y_5"},
	{0x0D84, "PAFSTAT_AFIDENT_PTRN_Y_6"},
	{0x0D88, "PAFSTAT_AFIDENT_PTRN_Y_7"},
	{0x0D8C, "PAFSTAT_AFIDENT_UNITS_PER_BLOCK_X"},
	{0x0D90, "PAFSTAT_AFIDENT_UNIS_PER_BLOCK_Y"},
	{0x0D94, "PAFSTAT_AFIDENT_PTRN_0"},
	{0x0D98, "PAFSTAT_AFIDENT_PTRN_1"},
	{0x0D9C, "PAFSTAT_AFIDENT_PTRN_2"},
	{0x0DA0, "PAFSTAT_AFIDENT_PTRN_3"},
	{0x0DA4, "PAFSTAT_AFIDENT_SWITCHED_PTRN"},
	{0x0DA8, "PAFSTAT_AFIDENT_RATE_CNTRL_EN"},
	{0x0DAC, "PAFSTAT_AFIDENT_PIXELS_GAP"},
	{0x0DB0, "PAFSTAT_AFIDENT_REG_INTERFACE_VER"},
	{0x0DB4, "PAFSTAT_AFIDENT_BLOCK_ID_CODE"},
	{0x0DB8, "PAFSTAT_AFIDENT_VERSION_ID_CODE"},
	{0x0DBC, "PAFSTAT_AFIDENT_STREAM_CRC"},
	{0x0F00, "PAFSTAT_LBCTRL_BYPASS"},
	{0x0F04, "PAFSTAT_LBCTRL_IMAGE_SIZE"},
	{0x0F08, "PAFSTAT_LBCTRL_BPC_MODE"},
};

/* the total count of the fields of pafstat v1.0's reg */
enum fimc_is_hw_pafstat_reg_field {
	PAFSTAT_F_COM_QACTIVE_SET,
	PAFSTAT_F_COM_RESET_REQ,
	PAFSTAT_F_COM_RESET_REQ_BUSY,
	PAFSTAT_F_COM_DMA_FLUSH_REQ,
	PAFSTAT_F_COM_DMA_FLUSH_REQ_BUSY,
	PAFSTAT_F_COM_3AA_STALL_ENABLE,
	PAFSTAT_F_COM_LIC_MODE,
	PAFSTAT_F_COM_LIC_BYPASS,
	PAFSTAT_F_COM_LIC_SEL_SINGLE_INPUT,
	PAFSTAT_F_COM_SUB_STALL,
	PAFSTAT_F_COM_SUB_BUSY,
	PAFSTAT_F_COM_SUB_DVALID,
	PAFSTAT_F_COM_HBLANK_CYCLE,
	PAFSTAT_F_COM_DISABLE_OUTPUTMASK,
	PAFSTAT_F_COM_FRAME_NUM,
	PAFSTAT_F_COM_FRAME_NUM_STAT,
	PAFSTAT_F_COM_FRAME_NUM_MED_INT,
	PAFSTAT_F_COM_FRAME_CNT,
	PAFSTAT_F_COM_FRAME_STATUS,
	PAFSTAT_F_COM_VERSION,
	PAFSTAT_F_CTX_GLOBAL_ENABLE,
	PAFSTAT_F_CTX_ONESHOT,
	PAFSTAT_F_CTX_SEL_OTF,
	PAFSTAT_F_CTX_INTERRUPT_SRC,
	PAFSTAT_F_CTX_INTERRUPT_MASK,
	PAFSTAT_F_CTX_TIMEOUT_CNT_INIT,
	PAFSTAT_F_CTX_TIMEOUT_CNT_VAL,
	PAFSTAT_F_CTX_SENSOR_MODE,
	PAFSTAT_F_CTX_CURRENT_USE_A,
	PAFSTAT_F_CTX_LINE_NUM_MED_INT,
	PAFSTAT_F_CTX_INPUT_WIDTH,
	PAFSTAT_F_CTX_INPUT_HEIGHT,
	PAFSTAT_F_CTX_PD_PXL_WIDTH,
	PAFSTAT_F_CTX_PD_PXL_HEIGHT,
	PAFSTAT_F_CTX_CLK_CTRL,
	PAFSTAT_F_CTX_LIC_IS_DMA,
	PAFSTAT_F_CTX_SFR_READY,
	PAFSTAT_F_CTX_LIC_4PPC,
	PAFSTAT_F_YEXTR_HDRMODE,
	PAFSTAT_F_YEXTR_MAXNOSKIPPXG,
	PAFSTAT_F_YEXTR_SKIPLEVELTH,
	PAFSTAT_F_YEXTR_SATVALUEG,
	PAFSTAT_F_YEXTR_SATVALUER,
	PAFSTAT_F_YEXTR_SATVALUEB,
	PAFSTAT_F_YEXTR_NUMOFSATG,
	PAFSTAT_F_YEXTR_NUMOFSATR,
	PAFSTAT_F_YEXTR_NUMOFSATB,
	PAFSTAT_F_YEXTR_SATVALSUMOFG,
	PAFSTAT_F_YEXTR_SATVALSUMOFR,
	PAFSTAT_F_YEXTR_SATVALSUMOFB,
	PAFSTAT_F_YEXTR_CLIPVALLEFT,
	PAFSTAT_F_YEXTR_CLIPVALRIGHT,
	PAFSTAT_F_YEXTR_COEFG,
	PAFSTAT_F_YEXTR_COEFR,
	PAFSTAT_F_YEXTR_COEFB,
	PAFSTAT_F_YEXTR_YSHIFT,
	PAFSTAT_F_YEXTR_COEFG_SHORT,
	PAFSTAT_F_YEXTR_COEFR_SHORT,
	PAFSTAT_F_YEXTR_COEFB_SHORT,
	PAFSTAT_F_YEXTR_CRC_RESULT,
	PAFSTAT_F_YEXTR_CRC_SEED,
	PAFSTAT_F_BIN_BYPASS,
	PAFSTAT_F_BIN_HDR_MODE,
	PAFSTAT_F_BIN_MODE,
	PAFSTAT_F_BIN_IMG_HEIGHT,
	PAFSTAT_F_BIN_IMG_WIDTH,
	PAFSTAT_F_BIN_COEF_3,
	PAFSTAT_F_BIN_COEF_2,
	PAFSTAT_F_BIN_COEF_1,
	PAFSTAT_F_BIN_COEF_0,
	PAFSTAT_F_BIN_COEF_6,
	PAFSTAT_F_BIN_COEF_5,
	PAFSTAT_F_BIN_COEF_4,
	PAFSTAT_F_BIN_CRC_SEED,
	PAFSTAT_F_BIN_CRC_RESULT,
	PAFSTAT_F_REORDER_BYPASS,
	PAFSTAT_F_REORDER_ACTIVE_STA_X,
	PAFSTAT_F_REORDER_ACTIVE_STA_Y,
	PAFSTAT_F_REORDER_ACTIVE_SIZE_X,
	PAFSTAT_F_REORDER_ACTIVE_SIZE_Y,
	PAFSTAT_F_REORDER_UNIT_SIZE_X,
	PAFSTAT_F_REORDER_UNIT_SIZE_Y,
	PAFSTAT_F_REORDER_UNIT_NUM_X,
	PAFSTAT_F_REORDER_UNIT_NUM_Y,
	PAFSTAT_F_REORDER_LR_INDC_FLAG_MODE,
	PAFSTAT_F_REORDER_LR_POS_ENABLE,
	PAFSTAT_F_REORDER_LR_NUM_OF_UNIT_X_IN_BLK,
	PAFSTAT_F_REORDER_LR_NUM_OF_UNIT_Y_IN_BLK,
	PAFSTAT_F_REORDER_LR_POS_TABLE_0,
	PAFSTAT_F_REORDER_LR_POS_TABLE_1,
	PAFSTAT_F_REORDER_LR_POS_TABLE_2,
	PAFSTAT_F_REORDER_LR_POS_TABLE_3,
	PAFSTAT_F_REORDER_LR_POS_TABLE_4,
	PAFSTAT_F_REORDER_LR_POS_TABLE_5,
	PAFSTAT_F_REORDER_LR_POS_TABLE_6,
	PAFSTAT_F_REORDER_LR_POS_TABLE_7,
	PAFSTAT_F_REORDER_LR_POS_TABLE_8,
	PAFSTAT_F_REORDER_LR_POS_TABLE_9,
	PAFSTAT_F_REORDER_LR_POS_TABLE_10,
	PAFSTAT_F_REORDER_LR_POS_TABLE_11,
	PAFSTAT_F_REORDER_LR_POS_TABLE_12,
	PAFSTAT_F_REORDER_LR_POS_TABLE_13,
	PAFSTAT_F_REORDER_LR_POS_TABLE_14,
	PAFSTAT_F_REORDER_LR_POS_TABLE_15,
	PAFSTAT_F_REORDER_LR_NUM_OF_BLK_IN_LINE,
	PAFSTAT_F_REORDER_LR_NUM_OF_PXL_IN_LINE,
	PAFSTAT_F_REORDER_CRC_SEED,
	PAFSTAT_F_REORDER_CRC_RESULT,
	PAFSTAT_F_LSC_BYPASS,
	PAFSTAT_F_LSC_HDR_MODE,
	PAFSTAT_F_LSC_MIRROR_MODE,
	PAFSTAT_F_LSC_PEDESTAL_EN,
	PAFSTAT_F_LSC_PEDESTAL_CUT,
	PAFSTAT_F_LSC_PEDESTAL_IN,
	PAFSTAT_F_LSC_PEDESTAL_OUT,
	PAFSTAT_F_LSC_START_X,
	PAFSTAT_F_LSC_START_Y,
	PAFSTAT_F_LSC_STEP_X,
	PAFSTAT_F_LSC_STEP_Y,
	PAFSTAT_F_LSC_GAIN_WEIGHT_INF,
	PAFSTAT_F_LSC_GAIN_WEIGHT_MAC,
	PAFSTAT_F_LSC_GAIN_SHIFT,
	PAFSTAT_F_LSC_GAIN_ADDR_0,
	PAFSTAT_F_LSC_GAIN_DATA_0,
	PAFSTAT_F_LSC_GAIN_ADDR_1,
	PAFSTAT_F_LSC_GAIN_DATA_1,
	PAFSTAT_F_LSC_CRC_SEED,
	PAFSTAT_F_LSC_CRC_RESULT,
	PAFSTAT_F_BPC_BYPASS,
	PAFSTAT_F_BPC_STATIC_POS_NUM,
	PAFSTAT_F_BPC_STATIC_POS_ADDR,
	PAFSTAT_F_BPC_STATIC_POS_DATA,
	PAFSTAT_F_BPC_CRC_SEED,
	PAFSTAT_F_BPC_CRC_RESULT,
	PAFSTAT_F_GAMMA_BYPASS,
	PAFSTAT_F_GAMMA_PEDESTAL_CUT,
	PAFSTAT_F_GAMMA_PEDESTAL_EN,
	PAFSTAT_F_GAMMA_PEDESTAL_OUT,
	PAFSTAT_F_GAMMA_PEDESTAL_IN,
	PAFSTAT_F_GAMMA_HDR_MODE,
	PAFSTAT_F_GAMMA_LUT_Y_00,
	PAFSTAT_F_GAMMA_LUT_X_00,
	PAFSTAT_F_GAMMA_LUT_Y_01,
	PAFSTAT_F_GAMMA_LUT_X_01,
	PAFSTAT_F_GAMMA_LUT_Y_02,
	PAFSTAT_F_GAMMA_LUT_X_02,
	PAFSTAT_F_GAMMA_LUT_Y_03,
	PAFSTAT_F_GAMMA_LUT_X_03,
	PAFSTAT_F_GAMMA_LUT_Y_04,
	PAFSTAT_F_GAMMA_LUT_X_04,
	PAFSTAT_F_GAMMA_LUT_Y_05,
	PAFSTAT_F_GAMMA_LUT_X_05,
	PAFSTAT_F_GAMMA_LUT_Y_06,
	PAFSTAT_F_GAMMA_LUT_X_06,
	PAFSTAT_F_GAMMA_LUT_Y_07,
	PAFSTAT_F_GAMMA_LUT_X_07,
	PAFSTAT_F_GAMMA_LUT_Y_08,
	PAFSTAT_F_GAMMA_LUT_X_08,
	PAFSTAT_F_GAMMA_LUT_Y_09,
	PAFSTAT_F_GAMMA_LUT_X_09,
	PAFSTAT_F_GAMMA_LUT_Y_10,
	PAFSTAT_F_GAMMA_LUT_X_10,
	PAFSTAT_F_GAMMA_LUT_Y_11,
	PAFSTAT_F_GAMMA_LUT_X_11,
	PAFSTAT_F_GAMMA_LUT_Y_12,
	PAFSTAT_F_GAMMA_LUT_X_12,
	PAFSTAT_F_GAMMA_LUT_Y_13,
	PAFSTAT_F_GAMMA_LUT_X_13,
	PAFSTAT_F_GAMMA_LUT_Y_14,
	PAFSTAT_F_GAMMA_LUT_X_14,
	PAFSTAT_F_GAMMA_LUT_Y_15,
	PAFSTAT_F_GAMMA_LUT_X_15,
	PAFSTAT_F_GAMMA_LUT_Y_16,
	PAFSTAT_F_GAMMA_LUT_X_16,
	PAFSTAT_F_GAMMA_LUT_Y_17,
	PAFSTAT_F_GAMMA_LUT_X_17,
	PAFSTAT_F_GAMMA_LUT_Y_18,
	PAFSTAT_F_GAMMA_LUT_X_18,
	PAFSTAT_F_GAMMA_LUT_Y_19,
	PAFSTAT_F_GAMMA_LUT_X_19,
	PAFSTAT_F_GAMMA_LUT_Y_20,
	PAFSTAT_F_GAMMA_LUT_X_20,
	PAFSTAT_F_GAMMA_LUT_Y_21,
	PAFSTAT_F_GAMMA_LUT_X_21,
	PAFSTAT_F_GAMMA_LUT_Y_22,
	PAFSTAT_F_GAMMA_LUT_X_22,
	PAFSTAT_F_GAMMA_LUT_Y_23,
	PAFSTAT_F_GAMMA_LUT_X_23,
	PAFSTAT_F_GAMMA_LUT_Y_24,
	PAFSTAT_F_GAMMA_LUT_X_24,
	PAFSTAT_F_GAMMA_LUT_Y_25,
	PAFSTAT_F_GAMMA_LUT_X_25,
	PAFSTAT_F_GAMMA_LUT_Y_26,
	PAFSTAT_F_GAMMA_LUT_X_26,
	PAFSTAT_F_GAMMA_LUT_Y_27,
	PAFSTAT_F_GAMMA_LUT_X_27,
	PAFSTAT_F_GAMMA_LUT_Y_28,
	PAFSTAT_F_GAMMA_LUT_X_28,
	PAFSTAT_F_GAMMA_LUT_Y_29,
	PAFSTAT_F_GAMMA_LUT_X_29,
	PAFSTAT_F_GAMMA_LUT_Y_30,
	PAFSTAT_F_GAMMA_LUT_X_30,
	PAFSTAT_F_GAMMA_LUT_Y_31,
	PAFSTAT_F_GAMMA_LUT_X_31,
	PAFSTAT_F_GAMMA_CRC_SEED,
	PAFSTAT_F_GAMMA_CRC_RESULT,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_00,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_00,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_01,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_01,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_02,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_02,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_03,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_03,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_04,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_04,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_05,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_05,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_06,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_06,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_07,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_07,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_08,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_08,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_09,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_09,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_10,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_10,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_11,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_11,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_12,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_12,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_13,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_13,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_14,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_14,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_15,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_15,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_16,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_16,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_17,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_17,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_18,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_18,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_19,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_19,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_20,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_20,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_21,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_21,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_22,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_22,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_23,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_23,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_24,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_24,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_25,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_25,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_26,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_26,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_27,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_27,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_28,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_28,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_29,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_29,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_30,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_30,
	PAFSTAT_F_GAMMA_LUT_SHORT_Y_31,
	PAFSTAT_F_GAMMA_LUT_SHORT_X_31,
	PAFSTAT_F_STAT_BYPASS,
	PAFSTAT_F_STAT_HDR_MODE,
	PAFSTAT_F_STAT_PAD_EXPAND,
	PAFSTAT_F_STAT_UPSAMPLE_BYPASS,
	PAFSTAT_F_STAT_UPSAMPLE_RATIO,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_0_0,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_0_1,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_0_2,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_0_3,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_0_4,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_0_5,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_0_6,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_0_7,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_1_0,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_1_1,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_1_2,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_1_3,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_1_4,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_1_5,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_1_6,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_1_7,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_2_0,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_2_1,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_2_2,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_2_3,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_2_4,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_2_5,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_2_6,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_2_7,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_3_0,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_3_1,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_3_2,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_3_3,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_3_4,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_3_5,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_3_6,
	PAFSTAT_F_STAT_UPSAMPLE_COEF_3_7,
	PAFSTAT_F_STAT_LPF_BYPASS,
	PAFSTAT_F_STAT_GRAD_BYPASS,
	PAFSTAT_F_STAT_GRAD_LEVEL,
	PAFSTAT_F_STAT_CORR_MATCH_METHOD,
	PAFSTAT_F_STAT_CORR_MAX_DISPARITY,
	PAFSTAT_F_STAT_CORR_LR_ORDER,
	PAFSTAT_F_STAT_CORR_SAT_LEVEL,
	PAFSTAT_F_STAT_FWIN_0_ENABLE,
	PAFSTAT_F_STAT_FWIN_1_ENABLE,
	PAFSTAT_F_STAT_FWIN_2_ENABLE,
	PAFSTAT_F_STAT_FWIN_3_ENABLE,
	PAFSTAT_F_STAT_FWIN_4_ENABLE,
	PAFSTAT_F_STAT_FWIN_5_ENABLE,
	PAFSTAT_F_STAT_FWIN_0_POS_STA_X,
	PAFSTAT_F_STAT_FWIN_0_POS_STA_Y,
	PAFSTAT_F_STAT_FWIN_0_POS_END_X,
	PAFSTAT_F_STAT_FWIN_0_POS_END_Y,
	PAFSTAT_F_STAT_FWIN_1_POS_STA_X,
	PAFSTAT_F_STAT_FWIN_1_POS_STA_Y,
	PAFSTAT_F_STAT_FWIN_1_POS_END_X,
	PAFSTAT_F_STAT_FWIN_1_POS_END_Y,
	PAFSTAT_F_STAT_FWIN_2_POS_STA_X,
	PAFSTAT_F_STAT_FWIN_2_POS_STA_Y,
	PAFSTAT_F_STAT_FWIN_2_POS_END_X,
	PAFSTAT_F_STAT_FWIN_2_POS_END_Y,
	PAFSTAT_F_STAT_FWIN_3_POS_STA_X,
	PAFSTAT_F_STAT_FWIN_3_POS_STA_Y,
	PAFSTAT_F_STAT_FWIN_3_POS_END_X,
	PAFSTAT_F_STAT_FWIN_3_POS_END_Y,
	PAFSTAT_F_STAT_FWIN_4_POS_STA_X,
	PAFSTAT_F_STAT_FWIN_4_POS_STA_Y,
	PAFSTAT_F_STAT_FWIN_4_POS_END_X,
	PAFSTAT_F_STAT_FWIN_4_POS_END_Y,
	PAFSTAT_F_STAT_FWIN_5_POS_STA_X,
	PAFSTAT_F_STAT_FWIN_5_POS_STA_Y,
	PAFSTAT_F_STAT_FWIN_5_POS_END_X,
	PAFSTAT_F_STAT_FWIN_5_POS_END_Y,
	PAFSTAT_F_STAT_SWIN_ENABLE,
	PAFSTAT_F_STAT_SWIN_BLK_NUM_X,
	PAFSTAT_F_STAT_SWIN_BLK_NUM_Y,
	PAFSTAT_F_STAT_SWIN_BLK_SIZE_X,
	PAFSTAT_F_STAT_SWIN_BLK_SIZE_Y,
	PAFSTAT_F_STAT_SWIN_POS_STA_X,
	PAFSTAT_F_STAT_SWIN_POS_STA_Y,
	PAFSTAT_F_STAT_FWIN_0_INTEGRAL_SHIFT,
	PAFSTAT_F_STAT_FWIN_1_INTEGRAL_SHIFT,
	PAFSTAT_F_STAT_FWIN_2_INTEGRAL_SHIFT,
	PAFSTAT_F_STAT_FWIN_3_INTEGRAL_SHIFT,
	PAFSTAT_F_STAT_FWIN_4_INTEGRAL_SHIFT,
	PAFSTAT_F_STAT_FWIN_5_INTEGRAL_SHIFT,
	PAFSTAT_F_STAT_FWIN_0_LPF_COEF0,
	PAFSTAT_F_STAT_FWIN_0_LPF_COEF1,
	PAFSTAT_F_STAT_FWIN_0_LPF_COEF2,
	PAFSTAT_F_STAT_FWIN_0_LPF_COEF3,
	PAFSTAT_F_STAT_FWIN_1_LPF_COEF0,
	PAFSTAT_F_STAT_FWIN_1_LPF_COEF1,
	PAFSTAT_F_STAT_FWIN_1_LPF_COEF2,
	PAFSTAT_F_STAT_FWIN_1_LPF_COEF3,
	PAFSTAT_F_STAT_FWIN_2_LPF_COEF0,
	PAFSTAT_F_STAT_FWIN_2_LPF_COEF1,
	PAFSTAT_F_STAT_FWIN_2_LPF_COEF2,
	PAFSTAT_F_STAT_FWIN_2_LPF_COEF3,
	PAFSTAT_F_STAT_FWIN_3_LPF_COEF0,
	PAFSTAT_F_STAT_FWIN_3_LPF_COEF1,
	PAFSTAT_F_STAT_FWIN_3_LPF_COEF2,
	PAFSTAT_F_STAT_FWIN_3_LPF_COEF3,
	PAFSTAT_F_STAT_FWIN_4_LPF_COEF0,
	PAFSTAT_F_STAT_FWIN_4_LPF_COEF1,
	PAFSTAT_F_STAT_FWIN_4_LPF_COEF2,
	PAFSTAT_F_STAT_FWIN_4_LPF_COEF3,
	PAFSTAT_F_STAT_FWIN_5_LPF_COEF0,
	PAFSTAT_F_STAT_FWIN_5_LPF_COEF1,
	PAFSTAT_F_STAT_FWIN_5_LPF_COEF2,
	PAFSTAT_F_STAT_FWIN_5_LPF_COEF3,
	PAFSTAT_F_STAT_FWIN_0_LPF_COEF_SHIFT,
	PAFSTAT_F_STAT_FWIN_1_LPF_COEF_SHIFT,
	PAFSTAT_F_STAT_FWIN_2_LPF_COEF_SHIFT,
	PAFSTAT_F_STAT_FWIN_3_LPF_COEF_SHIFT,
	PAFSTAT_F_STAT_FWIN_4_LPF_COEF_SHIFT,
	PAFSTAT_F_STAT_FWIN_5_LPF_COEF_SHIFT,
	PAFSTAT_F_STAT_FWIN_0_GRAD_COEF0,
	PAFSTAT_F_STAT_FWIN_0_GRAD_COEF1,
	PAFSTAT_F_STAT_FWIN_0_GRAD_COEF2,
	PAFSTAT_F_STAT_FWIN_0_GRAD_COEF3,
	PAFSTAT_F_STAT_FWIN_1_GRAD_COEF0,
	PAFSTAT_F_STAT_FWIN_1_GRAD_COEF1,
	PAFSTAT_F_STAT_FWIN_1_GRAD_COEF2,
	PAFSTAT_F_STAT_FWIN_1_GRAD_COEF3,
	PAFSTAT_F_STAT_FWIN_2_GRAD_COEF0,
	PAFSTAT_F_STAT_FWIN_2_GRAD_COEF1,
	PAFSTAT_F_STAT_FWIN_2_GRAD_COEF2,
	PAFSTAT_F_STAT_FWIN_2_GRAD_COEF3,
	PAFSTAT_F_STAT_FWIN_3_GRAD_COEF0,
	PAFSTAT_F_STAT_FWIN_3_GRAD_COEF1,
	PAFSTAT_F_STAT_FWIN_3_GRAD_COEF2,
	PAFSTAT_F_STAT_FWIN_3_GRAD_COEF3,
	PAFSTAT_F_STAT_FWIN_4_GRAD_COEF0,
	PAFSTAT_F_STAT_FWIN_4_GRAD_COEF1,
	PAFSTAT_F_STAT_FWIN_4_GRAD_COEF2,
	PAFSTAT_F_STAT_FWIN_4_GRAD_COEF3,
	PAFSTAT_F_STAT_FWIN_5_GRAD_COEF0,
	PAFSTAT_F_STAT_FWIN_5_GRAD_COEF1,
	PAFSTAT_F_STAT_FWIN_5_GRAD_COEF2,
	PAFSTAT_F_STAT_FWIN_5_GRAD_COEF3,
	PAFSTAT_F_STAT_FWIN_0_GRAD_COEF_SHIFT,
	PAFSTAT_F_STAT_FWIN_1_GRAD_COEF_SHIFT,
	PAFSTAT_F_STAT_FWIN_2_GRAD_COEF_SHIFT,
	PAFSTAT_F_STAT_FWIN_3_GRAD_COEF_SHIFT,
	PAFSTAT_F_STAT_FWIN_4_GRAD_COEF_SHIFT,
	PAFSTAT_F_STAT_FWIN_5_GRAD_COEF_SHIFT,
	PAFSTAT_F_STAT_SWIN_INTEGRAL_SHIFT,
	PAFSTAT_F_STAT_SWIN_LPF_COEF0,
	PAFSTAT_F_STAT_SWIN_LPF_COEF1,
	PAFSTAT_F_STAT_SWIN_LPF_COEF2,
	PAFSTAT_F_STAT_SWIN_LPF_COEF3,
	PAFSTAT_F_STAT_SWIN_LPF_COEF_SHIFT,
	PAFSTAT_F_STAT_SWIN_GRAD_COEF0,
	PAFSTAT_F_STAT_SWIN_GRAD_COEF1,
	PAFSTAT_F_STAT_SWIN_GRAD_COEF2,
	PAFSTAT_F_STAT_SWIN_GRAD_COEF3,
	PAFSTAT_F_STAT_SWIN_GRAD_COEF_SHIFT,
	PAFSTAT_F_STAT_FWIN_0_CORR_SHIFT,
	PAFSTAT_F_STAT_FWIN_1_CORR_SHIFT,
	PAFSTAT_F_STAT_FWIN_2_CORR_SHIFT,
	PAFSTAT_F_STAT_FWIN_3_CORR_SHIFT,
	PAFSTAT_F_STAT_FWIN_4_CORR_SHIFT,
	PAFSTAT_F_STAT_FWIN_5_CORR_SHIFT,
	PAFSTAT_F_STAT_SWIN_CORR_SHIFT,
	PAFSTAT_F_STAT_RESULT_OUT_FW0_START_ADDR,
	PAFSTAT_F_STAT_RESULT_OUT_FW0_ACCESS,
	PAFSTAT_F_STAT_RESULT_OUT_FW1_START_ADDR,
	PAFSTAT_F_STAT_RESULT_OUT_FW1_ACCESS,
	PAFSTAT_F_STAT_RESULT_OUT_FW2_START_ADDR,
	PAFSTAT_F_STAT_RESULT_OUT_FW2_ACCESS,
	PAFSTAT_F_STAT_RESULT_OUT_FW3_START_ADDR,
	PAFSTAT_F_STAT_RESULT_OUT_FW3_ACCESS,
	PAFSTAT_F_STAT_RESULT_OUT_FW4_START_ADDR,
	PAFSTAT_F_STAT_RESULT_OUT_FW4_ACCESS,
	PAFSTAT_F_STAT_RESULT_OUT_FW5_START_ADDR,
	PAFSTAT_F_STAT_RESULT_OUT_FW5_ACCESS,
	PAFSTAT_F_STAT_FWIN_INTEGRAL_CRC_SEED,
	PAFSTAT_F_STAT_FWIN_INTEGRAL_CRC_RESULT,
	PAFSTAT_F_STAT_FWIN_UPSAMPLE_CRC_SEED,
	PAFSTAT_F_STAT_FWIN_UPSAMPLE_CRC_RESULT,
	PAFSTAT_F_STAT_FWIN_LPF_CRC_SEED,
	PAFSTAT_F_STAT_FWIN_LPF_CRC_RESULT,
	PAFSTAT_F_STAT_FWIN_GRAD_CRC_SEED,
	PAFSTAT_F_STAT_FWIN_GRAD_CRC_RESULT,
	PAFSTAT_F_STAT_SWIN_INTEGRAL_CRC_SEED,
	PAFSTAT_F_STAT_SWIN_INTEGRAL_CRC_RESULT,
	PAFSTAT_F_STAT_SWIN_UPSAMPLE_CRC_SEED,
	PAFSTAT_F_STAT_SWIN_UPSAMPLE_CRC_RESULT,
	PAFSTAT_F_STAT_SWIN_LPF_CRC_SEED,
	PAFSTAT_F_STAT_SWIN_LPF_CRC_RESULT,
	PAFSTAT_F_STAT_SWIN_GRAD_CRC_SEED,
	PAFSTAT_F_STAT_SWIN_GRAD_CRC_RESULT,
	PAFSTAT_F_AFIDENT_BYPASS,
	PAFSTAT_F_AFIDENT_START_ACTIVE_X,
	PAFSTAT_F_AFIDENT_START_ACTIVE_Y,
	PAFSTAT_F_AFIDENT_ACTIVE_WIDTH,
	PAFSTAT_F_AFIDENT_ACTIVE_HEIGHT,
	PAFSTAT_F_AFIDENT_UNIT_OFFSET_X,
	PAFSTAT_F_AFIDENT_UNIT_OFFSET_Y,
	PAFSTAT_F_AFIDENT_RELATIVE_OFFSET_X,
	PAFSTAT_F_AFIDENT_RELATIVE_OFFSET_Y,
	PAFSTAT_F_AFIDENT_OUTPUT_TYPE0,
	PAFSTAT_F_AFIDENT_BLOCKS_PER_ACTIVE_X,
	PAFSTAT_F_AFIDENT_BLOCKS_PER_ACTIVE_Y,
	PAFSTAT_F_AFIDENT_DATA_IN_TAIL,
	PAFSTAT_F_AFIDENT_TAIL_START,
	PAFSTAT_F_AFIDENT_TAIL_SPLIT,
	PAFSTAT_F_AFIDENT_BLOCKS_FIRST_SPLIT_TAIL,
	PAFSTAT_F_AFIDENT_BLOCKS_SECOND_SPLIT_TAIL,
	PAFSTAT_F_AFIDENT_UNIT_SIZE_X,
	PAFSTAT_F_AFIDENT_UNIT_SIZE_Y,
	PAFSTAT_F_AFIDENT_PTRN_X_0_1,
	PAFSTAT_F_AFIDENT_PTRN_X_0_0,
	PAFSTAT_F_AFIDENT_PTRN_X_1_1,
	PAFSTAT_F_AFIDENT_PTRN_X_1_0,
	PAFSTAT_F_AFIDENT_PTRN_X_2_1,
	PAFSTAT_F_AFIDENT_PTRN_X_2_0,
	PAFSTAT_F_AFIDENT_PTRN_X_3_1,
	PAFSTAT_F_AFIDENT_PTRN_X_3_0,
	PAFSTAT_F_AFIDENT_PTRN_X_4_1,
	PAFSTAT_F_AFIDENT_PTRN_X_4_0,
	PAFSTAT_F_AFIDENT_PTRN_X_5_1,
	PAFSTAT_F_AFIDENT_PTRN_X_5_0,
	PAFSTAT_F_AFIDENT_PTRN_X_6_1,
	PAFSTAT_F_AFIDENT_PTRN_X_6_0,
	PAFSTAT_F_AFIDENT_PTRN_X_7_1,
	PAFSTAT_F_AFIDENT_PTRN_X_7_0,
	PAFSTAT_F_AFIDENT_PTRN_Y_0_1,
	PAFSTAT_F_AFIDENT_PTRN_Y_0_0,
	PAFSTAT_F_AFIDENT_PTRN_Y_1_1,
	PAFSTAT_F_AFIDENT_PTRN_Y_1_0,
	PAFSTAT_F_AFIDENT_PTRN_Y_2_1,
	PAFSTAT_F_AFIDENT_PTRN_Y_2_0,
	PAFSTAT_F_AFIDENT_PTRN_Y_3_1,
	PAFSTAT_F_AFIDENT_PTRN_Y_3_0,
	PAFSTAT_F_AFIDENT_PTRN_Y_4_1,
	PAFSTAT_F_AFIDENT_PTRN_Y_4_0,
	PAFSTAT_F_AFIDENT_PTRN_Y_5_1,
	PAFSTAT_F_AFIDENT_PTRN_Y_5_0,
	PAFSTAT_F_AFIDENT_PTRN_Y_6_1,
	PAFSTAT_F_AFIDENT_PTRN_Y_6_0,
	PAFSTAT_F_AFIDENT_PTRN_Y_7_1,
	PAFSTAT_F_AFIDENT_PTRN_Y_7_0,
	PAFSTAT_F_AFIDENT_UNITS_PER_BLOCK_X,
	PAFSTAT_F_AFIDENT_UNITS_PER_BLOCK_Y,
	PAFSTAT_F_AFIDENT_PTRN_TYPE_0_3,
	PAFSTAT_F_AFIDENT_PTRN_TYPE_0_2,
	PAFSTAT_F_AFIDENT_PTRN_TYPE_0_1,
	PAFSTAT_F_AFIDENT_PTRN_TYPE_0_0,
	PAFSTAT_F_AFIDENT_PTRN_TYPE_0_7,
	PAFSTAT_F_AFIDENT_PTRN_TYPE_0_6,
	PAFSTAT_F_AFIDENT_PTRN_TYPE_0_5,
	PAFSTAT_F_AFIDENT_PTRN_TYPE_0_4,
	PAFSTAT_F_AFIDENT_PTRN_TYPE_0_11,
	PAFSTAT_F_AFIDENT_PTRN_TYPE_0_10,
	PAFSTAT_F_AFIDENT_PTRN_TYPE_0_9,
	PAFSTAT_F_AFIDENT_PTRN_TYPE_0_8,
	PAFSTAT_F_AFIDENT_PTRN_TYPE_0_15,
	PAFSTAT_F_AFIDENT_PTRN_TYPE_0_14,
	PAFSTAT_F_AFIDENT_PTRN_TYPE_0_13,
	PAFSTAT_F_AFIDENT_PTRN_TYPE_0_12,
	PAFSTAT_F_AFIDENT_SWITCHED_PTRN_0_15,
	PAFSTAT_F_AFIDENT_SWITCHED_PTRN_0_14,
	PAFSTAT_F_AFIDENT_SWITCHED_PTRN_0_13,
	PAFSTAT_F_AFIDENT_SWITCHED_PTRN_0_12,
	PAFSTAT_F_AFIDENT_SWITCHED_PTRN_0_11,
	PAFSTAT_F_AFIDENT_SWITCHED_PTRN_0_10,
	PAFSTAT_F_AFIDENT_SWITCHED_PTRN_0_9,
	PAFSTAT_F_AFIDENT_SWITCHED_PTRN_0_8,
	PAFSTAT_F_AFIDENT_SWITCHED_PTRN_0_7,
	PAFSTAT_F_AFIDENT_SWITCHED_PTRN_0_6,
	PAFSTAT_F_AFIDENT_SWITCHED_PTRN_0_5,
	PAFSTAT_F_AFIDENT_SWITCHED_PTRN_0_4,
	PAFSTAT_F_AFIDENT_SWITCHED_PTRN_0_3,
	PAFSTAT_F_AFIDENT_SWITCHED_PTRN_0_2,
	PAFSTAT_F_AFIDENT_SWITCHED_PTRN_0_1,
	PAFSTAT_F_AFIDENT_SWITCHED_PTRN_0_0,
	PAFSTAT_F_AFIDENT_RATE_CNTRL_EN,
	PAFSTAT_F_AFIDENT_PIXELS_GAP2,
	PAFSTAT_F_AFIDENT_PIXELS_GAP1,
	PAFSTAT_F_AFIDENT_REG_INTERFACE_VER,
	PAFSTAT_F_AFIDENT_BLOCK_ID_CODE,
	PAFSTAT_F_AFIDENT_VERSION_ID_CODE,
	PAFSTAT_F_AFIDENT_CRC_RESULT,
	PAFSTAT_F_AFIDENT_CRC_SEED,
	PAFSTAT_F_LBCTRL_BYPASS,
	PAFSTAT_F_LBCTRL_IMG_HEIGHT,
	PAFSTAT_F_LBCTRL_IMG_WIDTH,
	PAFSTAT_F_LBCTRL_BPC_MODE,
	PAFSTAT_REG_FIELD_CNT
};

static struct fimc_is_field pafstat_fields[PAFSTAT_REG_FIELD_CNT] = {
	/* field_name, start_bit, bit_width, type, reset */
	{"COM_QACTIVE_SET", 0, 1, RW, 0x0}, /* COM_QACTIVE_SET */
	{"COM_RESET_REQ", 0, 1, RW, 0x0},	/* COM_RESET_REQ */
	{"COM_RESET_REQ_BUSY", 0, 2, RWI, 0x0}, /* COM_RESET_REQ_BUSY */
	{"COM_DMA_FLUSH_REQ", 0, 2, RIW, 0x0},	/* COM_DMA_FLUSH_REQ */
	{"COM_DMA_FLUSH_REQ_BUSY", 0, 2, RWI, 0x0}, /* COM_DMA_FLUSH_REQ_BUSY */
	{"COM_3AA_STALL_ENABLE", 0, 1, RW, 0x0},	/* COM_3AA_STALL_ENABLE */
	{"COM_LIC_MODE", 0, 1, RW, 0x0},	/* COM_LIC_MODE */
	{"COM_LIC_BYPASS", 0, 1, RW, 0x0},	/* COM_LIC_BYPASS */
	{"COM_LIC_SEL_SINGLE_INPUT", 0, 2, RW, 0x0},	/* COM_LIC_SEL_SINGLE_INPUT */
	{"COM_SUB_STALL", 0, 10, RWI, 0x0}, /* COM_SUB_STALL */
	{"COM_SUB_BUSY", 0, 10, RWI, 0x0},	/* COM_SUB_BUSY */
	{"COM_SUB_DVALID", 0, 10, RWI, 0x0},	/* COM_SUB_DVALID */
	{"COM_HBLANK_CYCLE", 0, 7, RW, 0x0},	/* COM_HBLANK_CYCLE */
	{"COM_DISABLE_OUTPUTMASK", 0, 1, RW, 0x0},	/* COM_DISABLE_OUTPUTMASK */
	{"COM_FRAME_NUM", 0, 3, RW, 0x0},	/* COM_FRAME_NUM */
	{"COM_FRAME_NUM_STAT", 0, 3, RW, 0x0},	/* COM_FRAME_NUM_STAT */
	{"COM_FRAME_NUM_MED_INT", 0, 3, RW, 0x0},	/* COM_FRAME_NUM_MED_INT */
	{"COM_FRAME_CNT", 0, 3, RWI, 0x0},	/* COM_FRAME_CNT */
	{"COM_FRAME_STATUS", 0, 8, RWI, 0x0},	/* COM_FRAME_STATUS */
	{"COM_VERSION", 0, 32, RWI, 0x10000},	/* COM_VERSION */
	{"CTX_GLOBAL_ENABLE", 0, 1, RW, 0x0},	/* CTX_GLOBAL_ENABLE */
	{"CTX_ONESHOT", 0, 1, RIW, 0x0},	/* CTX_ONESHOT */
	{"CTX_SEL_OTF", 0, 1, RIW, 0x0},	/* CTX_SEL_OTF */
	{"CTX_INTERRUPT_SRC", 0, 32, RW, 0x0},	/* CTX_INTERRUPT_SRC */
	{"CTX_INTERRUPT_MASK", 0, 32, RW, 0x0}, /* CTX_INTERRUPT_MASK */
	{"CTX_TIMEOUT_CNT_INIT", 0, 1, RW, 0x0},	/* CTX_TIMEOUT_CNT_INIT */
	{"CTX_TIMEOUT_CNT_VAL", 0, 32, RW, 0xffffffff}, /* CTX_TIMEOUT_CNT_MAX */
	{"CTX_SENSOR_MODE", 0, 3, RW, 0x0}, /* CTX_SENSOR_MODE */
	{"CTX_CURRENT_USE_A", 0, 1, RWI, 0x1},	/* CTX_CURRENT_USE_A */
	{"CTX_LINE_NUM_MED_INT", 0, 13, RW, 0x1fff},	/* CTX_LINE_NUM_MED_INT */
	{"CTX_INPUT_WIDTH", 0, 13, RW, 0x0},	/* CTX_INPUT_WIDTH */
	{"CTX_INPUT_HEIGHT", 0, 13, RW, 0x0},	/* CTX_INPUT_HEIGHT */
	{"CTX_PD_PXL_WIDTH", 0, 10, RW, 0x0},	/* CTX_PD_PXL_WIDTH */
	{"CTX_PD_PXL_HEIGHT", 0, 11, RW, 0x0},	/* CTX_PD_PXL_HEIGHT */
	{"CTX_CLK_CTRL", 0, 32, RW, 0x0},	/* CTX_CLK_CTRL */
	{"CTX_LIC_IS_DMA", 0, 1, RW, 0x0},	/* CTX_LIC_IS_DMA */
	{"CTX_SFR_READY", 0, 1, RW, 0x0},	/* CTX_SFR_READY */
	{"CTX_LIC_4PPC", 0, 1, RW, 0x0},	/* CTX_LIC_4PPC */
	{"YEXTR_HDRMODE", 0, 1, RW, 0x0},	/* PAFSTAT_YEXTR_HDRMODE */
	{"YEXTR_MAXNOSKIPPXG", 0, 2, RW, 0x0},	/* PAFSTAT_YEXTR_MAXNOSKIPPXG */
	{"YEXTR_SKIPLEVELTH", 0, 10, RW, 0x0},	/* PAFSTAT_YEXTR_SKIPLEVELTH */
	{"YEXTR_SATVALUEG", 0, 10, RW, 0x0},	/* PAFSTAT_YEXTR_SATVALUEG */
	{"YEXTR_SATVALUER", 0, 10, RW, 0x0},	/* PAFSTAT_YEXTR_SATVALUER */
	{"YEXTR_SATVALUEB", 0, 10, RW, 0x0},	/* PAFSTAT_YEXTR_SATVALUEB */
	{"YEXTR_NUMOFSATG", 0, 2, RW, 0x0}, /* PAFSTAT_YEXTR_NUMOFSATG */
	{"YEXTR_NUMOFSATR", 0, 1, RW, 0x0}, /* PAFSTAT_YEXTR_NUMOFSATR */
	{"YEXTR_NUMOFSATB", 0, 1, RW, 0x0}, /* PAFSTAT_YEXTR_NUMOFSATB */
	{"YEXTR_SATVALSUMOFG", 0, 12, RW, 0x0}, /* PAFSTAT_YEXTR_SATVALSUMOFG */
	{"YEXTR_SATVALSUMOFR", 0, 11, RW, 0x0}, /* PAFSTAT_YEXTR_SATVALSUMOFR */
	{"YEXTR_SATVALSUMOFB", 0, 11, RW, 0x0}, /* PAFSTAT_YEXTR_SATVALSUMOFB */
	{"YEXTR_CLIPVALLEFT", 0, 10, RW, 0x0},	/* PAFSTAT_YEXTR_CLIPVALLEFT */
	{"YEXTR_CLIPVALRIGHT", 0, 10, RW, 0x0}, /* PAFSTAT_YEXTR_CLIPVALRIGHT */
	{"YEXTR_COEFG", 0, 10, RW, 0x0},	/* PAFSTAT_YEXTR_COEFG */
	{"YEXTR_COEFR", 0, 10, RW, 0x0},	/* PAFSTAT_YEXTR_COEFR */
	{"YEXTR_COEFB", 0, 10, RW, 0x0},	/* PAFSTAT_YEXTR_COEFB */
	{"YEXTR_YSHIFT", 0, 4, RW, 0x0},	/* PAFSTAT_YEXTR_YSHIFT */
	{"YEXTR_COEFG_SHORT", 0, 10, RW, 0x0},	/* PAFSTAT_YEXTR_COEFG_SHORT */
	{"YEXTR_COEFR_SHORT", 0, 10, RW, 0x0},	/* PAFSTAT_YEXTR_COEFR_SHORT */
	{"YEXTR_COEFB_SHORT", 0, 10, RW, 0x0},	/* PAFSTAT_YEXTR_COEFB_SHORT */
	{"YEXTR_CRC_RESULT", 16, 8, RWI, 0x0},	/* PAFSTAT_YEXTR_CRC */
	{"YEXTR_CRC_SEED", 0, 8, RW, 0x0},	/* PAFSTAT_YEXTR_CRC */
	{"BIN_BYPASS", 0, 1, RW, 0x0},	/* PAFSTAT_BIN_BYPASS */
	{"BIN_HDR_MODE", 4, 1, RW, 0x0},	/* PAFSTAT_BIN_CONFIG */
	{"BIN_MODE", 0, 1, RW, 0x0},	/* PAFSTAT_BIN_CONFIG */
	{"BIN_IMG_HEIGHT", 16, 14, RW, 0x0},	/* PAFSTAT_BIN_IMAGE_SIZE */
	{"BIN_IMG_WIDTH", 0, 14, RW, 0x0},	/* PAFSTAT_BIN_IMAGE_SIZE */
	{"BIN_COEF_3", 24, 8, RW, 0x0}, /* PAFSTAT_BIN_COEF_0 */
	{"BIN_COEF_2", 16, 8, RW, 0x0}, /* PAFSTAT_BIN_COEF_0 */
	{"BIN_COEF_1", 8, 8, RW, 0x0},	/* PAFSTAT_BIN_COEF_0 */
	{"BIN_COEF_0", 0, 8, RW, 0x0},	/* PAFSTAT_BIN_COEF_0 */
	{"BIN_COEF_6", 16, 8, RW, 0x0}, /* PAFSTAT_BIN_COEF_1 */
	{"BIN_COEF_5", 8, 8, RW, 0x0},	/* PAFSTAT_BIN_COEF_1 */
	{"BIN_COEF_4", 0, 8, RW, 0x0},	/* PAFSTAT_BIN_COEF_1 */
	{"BIN_CRC_SEED", 0, 8, RW, 0x0},	/* PAFSTAT_BIN_CRC_SEED */
	{"BIN_CRC_RESULT", 0, 8, RWI, 0x0}, /* PAFSTAT_BIN_CRC_RESULT */
	{"REORDER_BYPASS", 0, 1, RW, 0x0},	/* PAFSTAT_REORDER_BYPASS */
	{"REORDER_ACTIVE_STA_X", 0, 13, RW, 0x0},	/* PAFSTAT_REORDER_ACTIVE_STA_X */
	{"REORDER_ACTIVE_STA_Y", 0, 13, RW, 0x0},	/* PAFSTAT_REORDER_ACTIVE_STA_Y */
	{"REORDER_ACTIVE_SIZE_X", 0, 13, RW, 0x0},	/* PAFSTAT_REORDER_ACTIVE_SIZE_X */
	{"REORDER_ACTIVE_SIZE_Y", 0, 13, RW, 0x0},	/* PAFSTAT_REORDER_ACTIVE_SIZE_Y */
	{"REORDER_UNIT_SIZE_X", 0, 6, RW, 0x0}, /* PAFSTAT_REORDER_UNIT_SIZE_X */
	{"REORDER_UNIT_SIZE_Y", 0, 6, RW, 0x0}, /* PAFSTAT_REORDER_UNIT_SIZE_Y */
	{"REORDER_UNIT_NUM_X", 0, 13, RW, 0x0}, /* PAFSTAT_REORDER_NUM_OF_UNIT_X */
	{"REORDER_UNIT_NUM_Y", 0, 13, RW, 0x0}, /* PAFSTAT_REORDER_NUM_OF_UNIT_Y */
	{"REORDER_LR_INDC_FLAG_MODE", 0, 2, RW, 0x0},	/* PAFSTAT_REORDER_LR_INDC_FLAG_MODE */
	{"REORDER_LR_POS_ENABLE", 0, 1, RW, 0x0},	/* PAFSTAT_REORDER_LR_POS_ENABLE */
	{"REORDER_LR_NUM_OF_UNIT_X_IN_BLK", 0, 5, RW, 0x0}, /* PAFSTAT_REORDER_LR_NUM_OF_UNIT_X_IN_BLK */
	{"REORDER_LR_NUM_OF_UNIT_Y_IN_BLK", 0, 5, RW, 0x0}, /* PAFSTAT_REORDER_LR_NUM_OF_UNIT_Y_IN_BLK */
	{"REORDER_LR_POS_TABLE_0", 0, 10, RW, 0x0}, /* PAFSTAT_REORDER_LR_POS_TABLE_0 */
	{"REORDER_LR_POS_TABLE_1", 0, 10, RW, 0x0}, /* PAFSTAT_REORDER_LR_POS_TABLE_1 */
	{"REORDER_LR_POS_TABLE_2", 0, 10, RW, 0x0}, /* PAFSTAT_REORDER_LR_POS_TABLE_2 */
	{"REORDER_LR_POS_TABLE_3", 0, 10, RW, 0x0}, /* PAFSTAT_REORDER_LR_POS_TABLE_3 */
	{"REORDER_LR_POS_TABLE_4", 0, 10, RW, 0x0}, /* PAFSTAT_REORDER_LR_POS_TABLE_4 */
	{"REORDER_LR_POS_TABLE_5", 0, 10, RW, 0x0}, /* PAFSTAT_REORDER_LR_POS_TABLE_5 */
	{"REORDER_LR_POS_TABLE_6", 0, 10, RW, 0x0}, /* PAFSTAT_REORDER_LR_POS_TABLE_6 */
	{"REORDER_LR_POS_TABLE_7", 0, 10, RW, 0x0}, /* PAFSTAT_REORDER_LR_POS_TABLE_7 */
	{"REORDER_LR_POS_TABLE_8", 0, 10, RW, 0x0}, /* PAFSTAT_REORDER_LR_POS_TABLE_8 */
	{"REORDER_LR_POS_TABLE_9", 0, 10, RW, 0x0}, /* PAFSTAT_REORDER_LR_POS_TABLE_9 */
	{"REORDER_LR_POS_TABLE_10", 0, 10, RW, 0x0},	/* PAFSTAT_REORDER_LR_POS_TABLE_10 */
	{"REORDER_LR_POS_TABLE_11", 0, 10, RW, 0x0},	/* PAFSTAT_REORDER_LR_POS_TABLE_11 */
	{"REORDER_LR_POS_TABLE_12", 0, 10, RW, 0x0},	/* PAFSTAT_REORDER_LR_POS_TABLE_12 */
	{"REORDER_LR_POS_TABLE_13", 0, 10, RW, 0x0},	/* PAFSTAT_REORDER_LR_POS_TABLE_13 */
	{"REORDER_LR_POS_TABLE_14", 0, 10, RW, 0x0},	/* PAFSTAT_REORDER_LR_POS_TABLE_14 */
	{"REORDER_LR_POS_TABLE_15", 0, 10, RW, 0x0},	/* PAFSTAT_REORDER_LR_POS_TABLE_15 */
	{"REORDER_LR_NUM_OF_BLK_IN_LINE", 0, 10, RW, 0x0},	/* PAFSTAT_REORDER_LR_NUM_OF_BLK_IN_LINE */
	{"REORDER_LR_NUM_OF_PXL_IN_LINE", 0, 5, RW, 0x0},	/* PAFSTAT_REORDER_LR_NUM_OF_PXL_IN_LINE */
	{"REORDER_CRC_SEED", 0, 8, RW, 0x0},	/* PAFSTAT_REORDER_CRC_SEED */
	{"REORDER_CRC_RESULT", 0, 8, RWI, 0x0}, /* PAFSTAT_REORDER_CRC_RESULT */
	{"LSC_BYPASS", 0, 1, RW, 0x0},	/* PAFSTAT_LSC_BYPASS */
	{"LSC_HDR_MODE", 0, 1, RW, 0x0},	/* PAFSTAT_LSC_HDR_MODE */
	{"LSC_MIRROR_MODE", 0, 2, RW, 0x0}, /* PAFSTAT_LSC_MIRROR_MODE */
	{"LSC_PEDESTAL_EN", 0, 1, RW, 0x0}, /* PAFSTAT_LSC_PEDESTAL_EN */
	{"LSC_PEDESTAL_CUT", 0, 1, RW, 0x0},	/* PAFSTAT_LSC_PEDESTAL_CUT */
	{"LSC_PEDESTAL_IN", 0, 10, RW, 0x0},	/* PAFSTAT_LSC_PEDESTAL_IN */
	{"LSC_PEDESTAL_OUT", 0, 10, RW, 0x0},	/* PAFSTAT_LSC_PEDESTAL_OUT */
	{"LSC_START_X", 0, 24, RW, 0x0},	/* PAFSTAT_LSC_START_X */
	{"LSC_START_Y", 0, 24, RW, 0x0},	/* PAFSTAT_LSC_START_Y */
	{"LSC_STEP_X", 0, 20, RW, 0x0}, /* PAFSTAT_LSC_STEP_X */
	{"LSC_STEP_Y", 0, 20, RW, 0x0}, /* PAFSTAT_LSC_STEP_Y */
	{"LSC_GAIN_WEIGHT_INF", 0, 13, RW, 0x0},	/* PAFSTAT_LSC_GAIN_WEIGHT_INF */
	{"LSC_GAIN_WEIGHT_MAC", 0, 13, RW, 0x0},	/* PAFSTAT_LSC_GAIN_WEIGHT_MAC */
	{"LSC_GAIN_SHIFT", 0, 4, RW, 0x0},	/* PAFSTAT_LSC_GAIN_SHIFT */
	{"LSC_GAIN_ADDR_0", 0, 8, RW, 0x0}, /* PAFSTAT_LSC_GAIN_ADDR_0 */
	{"LSC_GAIN_DATA_0", 0, 28, RIW, 0x0},	/* PAFSTAT_LSC_GAIN_DATA_0 */
	{"LSC_GAIN_ADDR_1", 0, 8, RW, 0x0}, /* PAFSTAT_LSC_GAIN_ADDR_1 */
	{"LSC_GAIN_DATA_1", 0, 28, RIW, 0x0},	/* PAFSTAT_LSC_GAIN_DATA_1 */
	{"LSC_CRC_SEED", 0, 8, RW, 0x0},	/* PAFSTAT_LSC_CRC_SEED */
	{"LSC_CRC_RESULT", 0, 8, RWI, 0x0}, /* PAFSTAT_LSC_CRC_RESULT */
	{"BPC_BYPASS", 0, 1, RW, 0x0},	/* PAFSTAT_BPC_BYPASS */
	{"BPC_STATIC_POS_NUM", 0, 9, RW, 0x0},	/* PAFSTAT_BPC_POS_NUM */
	{"BPC_STATIC_POS_ADDR", 0, 9, RW, 0x0}, /* PAFSTAT_BPC_STATIC_POS_ADDR */
	{"BPC_STATIC_POS_DATA", 0, 32, RW, 0x0},	/* PAFSTAT_BPC_STATIC_POS_DATA */
	{"BPC_CRC_SEED", 0, 8, RW, 0x0},	/* PAFSTAT_BPC_CRC_SEED */
	{"BPC_CRC_RESULT", 0, 8, RWI, 0x0}, /* PAFSTAT_BPC_CRC_RESULT */
	{"GAMMA_BYPASS", 0, 1, RW, 0x0},	/* PAFSTAT_GAMMA_BYPASS */
	{"GAMMA_PEDESTAL_CUT", 4, 1, RW, 0x0},	/* PAFSTAT_GAMMA_PEDESTAL_EN */
	{"GAMMA_PEDESTAL_EN", 0, 1, RW, 0x0},	/* PAFSTAT_GAMMA_PEDESTAL_EN */
	{"GAMMA_PEDESTAL_OUT", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_PEDESTAL */
	{"GAMMA_PEDESTAL_IN", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_PEDESTAL */
	{"GAMMA_HDR_MODE", 0, 1, RW, 0x0},	/* PAFSTAT_GAMMA_HDR_MODE */
	{"GAMMA_LUT_Y_00", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_00 */
	{"GAMMA_LUT_X_00", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_00 */
	{"GAMMA_LUT_Y_01", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_01 */
	{"GAMMA_LUT_X_01", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_01 */
	{"GAMMA_LUT_Y_02", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_02 */
	{"GAMMA_LUT_X_02", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_02 */
	{"GAMMA_LUT_Y_03", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_03 */
	{"GAMMA_LUT_X_03", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_03 */
	{"GAMMA_LUT_Y_04", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_04 */
	{"GAMMA_LUT_X_04", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_04 */
	{"GAMMA_LUT_Y_05", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_05 */
	{"GAMMA_LUT_X_05", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_05 */
	{"GAMMA_LUT_Y_06", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_06 */
	{"GAMMA_LUT_X_06", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_06 */
	{"GAMMA_LUT_Y_07", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_07 */
	{"GAMMA_LUT_X_07", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_07 */
	{"GAMMA_LUT_Y_08", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_08 */
	{"GAMMA_LUT_X_08", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_08 */
	{"GAMMA_LUT_Y_09", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_09 */
	{"GAMMA_LUT_X_09", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_09 */
	{"GAMMA_LUT_Y_10", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_10 */
	{"GAMMA_LUT_X_10", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_10 */
	{"GAMMA_LUT_Y_11", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_11 */
	{"GAMMA_LUT_X_11", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_11 */
	{"GAMMA_LUT_Y_12", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_12 */
	{"GAMMA_LUT_X_12", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_12 */
	{"GAMMA_LUT_Y_13", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_13 */
	{"GAMMA_LUT_X_13", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_13 */
	{"GAMMA_LUT_Y_14", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_14 */
	{"GAMMA_LUT_X_14", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_14 */
	{"GAMMA_LUT_Y_15", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_15 */
	{"GAMMA_LUT_X_15", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_15 */
	{"GAMMA_LUT_Y_16", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_16 */
	{"GAMMA_LUT_X_16", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_16 */
	{"GAMMA_LUT_Y_17", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_17 */
	{"GAMMA_LUT_X_17", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_17 */
	{"GAMMA_LUT_Y_18", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_18 */
	{"GAMMA_LUT_X_18", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_18 */
	{"GAMMA_LUT_Y_19", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_19 */
	{"GAMMA_LUT_X_19", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_19 */
	{"GAMMA_LUT_Y_20", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_20 */
	{"GAMMA_LUT_X_20", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_20 */
	{"GAMMA_LUT_Y_21", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_21 */
	{"GAMMA_LUT_X_21", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_21 */
	{"GAMMA_LUT_Y_22", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_22 */
	{"GAMMA_LUT_X_22", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_22 */
	{"GAMMA_LUT_Y_23", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_23 */
	{"GAMMA_LUT_X_23", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_23 */
	{"GAMMA_LUT_Y_24", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_24 */
	{"GAMMA_LUT_X_24", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_24 */
	{"GAMMA_LUT_Y_25", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_25 */
	{"GAMMA_LUT_X_25", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_25 */
	{"GAMMA_LUT_Y_26", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_26 */
	{"GAMMA_LUT_X_26", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_26 */
	{"GAMMA_LUT_Y_27", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_27 */
	{"GAMMA_LUT_X_27", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_27 */
	{"GAMMA_LUT_Y_28", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_28 */
	{"GAMMA_LUT_X_28", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_28 */
	{"GAMMA_LUT_Y_29", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_29 */
	{"GAMMA_LUT_X_29", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_29 */
	{"GAMMA_LUT_Y_30", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_30 */
	{"GAMMA_LUT_X_30", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_30 */
	{"GAMMA_LUT_Y_31", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_31 */
	{"GAMMA_LUT_X_31", 0, 10, RW, 0x0}, /* PAFSTAT_GAMMA_LUT_31 */
	{"GAMMA_CRC_SEED", 0, 8, RW, 0x0},	/* PAFSTAT_GAMMA_CRC_SEED */
	{"GAMMA_CRC_RESULT", 0, 8, RWI, 0x0},	/* PAFSTAT_GAMMA_CRC_RESULT */
	{"GAMMA_LUT_SHORT_Y_00", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_00 */
	{"GAMMA_LUT_SHORT_X_00", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_00 */
	{"GAMMA_LUT_SHORT_Y_01", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_01 */
	{"GAMMA_LUT_SHORT_X_01", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_01 */
	{"GAMMA_LUT_SHORT_Y_02", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_02 */
	{"GAMMA_LUT_SHORT_X_02", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_02 */
	{"GAMMA_LUT_SHORT_Y_03", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_03 */
	{"GAMMA_LUT_SHORT_X_03", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_03 */
	{"GAMMA_LUT_SHORT_Y_04", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_04 */
	{"GAMMA_LUT_SHORT_X_04", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_04 */
	{"GAMMA_LUT_SHORT_Y_05", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_05 */
	{"GAMMA_LUT_SHORT_X_05", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_05 */
	{"GAMMA_LUT_SHORT_Y_06", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_06 */
	{"GAMMA_LUT_SHORT_X_06", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_06 */
	{"GAMMA_LUT_SHORT_Y_07", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_07 */
	{"GAMMA_LUT_SHORT_X_07", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_07 */
	{"GAMMA_LUT_SHORT_Y_08", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_08 */
	{"GAMMA_LUT_SHORT_X_08", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_08 */
	{"GAMMA_LUT_SHORT_Y_09", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_09 */
	{"GAMMA_LUT_SHORT_X_09", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_09 */
	{"GAMMA_LUT_SHORT_Y_10", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_10 */
	{"GAMMA_LUT_SHORT_X_10", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_10 */
	{"GAMMA_LUT_SHORT_Y_11", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_11 */
	{"GAMMA_LUT_SHORT_X_11", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_11 */
	{"GAMMA_LUT_SHORT_Y_12", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_12 */
	{"GAMMA_LUT_SHORT_X_12", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_12 */
	{"GAMMA_LUT_SHORT_Y_13", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_13 */
	{"GAMMA_LUT_SHORT_X_13", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_13 */
	{"GAMMA_LUT_SHORT_Y_14", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_14 */
	{"GAMMA_LUT_SHORT_X_14", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_14 */
	{"GAMMA_LUT_SHORT_Y_15", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_15 */
	{"GAMMA_LUT_SHORT_X_15", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_15 */
	{"GAMMA_LUT_SHORT_Y_16", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_16 */
	{"GAMMA_LUT_SHORT_X_16", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_16 */
	{"GAMMA_LUT_SHORT_Y_17", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_17 */
	{"GAMMA_LUT_SHORT_X_17", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_17 */
	{"GAMMA_LUT_SHORT_Y_18", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_18 */
	{"GAMMA_LUT_SHORT_X_18", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_18 */
	{"GAMMA_LUT_SHORT_Y_19", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_19 */
	{"GAMMA_LUT_SHORT_X_19", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_19 */
	{"GAMMA_LUT_SHORT_Y_20", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_20 */
	{"GAMMA_LUT_SHORT_X_20", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_20 */
	{"GAMMA_LUT_SHORT_Y_21", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_21 */
	{"GAMMA_LUT_SHORT_X_21", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_21 */
	{"GAMMA_LUT_SHORT_Y_22", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_22 */
	{"GAMMA_LUT_SHORT_X_22", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_22 */
	{"GAMMA_LUT_SHORT_Y_23", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_23 */
	{"GAMMA_LUT_SHORT_X_23", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_23 */
	{"GAMMA_LUT_SHORT_Y_24", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_24 */
	{"GAMMA_LUT_SHORT_X_24", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_24 */
	{"GAMMA_LUT_SHORT_Y_25", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_25 */
	{"GAMMA_LUT_SHORT_X_25", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_25 */
	{"GAMMA_LUT_SHORT_Y_26", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_26 */
	{"GAMMA_LUT_SHORT_X_26", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_26 */
	{"GAMMA_LUT_SHORT_Y_27", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_27 */
	{"GAMMA_LUT_SHORT_X_27", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_27 */
	{"GAMMA_LUT_SHORT_Y_28", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_28 */
	{"GAMMA_LUT_SHORT_X_28", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_28 */
	{"GAMMA_LUT_SHORT_Y_29", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_29 */
	{"GAMMA_LUT_SHORT_X_29", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_29 */
	{"GAMMA_LUT_SHORT_Y_30", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_30 */
	{"GAMMA_LUT_SHORT_X_30", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_30 */
	{"GAMMA_LUT_SHORT_Y_31", 12, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_31 */
	{"GAMMA_LUT_SHORT_X_31", 0, 10, RW, 0x0},	/* PAFSTAT_GAMMA_LUT_SHORT_31 */
	{"STAT_BYPASS", 0, 1, RW, 0x0}, /* PAFSTAT_STAT_BYPASS */
	{"STAT_HDR_MODE", 0, 1, RW, 0x0},	/* PAFSTAT_STAT_HDR_MODE */
	{"STAT_PAD_EXPAND", 0, 1, RW, 0x0}, /* PAFSTAT_STAT_PAD_EXPAND */
	{"STAT_UPSAMPLE_BYPASS", 0, 1, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_BYPASS */
	{"STAT_UPSAMPLE_RATIO", 0, 1, RW, 0x0}, /* PAFSTAT_STAT_UPSAMPLE_RATIO */
	{"STAT_UPSAMPLE_COEF_0_0", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_0_0 */
	{"STAT_UPSAMPLE_COEF_0_1", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_0_1 */
	{"STAT_UPSAMPLE_COEF_0_2", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_0_2 */
	{"STAT_UPSAMPLE_COEF_0_3", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_0_3 */
	{"STAT_UPSAMPLE_COEF_0_4", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_0_4 */
	{"STAT_UPSAMPLE_COEF_0_5", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_0_5 */
	{"STAT_UPSAMPLE_COEF_0_6", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_0_6 */
	{"STAT_UPSAMPLE_COEF_0_7", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_0_7 */
	{"STAT_UPSAMPLE_COEF_1_0", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_1_0 */
	{"STAT_UPSAMPLE_COEF_1_1", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_1_1 */
	{"STAT_UPSAMPLE_COEF_1_2", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_1_2 */
	{"STAT_UPSAMPLE_COEF_1_3", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_1_3 */
	{"STAT_UPSAMPLE_COEF_1_4", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_1_4 */
	{"STAT_UPSAMPLE_COEF_1_5", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_1_5 */
	{"STAT_UPSAMPLE_COEF_1_6", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_1_6 */
	{"STAT_UPSAMPLE_COEF_1_7", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_1_7 */
	{"STAT_UPSAMPLE_COEF_2_0", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_2_0 */
	{"STAT_UPSAMPLE_COEF_2_1", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_2_1 */
	{"STAT_UPSAMPLE_COEF_2_2", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_2_2 */
	{"STAT_UPSAMPLE_COEF_2_3", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_2_3 */
	{"STAT_UPSAMPLE_COEF_2_4", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_2_4 */
	{"STAT_UPSAMPLE_COEF_2_5", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_2_5 */
	{"STAT_UPSAMPLE_COEF_2_6", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_2_6 */
	{"STAT_UPSAMPLE_COEF_2_7", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_2_7 */
	{"STAT_UPSAMPLE_COEF_3_0", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_3_0 */
	{"STAT_UPSAMPLE_COEF_3_1", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_3_1 */
	{"STAT_UPSAMPLE_COEF_3_2", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_3_2 */
	{"STAT_UPSAMPLE_COEF_3_3", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_3_3 */
	{"STAT_UPSAMPLE_COEF_3_4", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_3_4 */
	{"STAT_UPSAMPLE_COEF_3_5", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_3_5 */
	{"STAT_UPSAMPLE_COEF_3_6", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_3_6 */
	{"STAT_UPSAMPLE_COEF_3_7", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_UPSAMPLE_COEF_3_7 */
	{"STAT_LPF_BYPASS", 0, 1, RW, 0x0}, /* PAFSTAT_STAT_LPF_BYPASS */
	{"STAT_GRAD_BYPASS", 0, 1, RW, 0x0},	/* PAFSTAT_STAT_GRAD_BYPASS */
	{"STAT_GRAD_LEVEL", 0, 15, RW, 0x0},	/* PAFSTAT_STAT_GRAD_LEVEL */
	{"STAT_CORR_MATCH_METHOD", 0, 1, RW, 0x0},	/* PAFSTAT_STAT_CORR_MATCH_METHOD */
	{"STAT_CORR_MAX_DISPARITY", 0, 4, RW, 0x0}, /* PAFSTAT_STAT_CORR_MAX_DISPARITY */
	{"STAT_CORR_LR_ORDER", 0, 1, RW, 0x0},	/* PAFSTAT_STAT_CORR_LR_ORDER */
	{"STAT_CORR_SAT_LEVEL", 0, 10, RW, 0x0},	/* PAFSTAT_STAT_CORR_SAT_LEVEL */
	{"STAT_FWIN_0_ENABLE", 0, 1, RW, 0x0},	/* PAFSTAT_STAT_FWIN_0_ENABLE */
	{"STAT_FWIN_1_ENABLE", 0, 1, RW, 0x0},	/* PAFSTAT_STAT_FWIN_1_ENABLE */
	{"STAT_FWIN_2_ENABLE", 0, 1, RW, 0x0},	/* PAFSTAT_STAT_FWIN_2_ENABLE */
	{"STAT_FWIN_3_ENABLE", 0, 1, RW, 0x0},	/* PAFSTAT_STAT_FWIN_3_ENABLE */
	{"STAT_FWIN_4_ENABLE", 0, 1, RW, 0x0},	/* PAFSTAT_STAT_FWIN_4_ENABLE */
	{"STAT_FWIN_5_ENABLE", 0, 1, RW, 0x0},	/* PAFSTAT_STAT_FWIN_5_ENABLE */
	{"STAT_FWIN_0_POS_STA_X", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_0_POS_STA_X */
	{"STAT_FWIN_0_POS_STA_Y", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_0_POS_STA_Y */
	{"STAT_FWIN_0_POS_END_X", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_0_POS_END_X */
	{"STAT_FWIN_0_POS_END_Y", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_0_POS_END_Y */
	{"STAT_FWIN_1_POS_STA_X", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_1_POS_STA_X */
	{"STAT_FWIN_1_POS_STA_Y", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_1_POS_STA_Y */
	{"STAT_FWIN_1_POS_END_X", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_1_POS_END_X */
	{"STAT_FWIN_1_POS_END_Y", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_1_POS_END_Y */
	{"STAT_FWIN_2_POS_STA_X", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_2_POS_STA_X */
	{"STAT_FWIN_2_POS_STA_Y", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_2_POS_STA_Y */
	{"STAT_FWIN_2_POS_END_X", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_2_POS_END_X */
	{"STAT_FWIN_2_POS_END_Y", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_2_POS_END_Y */
	{"STAT_FWIN_3_POS_STA_X", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_3_POS_STA_X */
	{"STAT_FWIN_3_POS_STA_Y", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_3_POS_STA_Y */
	{"STAT_FWIN_3_POS_END_X", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_3_POS_END_X */
	{"STAT_FWIN_3_POS_END_Y", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_3_POS_END_Y */
	{"STAT_FWIN_4_POS_STA_X", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_4_POS_STA_X */
	{"STAT_FWIN_4_POS_STA_Y", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_4_POS_STA_Y */
	{"STAT_FWIN_4_POS_END_X", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_4_POS_END_X */
	{"STAT_FWIN_4_POS_END_Y", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_4_POS_END_Y */
	{"STAT_FWIN_5_POS_STA_X", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_5_POS_STA_X */
	{"STAT_FWIN_5_POS_STA_Y", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_5_POS_STA_Y */
	{"STAT_FWIN_5_POS_END_X", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_5_POS_END_X */
	{"STAT_FWIN_5_POS_END_Y", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_FWIN_5_POS_END_Y */
	{"STAT_SWIN_ENABLE", 0, 1, RW, 0x0},	/* PAFSTAT_STAT_SWIN_ENABLE */
	{"STAT_SWIN_BLK_NUM_X", 0, 5, RW, 0x0}, /* PAFSTAT_STAT_SWIN_BLK_NUM_X */
	{"STAT_SWIN_BLK_NUM_Y", 0, 4, RW, 0x0}, /* PAFSTAT_STAT_SWIN_BLK_NUM_Y */
	{"STAT_SWIN_BLK_SIZE_X", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_SWIN_BLK_SIZE_X */
	{"STAT_SWIN_BLK_SIZE_Y", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_SWIN_BLK_SIZE_Y */
	{"STAT_SWIN_POS_STA_X", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_SWIN_POS_STA_X */
	{"STAT_SWIN_POS_STA_Y", 0, 13, RW, 0x0},	/* PAFSTAT_STAT_SWIN_POS_STA_Y */
	{"STAT_FWIN_0_INTEGRAL_SHIFT", 0, 3, RW, 0x0},	/* PAFSTAT_STAT_FWIN_0_INTEGRAL_SHIFT */
	{"STAT_FWIN_1_INTEGRAL_SHIFT", 0, 3, RW, 0x0},	/* PAFSTAT_STAT_FWIN_1_INTEGRAL_SHIFT */
	{"STAT_FWIN_2_INTEGRAL_SHIFT", 0, 3, RW, 0x0},	/* PAFSTAT_STAT_FWIN_2_INTEGRAL_SHIFT */
	{"STAT_FWIN_3_INTEGRAL_SHIFT", 0, 3, RW, 0x0},	/* PAFSTAT_STAT_FWIN_3_INTEGRAL_SHIFT */
	{"STAT_FWIN_4_INTEGRAL_SHIFT", 0, 3, RW, 0x0},	/* PAFSTAT_STAT_FWIN_4_INTEGRAL_SHIFT */
	{"STAT_FWIN_5_INTEGRAL_SHIFT", 0, 3, RW, 0x0},	/* PAFSTAT_STAT_FWIN_5_INTEGRAL_SHIFT */
	{"STAT_FWIN_0_LPF_COEF0", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_0_LPF_COEF0 */
	{"STAT_FWIN_0_LPF_COEF1", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_0_LPF_COEF1 */
	{"STAT_FWIN_0_LPF_COEF2", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_0_LPF_COEF2 */
	{"STAT_FWIN_0_LPF_COEF3", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_0_LPF_COEF3 */
	{"STAT_FWIN_1_LPF_COEF0", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_1_LPF_COEF0 */
	{"STAT_FWIN_1_LPF_COEF1", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_1_LPF_COEF1 */
	{"STAT_FWIN_1_LPF_COEF2", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_1_LPF_COEF2 */
	{"STAT_FWIN_1_LPF_COEF3", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_1_LPF_COEF3 */
	{"STAT_FWIN_2_LPF_COEF0", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_2_LPF_COEF0 */
	{"STAT_FWIN_2_LPF_COEF1", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_2_LPF_COEF1 */
	{"STAT_FWIN_2_LPF_COEF2", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_2_LPF_COEF2 */
	{"STAT_FWIN_2_LPF_COEF3", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_2_LPF_COEF3 */
	{"STAT_FWIN_3_LPF_COEF0", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_3_LPF_COEF0 */
	{"STAT_FWIN_3_LPF_COEF1", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_3_LPF_COEF1 */
	{"STAT_FWIN_3_LPF_COEF2", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_3_LPF_COEF2 */
	{"STAT_FWIN_3_LPF_COEF3", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_3_LPF_COEF3 */
	{"STAT_FWIN_4_LPF_COEF0", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_4_LPF_COEF0 */
	{"STAT_FWIN_4_LPF_COEF1", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_4_LPF_COEF1 */
	{"STAT_FWIN_4_LPF_COEF2", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_4_LPF_COEF2 */
	{"STAT_FWIN_4_LPF_COEF3", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_4_LPF_COEF3 */
	{"STAT_FWIN_5_LPF_COEF0", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_5_LPF_COEF0 */
	{"STAT_FWIN_5_LPF_COEF1", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_5_LPF_COEF1 */
	{"STAT_FWIN_5_LPF_COEF2", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_5_LPF_COEF2 */
	{"STAT_FWIN_5_LPF_COEF3", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_5_LPF_COEF3 */
	{"STAT_FWIN_0_LPF_COEF_SHIFT", 0, 3, RW, 0x0},	/* PAFSTAT_STAT_FWIN_0_LPF_COEF_SHIFT */
	{"STAT_FWIN_1_LPF_COEF_SHIFT", 0, 3, RW, 0x0},	/* PAFSTAT_STAT_FWIN_1_LPF_COEF_SHIFT */
	{"STAT_FWIN_2_LPF_COEF_SHIFT", 0, 3, RW, 0x0},	/* PAFSTAT_STAT_FWIN_2_LPF_COEF_SHIFT */
	{"STAT_FWIN_3_LPF_COEF_SHIFT", 0, 3, RW, 0x0},	/* PAFSTAT_STAT_FWIN_3_LPF_COEF_SHIFT */
	{"STAT_FWIN_4_LPF_COEF_SHIFT", 0, 3, RW, 0x0},	/* PAFSTAT_STAT_FWIN_4_LPF_COEF_SHIFT */
	{"STAT_FWIN_5_LPF_COEF_SHIFT", 0, 3, RW, 0x0},	/* PAFSTAT_STAT_FWIN_5_LPF_COEF_SHIFT */
	{"STAT_FWIN_0_GRAD_COEF0", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_0_GRAD_COEF0 */
	{"STAT_FWIN_0_GRAD_COEF1", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_0_GRAD_COEF1 */
	{"STAT_FWIN_0_GRAD_COEF2", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_0_GRAD_COEF2 */
	{"STAT_FWIN_0_GRAD_COEF3", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_0_GRAD_COEF3 */
	{"STAT_FWIN_1_GRAD_COEF0", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_1_GRAD_COEF0 */
	{"STAT_FWIN_1_GRAD_COEF1", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_1_GRAD_COEF1 */
	{"STAT_FWIN_1_GRAD_COEF2", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_1_GRAD_COEF2 */
	{"STAT_FWIN_1_GRAD_COEF3", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_1_GRAD_COEF3 */
	{"STAT_FWIN_2_GRAD_COEF0", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_2_GRAD_COEF0 */
	{"STAT_FWIN_2_GRAD_COEF1", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_2_GRAD_COEF1 */
	{"STAT_FWIN_2_GRAD_COEF2", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_2_GRAD_COEF2 */
	{"STAT_FWIN_2_GRAD_COEF3", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_2_GRAD_COEF3 */
	{"STAT_FWIN_3_GRAD_COEF0", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_3_GRAD_COEF0 */
	{"STAT_FWIN_3_GRAD_COEF1", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_3_GRAD_COEF1 */
	{"STAT_FWIN_3_GRAD_COEF2", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_3_GRAD_COEF2 */
	{"STAT_FWIN_3_GRAD_COEF3", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_3_GRAD_COEF3 */
	{"STAT_FWIN_4_GRAD_COEF0", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_4_GRAD_COEF0 */
	{"STAT_FWIN_4_GRAD_COEF1", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_4_GRAD_COEF1 */
	{"STAT_FWIN_4_GRAD_COEF2", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_4_GRAD_COEF2 */
	{"STAT_FWIN_4_GRAD_COEF3", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_4_GRAD_COEF3 */
	{"STAT_FWIN_5_GRAD_COEF0", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_5_GRAD_COEF0 */
	{"STAT_FWIN_5_GRAD_COEF1", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_5_GRAD_COEF1 */
	{"STAT_FWIN_5_GRAD_COEF2", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_5_GRAD_COEF2 */
	{"STAT_FWIN_5_GRAD_COEF3", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_5_GRAD_COEF3 */
	{"STAT_FWIN_0_GRAD_COEF_SHIFT", 0, 3, RW, 0x0}, /* PAFSTAT_STAT_FWIN_0_GRAD_COEF_SHIFT */
	{"STAT_FWIN_1_GRAD_COEF_SHIFT", 0, 3, RW, 0x0}, /* PAFSTAT_STAT_FWIN_1_GRAD_COEF_SHIFT */
	{"STAT_FWIN_2_GRAD_COEF_SHIFT", 0, 3, RW, 0x0}, /* PAFSTAT_STAT_FWIN_2_GRAD_COEF_SHIFT */
	{"STAT_FWIN_3_GRAD_COEF_SHIFT", 0, 3, RW, 0x0}, /* PAFSTAT_STAT_FWIN_3_GRAD_COEF_SHIFT */
	{"STAT_FWIN_4_GRAD_COEF_SHIFT", 0, 3, RW, 0x0}, /* PAFSTAT_STAT_FWIN_4_GRAD_COEF_SHIFT */
	{"STAT_FWIN_5_GRAD_COEF_SHIFT", 0, 3, RW, 0x0}, /* PAFSTAT_STAT_FWIN_5_GRAD_COEF_SHIFT */
	{"STAT_SWIN_INTEGRAL_SHIFT", 0, 3, RW, 0x0},	/* PAFSTAT_STAT_SWIN_INTEGRAL_SHIFT */
	{"STAT_SWIN_LPF_COEF0", 0, 8, RW, 0x0}, /* PAFSTAT_STAT_SWIN_LPF_COEF0 */
	{"STAT_SWIN_LPF_COEF1", 0, 8, RW, 0x0}, /* PAFSTAT_STAT_SWIN_LPF_COEF1 */
	{"STAT_SWIN_LPF_COEF2", 0, 8, RW, 0x0}, /* PAFSTAT_STAT_SWIN_LPF_COEF2 */
	{"STAT_SWIN_LPF_COEF3", 0, 8, RW, 0x0}, /* PAFSTAT_STAT_SWIN_LPF_COEF3 */
	{"STAT_SWIN_LPF_COEF_SHIFT", 0, 3, RW, 0x0},	/* PAFSTAT_STAT_SWIN_LPF_COEF_SHIFT */
	{"STAT_SWIN_GRAD_COEF0", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_SWIN_GRAD_COEF0 */
	{"STAT_SWIN_GRAD_COEF1", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_SWIN_GRAD_COEF1 */
	{"STAT_SWIN_GRAD_COEF2", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_SWIN_GRAD_COEF2 */
	{"STAT_SWIN_GRAD_COEF3", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_SWIN_GRAD_COEF3 */
	{"STAT_SWIN_GRAD_COEF_SHIFT", 0, 3, RW, 0x0},	/* PAFSTAT_STAT_SWIN_GRAD_COEF_SHIFT */
	{"STAT_FWIN_0_CORR_SHIFT", 0, 5, RW, 0x0},	/* PAFSTAT_STAT_FWIN_0_CORR_SHIFT */
	{"STAT_FWIN_1_CORR_SHIFT", 0, 5, RW, 0x0},	/* PAFSTAT_STAT_FWIN_1_CORR_SHIFT */
	{"STAT_FWIN_2_CORR_SHIFT", 0, 5, RW, 0x0},	/* PAFSTAT_STAT_FWIN_2_CORR_SHIFT */
	{"STAT_FWIN_3_CORR_SHIFT", 0, 5, RW, 0x0},	/* PAFSTAT_STAT_FWIN_3_CORR_SHIFT */
	{"STAT_FWIN_4_CORR_SHIFT", 0, 5, RW, 0x0},	/* PAFSTAT_STAT_FWIN_4_CORR_SHIFT */
	{"STAT_FWIN_5_CORR_SHIFT", 0, 5, RW, 0x0},	/* PAFSTAT_STAT_FWIN_5_CORR_SHIFT */
	{"STAT_SWIN_CORR_SHIFT", 0, 5, RW, 0x0},	/* PAFSTAT_STAT_SWIN_CORR_SHIFT */
	{"STAT_RESULT_OUT_FW0_START_ADDR", 0, 7, RW, 0x0},	/* PAFSTAT_STAT_RESULT_OUT_FW0_START_ADDR */
	{"STAT_RESULT_OUT_FW0_ACCESS", 0, 32, RWI, 0x0},	/* PAFSTAT_STAT_RESULT_OUT_FW0_ACCESS */
	{"STAT_RESULT_OUT_FW1_START_ADDR", 0, 7, RW, 0x0},	/* PAFSTAT_STAT_RESULT_OUT_FW1_START_ADDR */
	{"STAT_RESULT_OUT_FW1_ACCESS", 0, 32, RWI, 0x0},	/* PAFSTAT_STAT_RESULT_OUT_FW1_ACCESS */
	{"STAT_RESULT_OUT_FW2_START_ADDR", 0, 7, RW, 0x0},	/* PAFSTAT_STAT_RESULT_OUT_FW2_START_ADDR */
	{"STAT_RESULT_OUT_FW2_ACCESS", 0, 32, RWI, 0x0},	/* PAFSTAT_STAT_RESULT_OUT_FW2_ACCESS */
	{"STAT_RESULT_OUT_FW3_START_ADDR", 0, 7, RW, 0x0},	/* PAFSTAT_STAT_RESULT_OUT_FW3_START_ADDR */
	{"STAT_RESULT_OUT_FW3_ACCESS", 0, 32, RWI, 0x0},	/* PAFSTAT_STAT_RESULT_OUT_FW3_ACCESS */
	{"STAT_RESULT_OUT_FW4_START_ADDR", 0, 7, RW, 0x0},	/* PAFSTAT_STAT_RESULT_OUT_FW4_START_ADDR */
	{"STAT_RESULT_OUT_FW4_ACCESS", 0, 32, RWI, 0x0},	/* PAFSTAT_STAT_RESULT_OUT_FW4_ACCESS */
	{"STAT_RESULT_OUT_FW5_START_ADDR", 0, 9, RW, 0x0},	/* PAFSTAT_STAT_RESULT_OUT_FW5_START_ADDR */
	{"STAT_RESULT_OUT_FW5_ACCESS", 0, 32, RWI, 0x0},	/* PAFSTAT_STAT_RESULT_OUT_FW5_ACCESS */
	{"STAT_FWIN_INTEGRAL_CRC_SEED", 0, 8, RW, 0x0}, /* PAFSTAT_STAT_FWIN_INTEGRAL_CRC_SEED */
	{"STAT_FWIN_INTEGRAL_CRC_RESULT", 0, 8, RWI, 0x0},	/* PAFSTAT_STAT_FWIN_INTEGRAL_CRC_RESULT */
	{"STAT_FWIN_UPSAMPLE_CRC_SEED", 0, 8, RW, 0x0}, /* PAFSTAT_STAT_FWIN_UPSAMPLE_CRC_SEED */
	{"STAT_FWIN_UPSAMPLE_CRC_RESULT", 0, 8, RWI, 0x0},	/* PAFSTAT_STAT_FWIN_UPSAMPLE_CRC_RESULT */
	{"STAT_FWIN_LPF_CRC_SEED", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_FWIN_LPF_CRC_SEED */
	{"STAT_FWIN_LPF_CRC_RESULT", 0, 8, RWI, 0x0},	/* PAFSTAT_STAT_FWIN_LPF_CRC_RESULT */
	{"STAT_FWIN_GRAD_CRC_SEED", 0, 8, RW, 0x0}, /* PAFSTAT_STAT_FWIN_GRAD_CRC_SEED */
	{"STAT_FWIN_GRAD_CRC_RESULT", 0, 8, RWI, 0x0},	/* PAFSTAT_STAT_FWIN_GRAD_CRC_RESULT */
	{"STAT_SWIN_INTEGRAL_CRC_SEED", 0, 8, RW, 0x0}, /* PAFSTAT_STAT_SWIN_INTEGRAL_CRC_SEED */
	{"STAT_SWIN_INTEGRAL_CRC_RESULT", 0, 8, RWI, 0x0},	/* PAFSTAT_STAT_SWIN_INTEGRAL_CRC_RESULT */
	{"STAT_SWIN_UPSAMPLE_CRC_SEED", 0, 8, RW, 0x0}, /* PAFSTAT_STAT_SWIN_UPSAMPLE_CRC_SEED */
	{"STAT_SWIN_UPSAMPLE_CRC_RESULT", 0, 8, RWI, 0x0},	/* PAFSTAT_STAT_SWIN_UPSAMPLE_CRC_RESULT */
	{"STAT_SWIN_LPF_CRC_SEED", 0, 8, RW, 0x0},	/* PAFSTAT_STAT_SWIN_LPF_CRC_SEED */
	{"STAT_SWIN_LPF_CRC_RESULT", 0, 8, RWI, 0x0},	/* PAFSTAT_STAT_SWIN_LPF_CRC_RESULT */
	{"STAT_SWIN_GRAD_CRC_SEED", 0, 8, RW, 0x0}, /* PAFSTAT_STAT_SWIN_GRAD_CRC_SEED */
	{"STAT_SWIN_GRAD_CRC_RESULT", 0, 8, RWI, 0x0},	/* PAFSTAT_STAT_SWIN_GRAD_CRC_RESULT */
	{"AFIDENT_BYPASS", 0, 1, RW, 0x1},	/* PAFSTAT_AFIDENT_BYPASS */
	{"AFIDENT_START_ACTIVE_X", 0, 13, RW, 0x0}, /* PAFSTAT_AFIDENT_START_ACTIVE_X */
	{"AFIDENT_START_ACTIVE_Y", 0, 13, RW, 0x0}, /* PAFSTAT_AFIDENT_START_ACTIVE_Y */
	{"AFIDENT_ACTIVE_WIDTH", 0, 13, RW, 0x1bfc},	/* PAFSTAT_AFIDENT_ACTIVE_WIDTH */
	{"AFIDENT_ACTIVE_HEIGHT", 0, 13, RW, 0x10cc},	/* PAFSTAT_AFIDENT_ACTIVE_HEIGHT */
	{"AFIDENT_UNIT_OFFSET_X", 0, 4, RW, 0x0},	/* PAFSTAT_AFIDENT_UNIT_OFFSET_X */
	{"AFIDENT_UNIT_OFFSET_Y", 0, 4, RW, 0x0},	/* PAFSTAT_AFIDENT_UNIT_OFFSET_Y */
	{"AFIDENT_RELATIVE_OFFSET_X", 0, 6, RW, 0x0},	/* PAFSTAT_AFIDENT_RELATIVE_OFFSET_X */
	{"AFIDENT_RELATIVE_OFFSET_Y", 0, 6, RW, 0x0},	/* PAFSTAT_AFIDENT_RELATIVE_OFFSET_Y */
	{"AFIDENT_OUTPUT_TYPE0", 0, 3, RW, 0x0},	/* PAFSTAT_AFIDENT_OUTPUT_TYPE0 */
	{"AFIDENT_BLOCKS_PER_ACTIVE_X", 0, 11, RW, 0x0},	/* PAFSTAT_AFIDENT_BLOCKS_PER_ACTIVE_X */
	{"AFIDENT_BLOCKS_PER_ACTIVE_Y", 0, 11, RW, 0x0},	/* PAFSTAT_AFIDENT_BLOCKS_PER_ACTIVE_Y */
	{"AFIDENT_DATA_IN_TAIL", 0, 1, RW, 0x0},	/* PAFSTAT_AFIDENT_DATA_IN_TAIL */
	{"AFIDENT_TAIL_START", 0, 13, RW, 0x0}, /* PAFSTAT_AFIDENT_TAIL_START */
	{"AFIDENT_TAIL_SPLIT", 0, 1, RW, 0x0},	/* PAFSTAT_AFIDENT_TAIL_SPLIT */
	{"AFIDENT_BLOCKS_FIRST_SPLIT_TAIL", 0, 11, RW, 0x0},	/* PAFSTAT_AFIDENT_BLOCKS_FIRST_SPLIT_TAIL */
	{"AFIDENT_BLOCKS_SECOND_SPLIT_TAIL", 0, 11, RW, 0x0},	/* PAFSTAT_AFIDENT_BLOCKS_SECOND_SPLIT_TAIL */
	{"AFIDENT_UNIT_SIZE_X", 0, 7, RW, 0xc}, /* PAFSTAT_AFIDENT_UNIT_SIZE_X */
	{"AFIDENT_UNIT_SIZE_Y", 0, 7, RW, 0x14},	/* PAFSTAT_AFIDENT_UNIT_SIZE_Y */
	{"AFIDENT_PTRN_X_0_1", 8, 6, RW, 0x3},	/* PAFSTAT_AFIDENT_PTRN_X_0 */
	{"AFIDENT_PTRN_X_0_0", 0, 6, RW, 0x2},	/* PAFSTAT_AFIDENT_PTRN_X_0 */
	{"AFIDENT_PTRN_X_1_1", 8, 6, RW, 0x7},	/* PAFSTAT_AFIDENT_PTRN_X_1 */
	{"AFIDENT_PTRN_X_1_0", 0, 6, RW, 0x6},	/* PAFSTAT_AFIDENT_PTRN_X_1 */
	{"AFIDENT_PTRN_X_2_1", 8, 6, RW, 0xb},	/* PAFSTAT_AFIDENT_PTRN_X_2 */
	{"AFIDENT_PTRN_X_2_0", 0, 6, RW, 0xa},	/* PAFSTAT_AFIDENT_PTRN_X_2 */
	{"AFIDENT_PTRN_X_3_1", 8, 6, RW, 0x6},	/* PAFSTAT_AFIDENT_PTRN_X_3 */
	{"AFIDENT_PTRN_X_3_0", 0, 6, RW, 0x6},	/* PAFSTAT_AFIDENT_PTRN_X_3 */
	{"AFIDENT_PTRN_X_4_1", 8, 6, RW, 0x6},	/* PAFSTAT_AFIDENT_PTRN_X_4 */
	{"AFIDENT_PTRN_X_4_0", 0, 6, RW, 0x6},	/* PAFSTAT_AFIDENT_PTRN_X_4 */
	{"AFIDENT_PTRN_X_5_1", 8, 6, RW, 0xa},	/* PAFSTAT_AFIDENT_PTRN_X_5 */
	{"AFIDENT_PTRN_X_5_0", 0, 6, RW, 0xa},	/* PAFSTAT_AFIDENT_PTRN_X_5 */
	{"AFIDENT_PTRN_X_6_1", 8, 6, RW, 0xa},	/* PAFSTAT_AFIDENT_PTRN_X_6 */
	{"AFIDENT_PTRN_X_6_0", 0, 6, RW, 0xa},	/* PAFSTAT_AFIDENT_PTRN_X_6 */
	{"AFIDENT_PTRN_X_7_1", 8, 6, RW, 0x6},	/* PAFSTAT_AFIDENT_PTRN_X_7 */
	{"AFIDENT_PTRN_X_7_0", 0, 6, RW, 0x6},	/* PAFSTAT_AFIDENT_PTRN_X_7 */
	{"AFIDENT_PTRN_Y_0_1", 8, 6, RW, 0x4},	/* PAFSTAT_AFIDENT_PTRN_Y_0 */
	{"AFIDENT_PTRN_Y_0_0", 0, 6, RW, 0x1},	/* PAFSTAT_AFIDENT_PTRN_Y_0 */
	{"AFIDENT_PTRN_Y_1_1", 8, 6, RW, 0x4},	/* PAFSTAT_AFIDENT_PTRN_Y_1 */
	{"AFIDENT_PTRN_Y_1_0", 0, 6, RW, 0x1},	/* PAFSTAT_AFIDENT_PTRN_Y_1 */
	{"AFIDENT_PTRN_Y_2_1", 8, 6, RW, 0x4},	/* PAFSTAT_AFIDENT_PTRN_Y_2 */
	{"AFIDENT_PTRN_Y_2_0", 0, 6, RW, 0x1},	/* PAFSTAT_AFIDENT_PTRN_Y_2 */
	{"AFIDENT_PTRN_Y_3_1", 8, 6, RW, 0xb},	/* PAFSTAT_AFIDENT_PTRN_Y_3 */
	{"AFIDENT_PTRN_Y_3_0", 0, 6, RW, 0xa},	/* PAFSTAT_AFIDENT_PTRN_Y_3 */
	{"AFIDENT_PTRN_Y_4_1", 8, 6, RW, 0x6},	/* PAFSTAT_AFIDENT_PTRN_Y_4 */
	{"AFIDENT_PTRN_Y_4_0", 0, 6, RW, 0x7},	/* PAFSTAT_AFIDENT_PTRN_Y_4 */
	{"AFIDENT_PTRN_Y_5_1", 8, 6, RW, 0x6},	/* PAFSTAT_AFIDENT_PTRN_Y_5 */
	{"AFIDENT_PTRN_Y_5_0", 0, 6, RW, 0x7},	/* PAFSTAT_AFIDENT_PTRN_Y_5 */
	{"AFIDENT_PTRN_Y_6_1", 8, 6, RW, 0xa},	/* PAFSTAT_AFIDENT_PTRN_Y_6 */
	{"AFIDENT_PTRN_Y_6_0", 0, 6, RW, 0xb},	/* PAFSTAT_AFIDENT_PTRN_Y_6 */
	{"AFIDENT_PTRN_Y_7_1", 8, 6, RW, 0xa},	/* PAFSTAT_AFIDENT_PTRN_Y_7 */
	{"AFIDENT_PTRN_Y_7_0", 0, 6, RW, 0xb},	/* PAFSTAT_AFIDENT_PTRN_Y_7 */
	{"AFIDENT_UNITS_PER_BLOCK_X", 0, 5, RW, 0x1},	/* PAFSTAT_AFIDENT_UNITS_PER_BLOCK_X */
	{"AFIDENT_UNITS_PER_BLOCK_Y", 0, 5, RW, 0x6},	/* PAFSTAT_AFIDENT_UNIS_PER_BLOCK_Y */
	{"AFIDENT_PTRN_TYPE_0_3", 12, 3, RW, 0x1},	/* PAFSTAT_AFIDENT_PTRN_0 */
	{"AFIDENT_PTRN_TYPE_0_2", 8, 3, RW, 0x1},	/* PAFSTAT_AFIDENT_PTRN_0 */
	{"AFIDENT_PTRN_TYPE_0_1", 4, 3, RW, 0x0},	/* PAFSTAT_AFIDENT_PTRN_0 */
	{"AFIDENT_PTRN_TYPE_0_0", 0, 3, RW, 0x0},	/* PAFSTAT_AFIDENT_PTRN_0 */
	{"AFIDENT_PTRN_TYPE_0_7", 12, 3, RW, 0x0},	/* PAFSTAT_AFIDENT_PTRN_1 */
	{"AFIDENT_PTRN_TYPE_0_6", 8, 3, RW, 0x0},	/* PAFSTAT_AFIDENT_PTRN_1 */
	{"AFIDENT_PTRN_TYPE_0_5", 4, 3, RW, 0x2},	/* PAFSTAT_AFIDENT_PTRN_1 */
	{"AFIDENT_PTRN_TYPE_0_4", 0, 3, RW, 0x2},	/* PAFSTAT_AFIDENT_PTRN_1 */
	{"AFIDENT_PTRN_TYPE_0_11", 12, 3, RW, 0x0}, /* PAFSTAT_AFIDENT_PTRN_2 */
	{"AFIDENT_PTRN_TYPE_0_10", 8, 3, RW, 0x0},	/* PAFSTAT_AFIDENT_PTRN_2 */
	{"AFIDENT_PTRN_TYPE_0_9", 4, 3, RW, 0x0},	/* PAFSTAT_AFIDENT_PTRN_2 */
	{"AFIDENT_PTRN_TYPE_0_8", 0, 3, RW, 0x0},	/* PAFSTAT_AFIDENT_PTRN_2 */
	{"AFIDENT_PTRN_TYPE_0_15", 12, 3, RW, 0x0}, /* PAFSTAT_AFIDENT_PTRN_3 */
	{"AFIDENT_PTRN_TYPE_0_14", 8, 3, RW, 0x0},	/* PAFSTAT_AFIDENT_PTRN_3 */
	{"AFIDENT_PTRN_TYPE_0_13", 4, 3, RW, 0x0},	/* PAFSTAT_AFIDENT_PTRN_3 */
	{"AFIDENT_PTRN_TYPE_0_12", 0, 3, RW, 0x0},	/* PAFSTAT_AFIDENT_PTRN_3 */
	{"AFIDENT_SWITCHED_PTRN_0_15", 15, 1, RW, 0x0}, /* PAFSTAT_AFIDENT_SWITCHED_PTRN */
	{"AFIDENT_SWITCHED_PTRN_0_14", 14, 1, RW, 0x0}, /* PAFSTAT_AFIDENT_SWITCHED_PTRN */
	{"AFIDENT_SWITCHED_PTRN_0_13", 13, 1, RW, 0x0}, /* PAFSTAT_AFIDENT_SWITCHED_PTRN */
	{"AFIDENT_SWITCHED_PTRN_0_12", 12, 1, RW, 0x0}, /* PAFSTAT_AFIDENT_SWITCHED_PTRN */
	{"AFIDENT_SWITCHED_PTRN_0_11", 11, 1, RW, 0x0}, /* PAFSTAT_AFIDENT_SWITCHED_PTRN */
	{"AFIDENT_SWITCHED_PTRN_0_10", 10, 1, RW, 0x0}, /* PAFSTAT_AFIDENT_SWITCHED_PTRN */
	{"AFIDENT_SWITCHED_PTRN_0_9", 9, 1, RW, 0x0},	/* PAFSTAT_AFIDENT_SWITCHED_PTRN */
	{"AFIDENT_SWITCHED_PTRN_0_8", 8, 1, RW, 0x0},	/* PAFSTAT_AFIDENT_SWITCHED_PTRN */
	{"AFIDENT_SWITCHED_PTRN_0_7", 7, 1, RW, 0x0},	/* PAFSTAT_AFIDENT_SWITCHED_PTRN */
	{"AFIDENT_SWITCHED_PTRN_0_6", 6, 1, RW, 0x0},	/* PAFSTAT_AFIDENT_SWITCHED_PTRN */
	{"AFIDENT_SWITCHED_PTRN_0_5", 5, 1, RW, 0x1},	/* PAFSTAT_AFIDENT_SWITCHED_PTRN */
	{"AFIDENT_SWITCHED_PTRN_0_4", 4, 1, RW, 0x0},	/* PAFSTAT_AFIDENT_SWITCHED_PTRN */
	{"AFIDENT_SWITCHED_PTRN_0_3", 3, 1, RW, 0x1},	/* PAFSTAT_AFIDENT_SWITCHED_PTRN */
	{"AFIDENT_SWITCHED_PTRN_0_2", 2, 1, RW, 0x0},	/* PAFSTAT_AFIDENT_SWITCHED_PTRN */
	{"AFIDENT_SWITCHED_PTRN_0_1", 1, 1, RW, 0x1},	/* PAFSTAT_AFIDENT_SWITCHED_PTRN */
	{"AFIDENT_SWITCHED_PTRN_0_0", 0, 1, RW, 0x0},	/* PAFSTAT_AFIDENT_SWITCHED_PTRN */
	{"AFIDENT_RATE_CNTRL_EN", 0, 1, RW, 0x0},	/* PAFSTAT_AFIDENT_RATE_CNTRL_EN */
	{"AFIDENT_PIXELS_GAP2", 8, 7, RW, 0x0}, /* PAFSTAT_AFIDENT_PIXELS_GAP */
	{"AFIDENT_PIXELS_GAP1", 0, 7, RW, 0x0}, /* PAFSTAT_AFIDENT_PIXELS_GAP */
	{"AFIDENT_REG_INTERFACE_VER", 0, 16, RWI, 0xa}, /* PAFSTAT_AFIDENT_REG_INTERFACE_VER */
	{"AFIDENT_BLOCK_ID_CODE", 0, 16, RWI, 0xbea9},	/* PAFSTAT_AFIDENT_BLOCK_ID_CODE */
	{"AFIDENT_VERSION_ID_CODE", 0, 16, RWI, 0x442}, /* PAFSTAT_AFIDENT_VERSION_ID_CODE */
	{"AFIDENT_CRC_RESULT", 8, 8, RWI, 0x0}, /* PAFSTAT_AFIDENT_STREAM_CRC */
	{"AFIDENT_CRC_SEED", 0, 8, RW, 0x0},	/* PAFSTAT_AFIDENT_STREAM_CRC */
	{"LBCTRL_BYPASS", 0, 1, RW, 0x0},	/* PAFSTAT_LBCTRL_BYPASS */
	{"LBCTRL_IMG_HEIGHT", 16, 14, RW, 0x0}, /* PAFSTAT_LBCTRL_IMAGE_SIZE */
	{"LBCTRL_IMG_WIDTH", 0, 14, RW, 0x0},	/* PAFSTAT_LBCTRL_IMAGE_SIZE */
	{"LBCTRL_BPC_MODE", 0, 1, RW, 0x0}, /* PAFSTAT_LBCTRL_BPC_MODE */
};

/* PAFSTAT_RDMA */
enum fimc_is_hw_pafstat_rdma_reg_name {
	PAFSTAT_RDMA_R_RDMA_COM_RESET,
	PAFSTAT_RDMA_R_RDMA_COM_RESET_STATUS,
	PAFSTAT_RDMA_R_RDMA_COM_QACTIVE,
	PAFSTAT_RDMA_R_RDMA_I_EN,
	PAFSTAT_RDMA_R_RDMA_I_DATA_FORMAT,
	PAFSTAT_RDMA_R_RDMA_I_IMG_WIDTH,
	PAFSTAT_RDMA_R_RDMA_I_IMG_HEIGHT,
	PAFSTAT_RDMA_R_RDMA_I_IMG_STRIDE,
	PAFSTAT_RDMA_R_RDMA_I_BASE_ADDR,
	PAFSTAT_RDMA_REG_CNT
};

static struct fimc_is_reg pafstat_rdma_regs[PAFSTAT_RDMA_REG_CNT] = {
	{0x0000, "RDMA_RESET"},
	{0x0004, "RDMA_RESET_STATUS"},
	{0x0008, "RDMA_QACTIVE"},
	{0x0100, "RDMA_I_EN"},
	{0x0104, "RDMA_I_DATA_FORMAT"},
	{0x0108, "RDMA_I_IMG_WIDTH"},
	{0x010C, "RDMA_I_IMG_HEIGHT"},
	{0x0110, "RDMA_I_IMG_STRIDE"},
	{0x0114, "RDMA_I_BASE_ADDR"},
};

enum fimc_is_hw_pafstat_rdma_reg_field {
	PAFSTAT_RDMA_F_COM_SW_RESET,
	PAFSTAT_RDMA_F_COM_SW_RESET_STATUS,
	PAFSTAT_RDMA_F_COM_RDMA_QACTIVE,
	PAFSTAT_RDMA_F_RDMA_I_EN,
	PAFSTAT_RDMA_F_RDMA_I_DATA_FORMAT,
	PAFSTAT_RDMA_F_RDMA_I_IMG_WIDTH,
	PAFSTAT_RDMA_F_RDMA_I_IMG_HEIGHT,
	PAFSTAT_RDMA_F_RDMA_I_IMG_STRIDE,
	PAFSTAT_RDMA_F_RDMA_I_BASE_ADDR,
	PAFSTAT_RDMA_REG_FIELD_CNT
};

static struct fimc_is_field pafstat_rdma_fields[PAFSTAT_RDMA_REG_FIELD_CNT] = {
/* field_name, start_bit, bit_width, type, reset */
	{"SW_RESET", 0, 1, RIW, 0x0},	/* RDMA_RESET */
	{"SW_RESET_STATUS", 0, 1, RWI, 0x0},	/* RDMA_RESET_STATUS */
	{"RDMA_QACTIVE", 0, 1, RW, 0x0},	/* RDMA_QACTIVE */
	{"RDMA_I_EN", 0, 1, RW, 0x0},	/* RDMA_I_EN */
	{"RDMA_I_DATA_FORMAT", 0, 3, RW, 0x0},	/* RDMA_I_DATA_FORMAT */
	{"RDMA_I_IMG_WIDTH", 0, 14, RW, 0x20},	/* RDMA_I_IMG_WIDTH */
	{"RDMA_I_IMG_HEIGHT", 0, 14, RW, 0x20},	/* RDMA_I_IMG_HEIGHT */
	{"RDMA_I_IMG_STRIDE", 0, 15, RW, 0x20},	/* RDMA_I_IMG_STRIDE */
	{"RDMA_I_BASE_ADDR", 0, 32, RW, 0x0},	/* RDMA_I_BASE_ADDR */
};

#endif
